In [2]:
%load_ext autoreload
%autoreload 2
%aimport src_config

In [3]:
%%time
from degiro.degiroUtils import _MODEL_STATS_PATH_    # "C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\laboratorio\\file\\processed\\parquet\\"
from degiro.degiroUtils import _MODEL_PATH_          # "C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\laboratorio\\file\\processed\\models\\"
from degiro import logger
from degiro.degiroUtils import downloader, anagrafica_builder
from degiro.degiroUtils import check_equality_btwn_df
import degiroapi
import degiro.degiroapi_mio as dg
from pathlib import Path
import pandas as pd
import numpy as np

Wall time: 32.5 s

In [48]:
def load_models_df(raw_file_path: Path, model_code: str):
    """
    """
    models = pd.read_parquet(path=raw_file_path / "models_{}.parquet".format(model_code), engine="fastparquet").set_index("index")
    models.index.name = None
    return models

def resume_models_df(grid_df: pd.DataFrame, raw_file_path: Path):
    """
    Fct for loading the saved model parametres through the PARAM_HASH key (index of the grid_df pd.DataFrame) and concatenate them building the models_df.
    The grid_df dataframe s index is PARAM_HASH and contains params, stats and MODEL_HASH (key for ) 
    """
    models = grid_df.reset_index().apply(lambda x: load_models_df(raw_file_path, x.PARAM_HASH), axis=1)
    models_df = pd.DataFrame()
    for _, model in models.iteritems():
        models_df = pd.concat([models_df, model])

    models_df.reset_index(inplace=True)
    models_df.rename(columns={"index" : "ISIN"}, inplace=True)
    models_df.set_index(["PARAM_HASH", "ISIN"], inplace=True)
    return models_df

def train_on_grid_refactor(
    global_param: dict, 
    grid_param: dict, 
    ts: pd.DataFrame, 
    return_stats: bool=True, 
    save: bool=False, 
    export_models: bool=False
    ):
    from copy import deepcopy
    import time
    from degiro.Timer import Timer
    from degiro.degiroUtils import rnn_save
    from degiro.degiroUtils import get_param_permutation
    #from tabulate import tabulate
    
    _BEST_CHOICE_CRITERIA_ = "TEST_LOSS_PERC"

    param_permutations = get_param_permutation(grid_param)
    total_permutations = len(param_permutations)

    param_df = pd.DataFrame()
    stats_df = pd.DataFrame()
    stats_models_df = pd.DataFrame()
    logger.debug("Total iterations...{}".format(total_permutations))
    
    timer = Timer(total_iterations=total_permutations)
    logger.debug(param_permutations)

    for iteration, model_p in enumerate(param_permutations):
        iteration += 1
        start_time = time.time()
        logger.debug(model_p)
        
        global_param.update(model_p)
        # Giro con save e return_stats defaultati a False e True -> train_models_on_df_refactor non scrive nulla
        it_stats_models, param_hash = train_models_on_df_refactor(
            ts=ts, 
            model_param=deepcopy(global_param), 
            return_stats=return_stats, 
            save=save
            )

        stats = it_stats_models[["TRAIN_LOSS", "TEST_LOSS", "VOL_IS", "VOL_OOS"]].describe()
        #print(tabulate(stats, headers='keys', tablefmt='psql'))

        stats["PARAM_HASH"] = param_hash
        stats.reset_index(inplace=True)
        stats.rename(columns={"index" : "STAT"}, inplace=True)
        stats.set_index(["PARAM_HASH", "STAT"], inplace=True)
        stats_df = pd.concat([stats_df, stats])

        param_tmp = pd.DataFrame(model_p, index=[param_hash])
        param_df = pd.concat([param_df, param_tmp])
        stats_models_df = pd.concat([stats_models_df, it_stats_models])

        logger.debug("Done {} -> {}%".format(iteration, (iteration)/total_permutations*100))

        timer.get_stats(start_time=start_time, iteration=iteration)

    param_df.index.name = "PARAM_HASH"
    
    # TODO: print best performer param
    # TODO: select best param per isin
    # TODO: save only best models
    stats_models_df.reset_index(inplace=True)
    stats_models_df.rename(columns={"index" : "ISIN"}, inplace=True)

    best_models_df = stats_models_df.loc[stats_models_df.groupby("ISIN")[_BEST_CHOICE_CRITERIA_].idxmin()].sort_values("PARAM_HASH").merge(
        param_df, left_on="PARAM_HASH", right_index=True
    )

    if export_models:
        # export_models a True
        logger.debug("Saving models...START")
        stats_models_df.apply(
            lambda x: rnn_save(x.MODEL, path=_MODEL_PATH_ / "{}".format(x.MODEL_HASH)), axis=1
            )
        logger.debug("Saving models...DONE")

        param_df.reset_index().to_parquet(_MODEL_STATS_PATH_ / "df_params.parquet", engine="fastparquet")
        stats_df.reset_index().to_parquet(_MODEL_STATS_PATH_ / "df_stats.parquet", engine="fastparquet")
        stats_models_df.drop(columns=["MODEL"]).reset_index().to_parquet(_MODEL_STATS_PATH_ / "df_stats_models.parquet", engine="fastparquet")
        best_models_df.drop(columns=["MODEL"]).reset_index().to_parquet(_MODEL_STATS_PATH_ / "df_best_models.parquet", engine="fastparquet")

    return param_df, stats_df, stats_models_df, best_models_df

def train_models_on_df_refactor(
    ts: pd.DataFrame, 
    model_param: dict, 
    return_stats: bool=True, 
    save: bool=False
    ):
    from degiro.degiroUtils import rnn_train, rnn_save, rnn_get_stats_2
    from degiro.degiroUtils import from_dict_values_to_hash, build_dict_for_hashing
    import datetime

    param_hash = from_dict_values_to_hash(model_param)
    logger.debug("Param ID...{}".format(param_hash))

    chunks_len = int(len(ts.columns)/model_param["chunks_num"])
    logger.debug("Isin per chunk...{}".format(chunks_len))

    rnn_models = pd.DataFrame(index=ts.columns, columns=["MODEL", "SCALER_MIN", "SCALER_MAX", "TRAIN_LOSS", "TEST_LOSS", "VOL_IS", "VOL_OOS", "MODEL_HASH"], data=None)
    # TODO: rnn_models.index.name = "ISIN"
    for chunk_num in range(model_param["chunks_num"]):
        logger.debug("Start trainig chunk...{}".format(chunk_num+1))
        columns = ts.columns[(chunk_num*chunks_len):(chunk_num*chunks_len+chunks_len)]
        #logger.debug("Working on : ", list(columns))

        model_tmp = ts[columns].apply(
            rnn_train, 
            epochs=model_param["epochs"], 
            look_back=model_param["look_back"], 
            batch_size=model_param["batch_size"], 
            loss=model_param["loss"], 
            optimizer=model_param["optimizer"], 
            lstm_dim=model_param["lstm_dim"], 
            dense_dim=model_param["dense_dim"], 
            result_type="expand", 
            verbose=0
            )

        model_tmp_t = model_tmp.T
        model_tmp_t["MODEL_HASH"] = None
        rnn_models.loc[columns] = pd.DataFrame(data=model_tmp_t).rename(columns={
            0 : "MODEL",
            1 : "SCALER_MIN",
            2 : "SCALER_MAX",
            3 : "TRAIN_LOSS",
            4 : "TEST_LOSS",
            5 : "VOL_IS",
            6 : "VOL_OOS"
        })

        rnn_models.loc[columns, "TIMESTAMP"] = datetime.datetime.now().timestamp()

        # Building model specific index (hashing isin, timestamp and param)
        rnn_models.loc[columns, "MODEL_HASH"] = (rnn_models.loc[columns].reset_index().rename(columns={"index" : "ISIN"}).apply(
            lambda x : from_dict_values_to_hash(
                build_dict_for_hashing(model_param, {"isin" : x.ISIN, "time" : x.TIMESTAMP})
            ), axis=1)).values

        logger.debug("Done {} -> {}%".format(chunk_num + 1, (chunk_num + 1)/model_param["chunks_num"]*100))

    logger.debug(f"Getting stats...")
    rnn_models[["TRAIN_LOSS", "TEST_LOSS", "VOL_IS", "VOL_OOS"]] = rnn_models.apply(
        lambda x: rnn_get_stats_2(
            model=x.MODEL, 
            dataset=ts[x.name], 
            look_back=model_param["look_back"]
            ), 
            result_type="expand", axis=1
        )

    rnn_models["AVERAGE_PRICE"]   = ts.mean()
    rnn_models["LOOK_BACK"]       = model_param["look_back"]
    rnn_models["LAST_PRICE"]      = ts.iloc[-1]
    rnn_models["TRAIN_LOSS_PERC"] = rnn_models["TRAIN_LOSS"].div(rnn_models["AVERAGE_PRICE"])
    rnn_models["TEST_LOSS_PERC"]  = rnn_models["TEST_LOSS"].div(rnn_models["AVERAGE_PRICE"])
    rnn_models["VOL_IS_PERC"]     = rnn_models["VOL_IS"].div(rnn_models["AVERAGE_PRICE"])
    rnn_models["VOL_OOS_PERC"]    = rnn_models["VOL_OOS"].div(rnn_models["AVERAGE_PRICE"])
    rnn_models["PARAM_HASH"]      = param_hash
    
    if save:
        # Droppo colonna MODEL ed esporto in raw_file_path
        logger.debug(f"Writing session to parquet...")
        rnn_models.reset_index().drop(columns=["MODEL"]).to_parquet(_MODEL_STATS_PATH_ / "models_{}.parquet".format(param_hash), engine="fastparquet")

        logger.debug(f"Saving models...")
        rnn_models.apply(
            lambda x: rnn_save(x.MODEL, path=_MODEL_PATH_ / "{}".format(x.MODEL_HASH)), axis=1
            )
        logger.debug(f"Models saved...")

    if return_stats:
        return rnn_models, param_hash

In [11]:
pd.options.display.max_columns = 200

"""
model_path = Path("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\laboratorio\\file\\processed\\models\\")
_MODEL_PATH_ = Path("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\laboratorio\\file\\processed\\models\\")
models_stats_path = Path("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\laboratorio\\file\\processed\\parquet\\")
_MODEL_STATS_PATH_ = Path("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\laboratorio\\file\\processed\\parquet\\")
"""
raw_file_path = Path("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\degiro\\degiro\\file\\raw\\")

degiro_conn = dg.DeGiro()
degiro_conn.login("Calsipher8", "Palazov13!")

{'data': {'id': 1858803,
  'intAccount': 111030591,
  'loggedInPersonId': 1861625,
  'clientRole': 'active',
  'effectiveClientRole': 'active',
  'isDebitMoneyEnabled': True,
  'contractType': 'PRIVATE',
  'username': 'Calsipher8',
  'displayName': 'OTTO FONTANESI',
  'email': 'otto.fonta@hotmail.it',
  'firstContact': {'firstName': 'OTTO',
   'lastName': 'FONTANESI',
   'displayName': 'OTTO FONTANESI',
   'nationality': 'IT',
   'gender': 'MALE',
   'dateOfBirth': '1990-02-11',
   'placeOfBirth': 'Sassuolo',
   'countryOfBirth': 'IT'},
  'address': {'streetAddress': 'Via Mezzacosta',
   'streetAddressNumber': '17',
   'zip': '40136',
   'city': 'Bologna',
   'country': 'IT'},
  'cellphoneNumber': 'REDACTED_PHONE',
  'locale': 'it_IT',
  'language': 'it',
  'culture': 'IT',
  'displayLanguage': 'it',
  'bankAccount': {'bankAccountId': 2796696,
   'bic': 'REDACTED_BIC',
   'iban': 'REDACTED_IBAN',
   'status': 'VERIFIED'},
  'flatexBankAccount': {'bic': 'REDACTED_BIC',
   'iban': 'REDACTED_IBAN'},
  'memberCode': 'REDACTED_MEMBER_CODE',
  'isWithdrawalAvailable': True,
  'isAllocationAvailable': True,
  'isIskClient': False,
  'isUsPerson': False,
  'isCollectivePortfolio': False,
  'isAmClientActive': False,
  'canEnableDebitMoney': False,
  'canUpgrade': True}}

# GET TS AND ANAGR -> EXPORT dax_anagrafica.parquet / ts_dax.parquet

In [9]:
index_id=6
stock_country_id=906

In [ ]:
%%time
"""
S&P : 
    index_id=14
    stock_country_id=846
"""
downloader(
    conn_degiro=degiro_conn, 
    index_id=index_id, 
    stock_country_id=stock_country_id, 
    raw_file_path=raw_file_path,
    time_span="1Y"
    )

DEGIRO - download_stock_info - DEBUG - 0 : 41 - 3457
DEGIRO - download_stock_info - DEBUG - 1 : 41 - 886838
DEGIRO - download_stock_info - DEBUG - 2 : 41 - 4799
DEGIRO - download_stock_info - DEBUG - 3 : 41 - 3572
DEGIRO - download_stock_info - DEBUG - 4 : 41 - 3934
DEGIRO - download_stock_info - DEBUG - 5 : 41 - 3597
DEGIRO - download_stock_info - DEBUG - 6 : 41 - 3607
DEGIRO - download_stock_info - DEBUG - 7 : 41 - 883883
DEGIRO - download_stock_info - DEBUG - 8 : 41 - 3765
DEGIRO - download_stock_info - DEBUG - 9 : 41 - 8071694
DEGIRO - download_stock_info - DEBUG - 10 : 41 - 13697828
DEGIRO - download_stock_info - DEBUG - 11 : 41 - 3560
DEGIRO - download_stock_info - DEBUG - 12 : 41 - 3982
DEGIRO - download_stock_info - DEBUG - 13 : 41 - 3873
DEGIRO - download_stock_info - DEBUG - 14 : 41 - 3877
DEGIRO - download_stock_info - DEBUG - 15 : 41 - 7102
DEGIRO - download_stock_info - DEBUG - 16 : 41 - 144781
DEGIRO - download_stock_info - DEBUG - 17 : 41 - 3963
DEGIRO - download_stock_info - DEBUG - 18 : 41 - 3959
DEGIRO - download_stock_info - DEBUG - 19 : 41 - 4076
DEGIRO - download_stock_info - DEBUG - 20 : 41 - 14015419
DEGIRO - download_stock_info - DEBUG - 21 : 41 - 4082
DEGIRO - download_stock_info - DEBUG - 22 : 41 - 4173
DEGIRO - download_stock_info - DEBUG - 23 : 41 - 15239084
DEGIRO - download_stock_info - DEBUG - 24 : 41 - 4448
DEGIRO - download_stock_info - DEBUG - 25 : 41 - 4294
DEGIRO - download_stock_info - DEBUG - 26 : 41 - 6907
DEGIRO - download_stock_info - DEBUG - 27 : 41 - 4818
DEGIRO - download_stock_info - DEBUG - 28 : 41 - 174861
DEGIRO - download_stock_info - DEBUG - 29 : 41 - 4409
DEGIRO - download_stock_info - DEBUG - 30 : 41 - 12858968
DEGIRO - download_stock_info - DEBUG - 31 : 41 - 4432
DEGIRO - download_stock_info - DEBUG - 32 : 41 - 4457
DEGIRO - download_stock_info - DEBUG - 33 : 41 - 883190
DEGIRO - download_stock_info - DEBUG - 34 : 41 - 4500
DEGIRO - download_stock_info - DEBUG - 35 : 41 - 18346283
DEGIRO - download_stock_info - DEBUG - 36 : 41 - 14466678
DEGIRO - download_stock_info - DEBUG - 37 : 41 - 7840
DEGIRO - download_stock_info - DEBUG - 38 : 41 - 4671
DEGIRO - download_stock_info - DEBUG - 39 : 41 - 4619302
DEGIRO - download_stock_info - DEBUG - 40 : 41 - 5281498
DEGIRO - download_stock_info - DEBUG -
Faild stocks 0
DEGIRO - download_stock_info - DEBUG - Success stocks 41
Pandas Apply: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 41/41 [00:00<?, ?it/s]
Pandas Apply:   0%|          | 0/41 [00:00<?, ?it/s]DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
Pandas Apply:  46%|â–ˆâ–ˆâ–ˆâ–ˆâ–‹     | 19/41 [00:00<00:00, 189.10it/s]DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
Pandas Apply:  90%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ | 37/41 [00:00<00:00, 178.59it/s]DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2021-05-13 00:00:00 to : 2022-05-13 00:00:00
Pandas Apply: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 41/41 [00:00<00:00, 162.54it/s]

Wall time: 20.4 s

In [12]:
def updater(
    conn_degiro: degiroapi.DeGiro, 
    index_id : int, 
    stock_country_id : int, 
    raw_file_path: Path,
    time_span: str="1Y"
    ) -> None:
    ts = pd.read_parquet(raw_file_path / f"{index_id}_{stock_country_id}_ts.parquet", engine="fastparquet")

    logger.debug("Dim old > rows : {} - cols : {}".format(ts.shape[0], ts.shape[1]))
    logger.debug("Date old > last date : {} - last date : {}".format(ts.index[0], ts.index[-1]))
    
    # scrivo le tmp in raw_file_path / tmp
    downloader(
        conn_degiro=conn_degiro, 
        index_id=index_id, 
        stock_country_id=stock_country_id, 
        raw_file_path=raw_file_path / "tmp",
        time_span=time_span
        )

    ts_new = pd.read_parquet(raw_file_path / "tmp" / f"{index_id}_{stock_country_id}_ts.parquet", engine="fastparquet")
    ts_up_to_date = pd.concat([ts, ts_new])
    ts_up_to_date = ts_up_to_date[~ts_up_to_date.sort_index().index.duplicated(keep='first')]

    logger.debug("Dim old > rows : {} - cols : {}".format(ts.shape[0], ts.shape[1]))
    logger.debug("Date new > last obs : {} - first obs : {}".format(ts.index[0], ts.index[-1]))

    ts_up_to_date.to_parquet(raw_file_path / f"{index_id}_{stock_country_id}_ts.parquet", engine="fastparquet")
    logger.debug("Dim new > rows : {} - cols : {}".format(ts_up_to_date.shape[0], ts_up_to_date.shape[1]))
    logger.debug("Date new > last obs : {} - first obs : {}".format(ts_up_to_date.index[0], ts_up_to_date.index[-1]))

    return None

In [13]:
updater(
    degiro_conn, 
    index_id=index_id, 
    stock_country_id=stock_country_id, 
    raw_file_path=raw_file_path,
    time_span="1Y"
)

DEGIRO - updater - DEBUG - Dim old > rows : 377 - cols : 41
DEGIRO - updater - DEBUG - Date old > last date : 2021-05-14 00:00:00 - last date : 2022-08-04 00:00:00
DEGIRO - download_stock_info - DEBUG - 0 : 40 - 3457
DEGIRO - download_stock_info - DEBUG - 1 : 40 - 886838
DEGIRO - download_stock_info - DEBUG - 2 : 40 - 4799
DEGIRO - download_stock_info - DEBUG - 3 : 40 - 3572
DEGIRO - download_stock_info - DEBUG - 4 : 40 - 3934
DEGIRO - download_stock_info - DEBUG - 5 : 40 - 3597
DEGIRO - download_stock_info - DEBUG - 6 : 40 - 3607
DEGIRO - download_stock_info - DEBUG - 7 : 40 - 883883
DEGIRO - download_stock_info - DEBUG - 8 : 40 - 1893017
DEGIRO - download_stock_info - DEBUG - 9 : 40 - 3765
DEGIRO - download_stock_info - DEBUG - 10 : 40 - 8071694
DEGIRO - download_stock_info - DEBUG - 11 : 40 - 20979466
DEGIRO - download_stock_info - DEBUG - 12 : 40 - 3560
DEGIRO - download_stock_info - DEBUG - 13 : 40 - 3982
DEGIRO - download_stock_info - DEBUG - 14 : 40 - 3873
DEGIRO - download_stock_info - DEBUG - 15 : 40 - 3877
DEGIRO - download_stock_info - DEBUG - 16 : 40 - 144781
DEGIRO - download_stock_info - DEBUG - 17 : 40 - 3959
DEGIRO - download_stock_info - DEBUG - 18 : 40 - 4797
DEGIRO - download_stock_info - DEBUG - 19 : 40 - 4076
DEGIRO - download_stock_info - DEBUG - 20 : 40 - 4082
DEGIRO - download_stock_info - DEBUG - 21 : 40 - 4173
DEGIRO - download_stock_info - DEBUG - 22 : 40 - 4448
DEGIRO - download_stock_info - DEBUG - 23 : 40 - 4294
DEGIRO - download_stock_info - DEBUG - 24 : 40 - 6907
DEGIRO - download_stock_info - DEBUG - 25 : 40 - 4818
DEGIRO - download_stock_info - DEBUG - 26 : 40 - 24014731
DEGIRO - download_stock_info - DEBUG - 27 : 40 - 174861
DEGIRO - download_stock_info - DEBUG - 28 : 40 - 12858968
DEGIRO - download_stock_info - DEBUG - 29 : 40 - 883182
DEGIRO - download_stock_info - DEBUG - 30 : 40 - 4432
DEGIRO - download_stock_info - DEBUG - 31 : 40 - 4457
DEGIRO - download_stock_info - DEBUG - 32 : 40 - 883190
DEGIRO - download_stock_info - DEBUG - 33 : 40 - 4500
DEGIRO - download_stock_info - DEBUG - 34 : 40 - 18346283
DEGIRO - download_stock_info - DEBUG - 35 : 40 - 14466678
DEGIRO - download_stock_info - DEBUG - 36 : 40 - 7840
DEGIRO - download_stock_info - DEBUG - 37 : 40 - 4671
DEGIRO - download_stock_info - DEBUG - 38 : 40 - 4619302
DEGIRO - download_stock_info - DEBUG - 39 : 40 - 5281498
DEGIRO - download_stock_info - DEBUG -
Faild stocks 0
DEGIRO - download_stock_info - DEBUG - Success stocks 40
Pandas Apply: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 40/40 [00:00<?, ?it/s]
Pandas Apply:   0%|          | 0/40 [00:00<?, ?it/s]DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
Pandas Apply:  45%|â–ˆâ–ˆâ–ˆâ–ˆâ–Œ     | 18/40 [00:00<00:00, 172.94it/s]DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
Pandas Apply:  75%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ  | 30/40 [00:00<00:00, 148.59it/s]DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
Pandas Apply:  98%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š| 39/40 [00:00<00:00, 120.64it/s]DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
DEGIRO - parse_hist_data - DEBUG - from : 2022-05-31 00:00:00 to : 2023-05-31 00:00:00
Pandas Apply: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 40/40 [00:00<00:00, 114.33it/s]
DEGIRO - updater - DEBUG - Dim old > rows : 377 - cols : 41
DEGIRO - updater - DEBUG - Date new > last obs : 2021-05-14 00:00:00 - first obs : 2022-08-04 00:00:00
DEGIRO - updater - DEBUG - Dim new > rows : 420 - cols : 46
DEGIRO - updater - DEBUG - Date new > last obs : 2021-05-14 00:00:00 - first obs : 2023-01-30 00:00:00

In [14]:
ts_dax = pd.read_parquet(raw_file_path / f"{index_id}_{stock_country_id}_ts.parquet", engine="fastparquet")
ts_dax.index[0], ts_dax.index[-1]

(Timestamp('2021-05-14 00:00:00'), Timestamp('2023-01-30 00:00:00'))

In [15]:
ts_dax.shape

(420, 46)

In [16]:
ts_dax.head()

,DE000A1EWWW0,NL0000235190,DE0008404005,DE000BASF111,DE000BAY0017,DE0005190003,DE0005200000,DE000A1DAHH0,DE0005439004,DE0006062144,DE000A2E4K43,DE0005140008,DE0005810055,DE0005552004,DE0005557508,DE000A0HN5C6,DE000ENAG999,DE0005785802,DE0005785604,DE0006047004,DE000A161408,DE0006048432,DE0006231004,IE00BZ12WP82,DE0007100000,DE0006599905,DE000A0D9PT0,DE0008430026,DE000PAH0038,DE0006969603,NL0012169213,DE0007037129,DE0007164600,DE0007165631,DE0007236101,DE000ENER6Y0,DE000SHL1006,DE000SYM9999,DE0007664039,DE000A1ML7J1,DE000ZAL1111,DE000CBK1001,DE000DTR0CK8,DE0008402215,DE000PAG9113,DE0007030009
DATE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2021-05-14,180.48,104.60,198.34,49.035,60.280,75.78,93.66,69.68,65.04,38.99,27.14,9.1320,162.75,37.950,17.948,25.82,9.964,56.70,33.210,52.44,35.89,62.74,27.600,288.65,63.51,160.10,177.25,227.30,76.44,64.00,42.51,38.66,93.40,312.50,113.90,15.625,52.90,101.35,146.44,33.00,33.09,NaN,NaN,NaN,NaN,NaN
2021-05-15,181.86,107.14,205.15,49.675,57.895,82.26,93.50,68.60,64.02,39.16,25.58,9.3230,162.10,37.725,17.510,25.82,10.230,58.74,34.165,54.80,34.84,63.32,26.765,288.65,63.86,169.30,180.05,227.50,76.44,65.56,42.56,40.41,92.96,330.80,116.80,16.275,51.64,100.95,147.06,34.17,31.97,NaN,NaN,NaN,NaN,NaN
2021-05-16,173.36,105.02,193.72,48.450,61.680,78.21,90.64,67.36,61.80,38.43,25.22,9.1010,161.30,37.335,17.280,24.99,9.854,58.42,33.240,54.14,33.72,63.24,25.760,285.30,61.13,165.10,174.45,217.00,72.34,63.03,42.10,39.49,91.66,317.50,114.72,16.685,50.84,99.94,143.28,32.84,32.53,NaN,NaN,NaN,NaN,NaN
2021-05-17,173.68,104.48,191.26,47.150,58.720,77.82,88.92,65.82,60.82,37.50,25.64,8.9560,158.50,36.210,17.142,24.88,9.764,57.54,34.050,53.74,34.43,61.42,25.575,285.65,60.56,163.65,179.25,213.70,74.48,63.36,42.98,40.03,90.77,316.10,111.94,16.630,49.70,98.10,142.31,32.71,31.94,NaN,NaN,NaN,NaN,NaN
2021-05-18,179.98,105.84,198.22,49.110,62.900,77.33,95.75,70.34,64.62,39.44,29.67,9.2235,161.55,38.375,18.078,25.93,9.934,56.94,33.220,52.08,38.82,63.24,28.255,295.45,63.56,161.00,179.90,225.95,75.10,65.32,44.23,41.17,92.86,343.25,113.52,16.495,55.54,102.80,144.46,33.34,34.67,NaN,NaN,NaN,NaN,NaN

In [17]:
ts_dax.describe()

,DE000A1EWWW0,NL0000235190,DE0008404005,DE000BASF111,DE000BAY0017,DE0005190003,DE0005200000,DE000A1DAHH0,DE0005439004,DE0006062144,DE000A2E4K43,DE0005140008,DE0005810055,DE0005552004,DE0005557508,DE000A0HN5C6,DE000ENAG999,DE0005785802,DE0005785604,DE0006047004,DE000A161408,DE0006048432,DE0006231004,IE00BZ12WP82,DE0007100000,DE0006599905,DE000A0D9PT0,DE0008430026,DE000PAH0038,DE0006969603,NL0012169213,DE0007037129,DE0007164600,DE0007165631,DE0007236101,DE000ENER6Y0,DE000SHL1006,DE000SYM9999,DE0007664039,DE000A1ML7J1,DE000ZAL1111,DE000CBK1001,DE000DTR0CK8,DE0008402215,DE000PAG9113,DE0007030009
count,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,270.000000,420.000000,420.000000,420.000000,420.000000,270.000000,377.000000,270.000000,420.000000,420.000000,270.000000,420.000000,420.000000,270.000000,420.000000,420.000000,420.000000,420.000000,420.000000,270.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,202.819893,111.250119,203.560881,54.899554,53.867494,85.912964,100.333131,72.854952,78.123857,45.297536,77.530852,10.609464,157.832917,45.463101,18.323795,38.493130,10.289019,58.693537,32.507500,59.587631,60.364056,70.239405,32.525494,278.076111,68.771631,183.798929,197.951786,265.284583,72.274381,89.003352,44.720107,37.306821,108.488500,433.158452,133.004857,19.602113,54.121369,109.534512,157.555631,37.693423,52.681381,9.194303,29.435867,178.235667,105.732267,213.407500
std,64.258004,7.840358,14.881181,8.553851,5.817246,8.637339,9.548929,7.898672,20.019281,8.586703,37.881604,1.254454,11.064370,8.602245,1.732700,11.105305,1.198747,6.213649,7.014773,8.591350,22.820859,8.081693,5.104276,16.427314,8.336314,16.688141,19.291435,37.047894,14.010225,17.008567,2.157480,3.603779,12.657374,85.737535,15.529399,3.720125,5.470981,9.864600,28.980736,13.637487,24.245436,1.218573,2.051151,11.318900,9.272726,38.837484
min,93.950000,87.900000,159.620000,38.760000,44.190000,69.130000,83.360000,55.700000,44.835000,28.815000,25.220000,7.583500,134.400000,30.465000,15.380000,20.860000,7.420000,35.650000,20.040000,39.590000,25.740000,57.540000,21.925000,244.750000,50.620000,146.500000,153.200000,213.700000,50.060000,60.560000,39.610000,29.060000,81.870000,301.750000,95.450000,10.340000,42.010000,93.120000,114.880000,15.655000,19.415000,7.158000,22.695000,152.150000,82.520000,146.100000
25%,146.565000,105.840000,197.300000,47.808750,48.694375,78.607500,93.150000,67.540000,64.210000,37.702500,38.735000,9.740000,147.156250,38.230000,16.962000,27.665000,9.522000,56.075000,26.597500,52.485000,37.662500,63.170000,28.225000,264.425000,63.120000,171.650000,183.850000,237.150000,57.415000,70.970000,43.185000,34.265000,97.652500,366.000000,120.465000,17.186250,49.872500,102.187500,130.867500,24.260000,32.877500,8.046500,28.690000,171.500000,99.487500,185.937500
50%,187.980000,112.500000,203.537500,52.430000,53.230000,83.840000,98.520000,73.220000,68.925000,42.725000,78.540000,10.768000,159.750000,41.960000,17.938000,36.830000,10.316000,59.410000,32.245000,60.650000,57.350000,68.340000,32.930000,279.650000,68.845000,181.400000,196.125000,252.050000,76.560000,94.360000,44.377500,38.135000,108.640000,403.750000,137.860000,19.437500,54.160000,107.350000,148.560000,35.967500,42.770000,9.400000,30.032500,181.812500,106.700000,213.575000
75%,260.925000,115.647500,215.925000,63.777500,57.900000,92.590000,106.200000,78.635000,94.773750,54.450000,114.950000,11.420000,165.725000,54.020000,19.304000,52.380000,11.111000,61.320000,37.195000,65.460000,82.342500,77.040000,35.976250,292.962500,74.000000,193.862500,210.375000,299.425000,84.675000,104.200000,46.437500,40.380000,120.840000,522.250000,144.945000,22.812500,57.915000,117.450000,186.595000,50.520000,75.680000,10.025000,30.874375,186.162500,113.925000,247.687500
max,336.250000,129.280000,231.950000,68.750000,67.570000,108.920000,127.450000,86.960000,127.900000,59.340000,132.100000,14.410000,186.300000,60.925000,23.045000,53.000000,12.364000,69.580000,47.380000,76.270000,94.760000,95.560000,43.195000,312.900000,91.175000,228.900000,243.000000,340.500000,94.400000,115.050000,50.280000,43.290000,128.980000,597.600000,157.960000,26.340000,67.180000,131.450000,226.150000,60.420000,102.950000,11.945000,32.897500,201.000000,120.300000,279.100000

In [14]:
oo = ts_dax.isnull().apply(lambda col : col.any())

DE000A1EWWW0    False
NL0000235190    False
DE0008404005    False
DE000BASF111    False
DE000BAY0017    False
DE0005190003    False
DE0005200000    False
DE000A1DAHH0    False
DE0005439004    False
DE0006062144    False
DE000A2E4K43    False
DE0005140008    False
DE0005810055    False
DE0005552004    False
DE0005557508    False
DE000A0HN5C6    False
DE000ENAG999     True
DE0005785802    False
DE0005785604    False
DE0006047004    False
DE000A161408    False
DE0006048432    False
DE0006231004    False
IE00BZ12WP82    False
DE0007100000    False
DE0006599905    False
DE000A0D9PT0    False
DE0008430026    False
DE000PAH0038    False
DE0006969603    False
NL0012169213    False
DE0007037129    False
DE0007164600    False
DE0007165631    False
DE0007236101    False
DE000ENER6Y0    False
DE000SHL1006    False
DE000SYM9999    False
DE0007664039    False
DE000A1ML7J1    False
DE000ZAL1111    False
dtype: bool

# TRAIN / EXPORT / LOAD MODELS dax_models.parquet

In [19]:
raw_file_path = Path("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\degiro\\degiro\\file\\raw\\")
index_id=6
stock_country_id=906

dax_anagrafica_test = pd.read_parquet(raw_file_path / f"{index_id}_{stock_country_id}_anagrafica.parquet", engine="fastparquet")
ts_dax = pd.read_parquet(raw_file_path / f"{index_id}_{stock_country_id}_ts.parquet", engine="fastparquet")

In [20]:
# MANCA '2021-10-09'
ts_dax.loc['2021-10-10']

,DE000A1EWWW0,NL0000235190,DE0008404005,DE000BASF111,DE000BAY0017,DE0005190003,DE0005200000,DE000A1DAHH0,DE0005439004,DE0006062144,DE000A2E4K43,DE0005140008,DE0005810055,DE0005552004,DE0005557508,DE000A0HN5C6,DE000ENAG999,DE0005785802,DE0005785604,DE0006047004,DE000A161408,DE0006048432,DE0006231004,IE00BZ12WP82,DE0007100000,DE0006599905,DE000A0D9PT0,DE0008430026,DE000PAH0038,DE0006969603,NL0012169213,DE0007037129,DE0007164600,DE0007165631,DE0007236101,DE000ENER6Y0,DE000SHL1006,DE000SYM9999,DE0007664039,DE000A1ML7J1,DE000ZAL1111,DE000CBK1001,DE000DTR0CK8,DE0008402215,DE000PAG9113,DE0007030009
DATE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2021-10-10,171.88,106.52,194.8,48.64,63.38,77.84,92.82,69.06,65.78,39.61,29.55,9.492,159.15,37.48,18.08,26.02,9.956,55.82,31.79,52.02,33.81,61.4,27.845,293.95,63.28,167.7,181.9,222.8,70.86,62.0,42.115,42.47,90.23,337.7,112.46,17.08,54.36,101.3,145.32,33.8,36.02,NaN,NaN,NaN,NaN,NaN

In [21]:
ts_dax[['DE000A1EWWW0', 'DE0008404005', 'DE000BASF111', 'DE000BAY0017']].iloc[-5:]

            DE000A1EWWW0  DE0008404005  DE000BASF111  DE000BAY0017
DATE
2023-01-23        121.86        164.94        41.325        47.845
2023-01-24        122.58        166.14        41.920        48.625
2023-01-25        126.20        167.20        42.300        48.715
2023-01-29        118.88        161.42        39.625        47.520
2023-01-30        124.02        159.62        38.760        47.625

## Load params

In [45]:
%%time
"""
Tests:
    1)
        4 x -> Wall time: 9min 32s

    2)
        6 x -> --- 00:10:50 ---> Total time (min) spent on 6 iterations
            Saving models...START
            Wall time: 21min 33s <- 4 models to save

    3)
        4 isin; --> export_models=False <-- ;epochs=3000;look_back=10;lstm_dim=40;dense_dim=10
            test 1 : --- 00:02:54 ---> Total time (min) spent on 1 iterations
            test 2 : --- 00:02:28 ---> Total time (min) spent on 1 iterations

    4)
        10 isin;export_models=False; -->  epochs=30000  <-- ; -->  look_back=100 <-- ; --> lstm_dim=400 <-- ; --> dense_dim=100 <--
            test 1 : 
            test 2 : 

"""
n_obs   = 252
to_test = ['DE000A1EWWW0', 'DE0008404005', 'DE000BASF111', 'DE000BAY0017']
# to_test = ts_dax.columns

model_param = {
    "chunks_num" : 2
}

model_param.update({
    "look_back" : 10,
    "epochs" : 5,
    "loss" : "mean_squared_error",
    "optimizer" : "adam",
    "lstm_dim" : 4,
    "dense_dim" : 1,
    "batch_size" : 1
})

grid_param = {
    "look_back" : [5],
    "epochs" : [
        10000, 5000
        ],
    "loss" : ["mean_squared_error"],
    "optimizer" : ["adam"],
    "lstm_dim" : [8],
    "dense_dim" : [32],
    "batch_size" : [150],
}

Wall time: 0 ns

In [49]:
"""
Ritorna (tra parentesi equivalente output da fct train_on_grid):
    df1 (grid_output_param) : 
        df index PARAM_HASH value parametrizzazione rete
    df2 (grid_output_stats) : 
        df index [PARAM_HASH, STAT] (STAT -> headers metodo pd.DataFrame.describe()) value pd.DataFrame.describe() output
    df3 (models_df) : 
        df no index (ISIN, PARAM_HASH da settare) con [ISIN, MODEL, MODEL_HASH, PARAM_HASH, statistiche performance model]
    df4 : 
        df no index (ISIN da settare) con miglior setting parametri e stat (merge df1 e df3)
"""
df1, df2, df3, df4 = train_on_grid_refactor(
    global_param=model_param, 
    grid_param=grid_param, 
    ts=ts_dax[to_test].iloc[-n_obs:], 
    export_models=True
    )

df1.shape, df2.shape, df3.shape, df4.shape

DEGIRO - train_on_grid_refactor - DEBUG - Total iterations...2
DEGIRO - train_on_grid_refactor - DEBUG - [{'batch_size': 150, 'dense_dim': 32, 'epochs': 10000, 'look_back': 5, 'loss': 'mean_squared_error', 'lstm_dim': 8, 'optimizer': 'adam'}, {'batch_size': 150, 'dense_dim': 32, 'epochs': 5000, 'look_back': 5, 'loss': 'mean_squared_error', 'lstm_dim': 8, 'optimizer': 'adam'}]
DEGIRO - train_on_grid_refactor - DEBUG - {'batch_size': 150, 'dense_dim': 32, 'epochs': 10000, 'look_back': 5, 'loss': 'mean_squared_error', 'lstm_dim': 8, 'optimizer': 'adam'}
DEGIRO - train_models_on_df_refactor - DEBUG - Param ID...a0b30aff28c5468c2f91e2a328f255ff
DEGIRO - train_models_on_df_refactor - DEBUG - Isin per chunk...2
DEGIRO - train_models_on_df_refactor - DEBUG - Start trainig chunk...1
DEGIRO - train_models_on_df_refactor - DEBUG - Done 1 -> 50.0%
DEGIRO - train_models_on_df_refactor - DEBUG - Start trainig chunk...2
DEGIRO - train_models_on_df_refactor - DEBUG - Done 2 -> 100.0%
DEGIRO - train_models_on_df_refactor - DEBUG - Getting stats...
DEGIRO - train_on_grid_refactor - DEBUG - Done 1 -> 50.0%
DEGIRO - train_on_grid_refactor - DEBUG - {'batch_size': 150, 'dense_dim': 32, 'epochs': 5000, 'look_back': 5, 'loss': 'mean_squared_error', 'lstm_dim': 8, 'optimizer': 'adam'}
DEGIRO - train_models_on_df_refactor - DEBUG - Param ID...8985324fa42104418279f22abd280ded
DEGIRO - train_models_on_df_refactor - DEBUG - Isin per chunk...2
DEGIRO - train_models_on_df_refactor - DEBUG - Start trainig chunk...1

--- 00:03:46 ---> Execution time (min) : last iteration
--- 00:03:46 ---> Average execution time (min) for 1 iterations
--- 00:03:46 ---> Remaining estimated time (min) for 1 iterations
--- 00:03:46 ---> Total time (min) spent on 1 iterations

DEGIRO - train_models_on_df_refactor - DEBUG - Done 1 -> 50.0%
DEGIRO - train_models_on_df_refactor - DEBUG - Start trainig chunk...2
DEGIRO - train_models_on_df_refactor - DEBUG - Done 2 -> 100.0%
DEGIRO - train_models_on_df_refactor - DEBUG - Getting stats...
DEGIRO - train_on_grid_refactor - DEBUG - Done 2 -> 100.0%
DEGIRO - train_on_grid_refactor - DEBUG - Saving models...START

--- 00:01:59 ---> Execution time (min) : last iteration
--- 00:02:53 ---> Average execution time (min) for 2 iterations
--- 00:00:00 ---> Remaining estimated time (min) for 0 iterations
--- 00:05:46 ---> Total time (min) spent on 2 iterations

DEGIRO - train_on_grid_refactor - DEBUG - Saving models...DONE

((2, 7), (16, 4), (8, 18), (4, 25))

In [50]:
ts_dax[to_test].DE000A1EWWW0.values[0]

180.48

In [51]:
import struct

b = bytes()
b = struct.pack('f', ts_dax[to_test].DE000A1EWWW0.values[0])
struct.unpack("f", b)

(180.47999572753906,)

In [52]:
struct.unpack("f", struct.pack("f", ts_dax[to_test].DE000A1EWWW0.values[0]))

(180.47999572753906,)

In [53]:
l = list()
ll = list()
l.extend(struct.pack('f', val) for val in ts_dax[to_test].DE000A1EWWW0.values)
ll.extend(round(struct.unpack("f", val)[0], 2) for val in l)

In [54]:
l[:10], ll[:10], ts_dax[to_test].DE000A1EWWW0.values[:10]

([b'\xe1z4C',
  b')\xdc5C',
  b')\\-C',
  b'\x14\xae-C',
  b'\xe1\xfa3C',
  b'\x9aYRC',
  b'3\xb3KC',
  b'f&RC',
  b'f&gC',
  b'\x00@rC'],
 [180.48,
  181.86,
  173.36,
  173.68,
  179.98,
  210.35,
  203.7,
  210.15,
  231.15,
  242.25],
 array([180.48, 181.86, 173.36, 173.68, 179.98, 210.35, 203.7 , 210.15,
        231.15, 242.25]))

In [55]:
for a in bytearray(ts_dax[to_test].DE000A1EWWW0.values[:10]):
    logger.debug(a)

DEGIRO - <module> - DEBUG - 143
DEGIRO - <module> - DEBUG - 194
DEGIRO - <module> - DEBUG - 245
DEGIRO - <module> - DEBUG - 40
DEGIRO - <module> - DEBUG - 92
DEGIRO - <module> - DEBUG - 143
DEGIRO - <module> - DEBUG - 102
DEGIRO - <module> - DEBUG - 64
DEGIRO - <module> - DEBUG - 236
DEGIRO - <module> - DEBUG - 81
DEGIRO - <module> - DEBUG - 184
DEGIRO - <module> - DEBUG - 30
DEGIRO - <module> - DEBUG - 133
DEGIRO - <module> - DEBUG - 187
DEGIRO - <module> - DEBUG - 102
DEGIRO - <module> - DEBUG - 64
DEGIRO - <module> - DEBUG - 236
DEGIRO - <module> - DEBUG - 81
DEGIRO - <module> - DEBUG - 184
DEGIRO - <module> - DEBUG - 30
DEGIRO - <module> - DEBUG - 133
DEGIRO - <module> - DEBUG - 171
DEGIRO - <module> - DEBUG - 101
DEGIRO - <module> - DEBUG - 64
DEGIRO - <module> - DEBUG - 246
DEGIRO - <module> - DEBUG - 40
DEGIRO - <module> - DEBUG - 92
DEGIRO - <module> - DEBUG - 143
DEGIRO - <module> - DEBUG - 194
DEGIRO - <module> - DEBUG - 181
DEGIRO - <module> - DEBUG - 101
DEGIRO - <module> - DEBUG - 64
DEGIRO - <module> - DEBUG - 143
DEGIRO - <module> - DEBUG - 194
DEGIRO - <module> - DEBUG - 245
DEGIRO - <module> - DEBUG - 40
DEGIRO - <module> - DEBUG - 92
DEGIRO - <module> - DEBUG - 127
DEGIRO - <module> - DEBUG - 102
DEGIRO - <module> - DEBUG - 64
DEGIRO - <module> - DEBUG - 51
DEGIRO - <module> - DEBUG - 51
DEGIRO - <module> - DEBUG - 51
DEGIRO - <module> - DEBUG - 51
DEGIRO - <module> - DEBUG - 51
DEGIRO - <module> - DEBUG - 75
DEGIRO - <module> - DEBUG - 106
DEGIRO - <module> - DEBUG - 64
DEGIRO - <module> - DEBUG - 102
DEGIRO - <module> - DEBUG - 102
DEGIRO - <module> - DEBUG - 102
DEGIRO - <module> - DEBUG - 102
DEGIRO - <module> - DEBUG - 102
DEGIRO - <module> - DEBUG - 118
DEGIRO - <module> - DEBUG - 105
DEGIRO - <module> - DEBUG - 64
DEGIRO - <module> - DEBUG - 205
DEGIRO - <module> - DEBUG - 204
DEGIRO - <module> - DEBUG - 204
DEGIRO - <module> - DEBUG - 204
DEGIRO - <module> - DEBUG - 204
DEGIRO - <module> - DEBUG - 68
DEGIRO - <module> - DEBUG - 106
DEGIRO - <module> - DEBUG - 64
DEGIRO - <module> - DEBUG - 205
DEGIRO - <module> - DEBUG - 204
DEGIRO - <module> - DEBUG - 204
DEGIRO - <module> - DEBUG - 204
DEGIRO - <module> - DEBUG - 204
DEGIRO - <module> - DEBUG - 228
DEGIRO - <module> - DEBUG - 108
DEGIRO - <module> - DEBUG - 64
DEGIRO - <module> - DEBUG - 0
DEGIRO - <module> - DEBUG - 0
DEGIRO - <module> - DEBUG - 0
DEGIRO - <module> - DEBUG - 0
DEGIRO - <module> - DEBUG - 0
DEGIRO - <module> - DEBUG - 72
DEGIRO - <module> - DEBUG - 110
DEGIRO - <module> - DEBUG - 64

## Inizio a capirci qualcosa, 

### pare che:

    2 funzioni, train_on_grid e train_on_grid_refactor, fanno entrambe (le strambe) fondamentalmente la stessa 
    
    cosa, runnare modelli sul dataframe in input, scrivono su disco i modelli (checkpoint? Restart?) e 
    
    restituiscono outputs.

    inputs:
        train_on_grid(
            global_param, 
            grid_param, 
            ts, 
            return_param_hash=True,         -> input di train_models_on_df, per farsi tornare lista contenete la variabile rnn_models["PARAM_HASH"] = param_hash
            return_stats=True               -> input di train_models_on_df, returns rnn_models[["TRAIN_LOSS", "TEST_LOSS", "VOL_IS", "VOL_OOS"]].describe()
            )
        
        train_on_grid_refactor(
            global_param: dict, 
            grid_param: dict, 
            ts: pd.DataFrame, 

            return_stats: bool=True,        -> inutilissimo orrido modo per farsi tornare come output it_stats_models, param_hash da train_models_on_df_refactor, conteneti le statistiche del chunk e il vettore con le param_hash. Tale vettore Ã¨ la colonna PARAM_HASH del dataframe it_stats_models. Dio cane
            
            save: bool=False,               -> input di train_models_on_df_refactor dio cane
                nda: 
                    # Giro con save e return_stats defaultati a False e True -> traduzione :  train_models_on_df_refactor non scrive nulla : ovvero, save salva i modelli del chuck in pasto a train_models_on_df_refactor. Le seguenti due righe non sono eseguite.
                        raw_file_path / "models_{}.parquet".format(param_hash)
                        rnn_save(x.MODEL, path=_MODEL_PATH_ / "{}".format(x.MODEL_HASH)

            export_models: bool=False       -> rnn_save(x.MODEL, path=_MODEL_PATH_ / "{}".format(x.MODEL_HASH)), axis=1
                nda:
                    satanicamente defaultato a False, ma passato ovunque a True.
                    esegue il metodo rnn_save(x.MODEL, path=_MODEL_PATH_ / "{}".format(x.MODEL_HASH) all interno di un apply
            )

    Outputs:
        train_on_grid
            param_df: pd.DataFrame 
                index : [PARAM_HASH]
                columns : [batch_size, dense_dim, epochs, look_back, loss, lstm_dim, optimizer,chunks_num]

            stats_df: pd.DataFrame
                index : [PARAM_HASH, STAT]
                columns : [TRAIN_LOSS	TEST_LOSS	VOL_IS	VOL_OOS]
        
        train_on_grid_refactor
            param_df: pd.DataFrame 
                index : [PARAM_HASH]
                columns : [batch_size, dense_dim, epochs, look_back, loss, lstm_dim, optimizer,chunks_num]

            stats_df: pd.DataFrame
                index : [PARAM_HASH, STAT]
                columns : [TRAIN_LOSS	TEST_LOSS	VOL_IS	VOL_OOS]

            stats_models_df: pd.DataFrame
                index: []
                columns: [ISIN	MODEL	SCALER_MIN	SCALER_MAX	TRAIN_LOSS	TEST_LOSS	VOL_IS	VOL_OOS	MODEL_HASH	TIMESTAMP	AVERAGE_PRICE	LOOK_BACK	LAST_PRICE	TRAIN_LOSS_PERC	TEST_LOSS_PERC	VOL_IS_PERC	VOL_OOS_PERC	PARAM_HASH]
            
            best_models_df: pd.DataFrame
                query eseguita
                    stats_models_df.loc[
                        stats_models_df.groupby("ISIN")[_BEST_CHOICE_CRITERIA_].idxmin()
                        ].sort_values("PARAM_HASH").merge(
                            param_df, 
                            left_on="PARAM_HASH", 
                            right_index=True
                            )
                    _BEST_CHOICE_CRITERIA_ : variabile brutalmente hardcodata
                index: []
                columns: ['ISIN', 'MODEL', 'SCALER_MIN', 'SCALER_MAX', 'TRAIN_LOSS', 'TEST_LOSS','VOL_IS', 'VOL_OOS', 'MODEL_HASH', 'TIMESTAMP', 'AVERAGE_PRICE', 'LOOK_BACK', 'LAST_PRICE', 'TRAIN_LOSS_PERC', 'TEST_LOSS_PERC', 'VOL_IS_PERC', 'VOL_OOS_PERC', 'PARAM_HASH', 'batch_size', 'dense_dim', 'epochs', 'look_back', 'loss', 'lstm_dim', 'optimizer', 'chunks_num']

    Commenti a caldo:
        input:
            train_on_grid
                perchÃ¨ 2 param?
                perchÃ¨ 2 varibili (return_param_hash), return_stats defaultizzate a True? Rimuovere?

        output:
            train_on_grid -> param_df = train_on_grid_refactor -> param_df
            train_on_grid -> stats_df = train_on_grid_refactor -> stats_df
            train_on_grid_refactor -> stats_models_df 
                nda: 
                 pare vero che: 
                    df_3_ref.set_index(["PARAM_HASH", "ISIN"]).drop(columns=["MODEL"])
                    ==
                    output di resume_models_df(param_df, _MODEL_STATS_PATH_)
                sia Vero
            train_on_grid_refactor -> best_models_df 
                nda:
                    merge tra param_df e stats_models_df su PARAM_HASH
        
        file:
            train_on_grid 


        Dove cazzo sono i modelli
            df_3_ref e df_4_ref, colonna MODEL
            scritti in _MODEL_PATH_ : "C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\laboratorio\\file\\processed\\parquet\\"

train_models_on_df(
    ts : pd.DataFrame, 
    model_param: dict, 
    return_param_hash=False, 
    return_stats=False
    )

train_models_on_df_refactor(
    ts: pd.DataFrame, 
    model_param: dict, 
    return_stats: bool=True, 
    save: bool=False
    )

### Stessi hyperparam per tutto il set di isin

    PRO : 
        stesso look_back cross isin -> serie storiche pari

    CONTRO:
        un grado di liberta in meno - meno accurato

In [6]:
raw_file_path = Path("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\degiro\\degiro\\file\\raw\\")
index_id=6
stock_country_id=906

ts_dax = pd.read_parquet(raw_file_path / f"{index_id}_{stock_country_id}_ts.parquet", engine="fastparquet")

n_obs   = 252
to_test = ['DE000A1EWWW0', 'DE0008404005', 'DE000BASF111', 'DE000BAY0017']
# to_test = ts_dax.columns

model_param = {
    "chunks_num" : 2
}

model_param.update({
    "look_back" : 10,
    "epochs" : 5,
    "loss" : "mean_squared_error",
    "optimizer" : "adam",
    "lstm_dim" : 4,
    "dense_dim" : 1,
    "batch_size" : 1
})

grid_param = {
    "look_back" : [5],
    "epochs" : [
        10000
        ],
    "loss" : ["mean_squared_error"],
    "optimizer" : ["adam"],
    "lstm_dim" : [8],
    "dense_dim" : [32],
    "batch_size" : [150],
}

_BEST_ = "TEST_LOSS"

In [58]:
df1.reset_index().to_parquet(_MODEL_STATS_PATH_ / "df_1_ref.parquet", engine="fastparquet")
df2.reset_index().to_parquet(_MODEL_STATS_PATH_ / "df_2_ref.parquet", engine="fastparquet")
df3.drop(columns=["MODEL"]).to_parquet(_MODEL_STATS_PATH_ / "df_3_ref.parquet", engine="fastparquet")
df4.drop(columns=["MODEL"]).to_parquet(_MODEL_STATS_PATH_ / "df_4_ref.parquet", engine="fastparquet")

In [4]:
df_1_ref = pd.read_parquet(_MODEL_STATS_PATH_ / "df_1_ref.parquet", engine="fastparquet")
df_1_ref.set_index("PARAM_HASH", inplace=True)
df_2_ref = pd.read_parquet(_MODEL_STATS_PATH_ / "df_2_ref.parquet", engine="fastparquet")

In [8]:
ordered_best = df_2_ref[df_2_ref.STAT=="mean"][[_BEST_, "PARAM_HASH"]].sort_values(_BEST_, ascending=True).PARAM_HASH
df_1_ref.reindex(ordered_best)

,batch_size,dense_dim,epochs,look_back,loss,lstm_dim,optimizer
PARAM_HASH,,,,,,,
8985324fa42104418279f22abd280ded,150,32,5000,5,mean_squared_error,8,adam
a0b30aff28c5468c2f91e2a328f255ff,150,32,10000,5,mean_squared_error,8,adam

In [10]:
df_2_ref[df_2_ref.STAT=="mean"][[_BEST_, "PARAM_HASH"]].sort_values(_BEST_, ascending=True)

   TEST_LOSS                        PARAM_HASH
9   2.500215  8985324fa42104418279f22abd280ded
1   2.935839  a0b30aff28c5468c2f91e2a328f255ff

## samples.parquet

## ground_truth.parquet

## ground_prediction.parquet

In [61]:
%load_ext autoreload
%autoreload 2
%aimport src_config

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
from degiro.degiroUtils import rnn_load, rnn_predict_dataset
import copy

look_back = 5
ts_to_test = copy.deepcopy(ts_dax[to_test])

In [8]:
ts_to_test.iloc[-n_obs:]

            DE000A1EWWW0  DE0008404005  DE000BASF111  DE000BAY0017
DATE
2021-08-05        171.00        179.18        43.935        58.680
2021-08-07        171.34        178.28        43.440        56.730
2021-08-10        167.80        177.32        43.445        57.090
2021-08-11        166.34        173.38        42.520        57.080
2021-08-18        175.08        173.82        43.615        57.230
...                  ...           ...           ...           ...
2023-01-23        121.86        164.94        41.325        47.845
2023-01-24        122.58        166.14        41.920        48.625
2023-01-25        126.20        167.20        42.300        48.715
2023-01-29        118.88        161.42        39.625        47.520
2023-01-30        124.02        159.62        38.760        47.625

[252 rows x 4 columns]

In [9]:
df_4_ref = pd.read_parquet(path=_MODEL_STATS_PATH_ / "df_4_ref.parquet", engine="fastparquet").set_index("ISIN")
df_4_ref["MODEL"] = df_4_ref.apply(lambda x: rnn_load(path=_MODEL_PATH_ / x.MODEL_HASH), axis=1)
df_4_ref.head()

,SCALER_MIN,SCALER_MAX,TRAIN_LOSS,TEST_LOSS,VOL_IS,VOL_OOS,MODEL_HASH,TIMESTAMP,AVERAGE_PRICE,LOOK_BACK,...,VOL_OOS_PERC,PARAM_HASH,batch_size,dense_dim,epochs,look_back,loss,lstm_dim,optimizer,MODEL
ISIN,,,,,,,,,,,,,,,,,,,,,
DE0008404005,159.62,231.95,4.220403,3.151327,4.219984,2.360025,ad79af16fa4a35bc9f40e64720a5b921,1.685540e+09,203.482004,5,...,0.011598,8985324fa42104418279f22abd280ded,150,32,5000,5,mean_squared_error,8,adam,<keras.engine.sequential.Sequential object at ...
DE000A1EWWW0,93.95,316.00,13.466767,5.102551,13.466761,4.555416,55310890d0ce5bbc0f7bd0dd6e08c123,1.685540e+09,173.372004,5,...,0.026275,8985324fa42104418279f22abd280ded,150,32,5000,5,mean_squared_error,8,adam,<keras.engine.sequential.Sequential object at ...
DE000BASF111,38.76,68.64,2.257235,0.894146,2.203925,0.892919,de3d8542b533fddafd96e191b4d68491,1.685540e+09,51.710764,5,...,0.017268,8985324fa42104418279f22abd280ded,150,32,5000,5,mean_squared_error,8,adam,<keras.engine.sequential.Sequential object at ...
DE000BAY0017,44.57,67.42,1.382214,0.852835,1.381831,0.852752,bc27d82eb8f394240da95cc302dd95cf,1.685540e+09,54.552589,5,...,0.015632,8985324fa42104418279f22abd280ded,150,32,5000,5,mean_squared_error,8,adam,<keras.engine.sequential.Sequential object at ...

In [10]:
df_3_ref = pd.read_parquet(path=_MODEL_STATS_PATH_ / "df_3_ref.parquet", engine="fastparquet").set_index("ISIN")
df_3_ref["MODEL"] = df_3_ref.apply(lambda x: rnn_load(path=_MODEL_PATH_ / x.MODEL_HASH), axis=1)
df_3_ref.head()

,SCALER_MIN,SCALER_MAX,TRAIN_LOSS,TEST_LOSS,VOL_IS,VOL_OOS,MODEL_HASH,TIMESTAMP,AVERAGE_PRICE,LOOK_BACK,LAST_PRICE,TRAIN_LOSS_PERC,TEST_LOSS_PERC,VOL_IS_PERC,VOL_OOS_PERC,PARAM_HASH,MODEL
ISIN,,,,,,,,,,,,,,,,,
DE000A1EWWW0,93.95,316.00,13.312616,6.380830,13.273747,4.959042,677e419151ac0856b54850e3ddf79479,1.685540e+09,173.372004,5,124.020,0.076786,0.036804,0.076562,0.028603,a0b30aff28c5468c2f91e2a328f255ff,<keras.engine.sequential.Sequential object at ...
DE0008404005,159.62,231.95,4.165190,3.501867,4.155565,2.503167,406adba7eb5bca863f8be974244041bc,1.685540e+09,203.482004,5,159.620,0.020470,0.017210,0.020422,0.012302,a0b30aff28c5468c2f91e2a328f255ff,<keras.engine.sequential.Sequential object at ...
DE000BASF111,38.76,68.64,2.217020,0.958115,2.197068,0.943279,d74e3610b0576abd60853c774927588b,1.685540e+09,51.710764,5,38.760,0.042873,0.018528,0.042488,0.018241,a0b30aff28c5468c2f91e2a328f255ff,<keras.engine.sequential.Sequential object at ...
DE000BAY0017,44.57,67.42,1.392718,0.902543,1.373615,0.890172,19587c7f8a1270b237e3cb0659b7d6bc,1.685540e+09,54.552589,5,47.625,0.025530,0.016544,0.025180,0.016318,a0b30aff28c5468c2f91e2a328f255ff,<keras.engine.sequential.Sequential object at ...
DE000A1EWWW0,93.95,316.00,13.466767,5.102551,13.466761,4.555416,55310890d0ce5bbc0f7bd0dd6e08c123,1.685540e+09,173.372004,5,124.020,0.077676,0.029431,0.077676,0.026275,8985324fa42104418279f22abd280ded,<keras.engine.sequential.Sequential object at ...

In [11]:
ts_dax.loc['2021-10-09']
ts_to_test.iloc[-n_obs:].shape

(252, 4)

In [12]:
%%time
df_3_ref[["PREDICTED_Y", "TEST_Y"]] = df_3_ref.apply(lambda x: rnn_predict_dataset(
    model=x.MODEL, 
    scaler_min=x.SCALER_MIN, 
    scaler_max=x.SCALER_MAX, 
    dataset=ts_to_test[x.name][int(ts_to_test.iloc[-n_obs:].shape[0]*0.67):], 
    in_sample_perc=0, 
    look_back=look_back
    ), 
    result_type="expand", axis=1)

Wall time: 2.88 s

In [15]:
last_date

Timestamp('2023-01-25 00:00:00')

In [14]:
#df_4_ref
#ts_to_test.iloc[-n_obs:]

sample_col = [f"SAMPLE_{sample}" for sample in range(ts_to_test.iloc[-n_obs:].shape[0]-look_back)]
date_col = [(ts_to_test.iloc[-n_obs:].index[positional:(positional+look_back)]) for positional, date in enumerate(ts_to_test.iloc[-n_obs:].index[:-look_back])]

columns = []
for c, sample in enumerate(sample_col):
    for obs_date in date_col[c]:
        columns.append((sample, obs_date))

ss = pd.DataFrame(index=ts_to_test.iloc[-n_obs:].columns, columns=pd.MultiIndex.from_tuples(columns))
last_date = ss.columns.get_level_values(level=1)[-2]

In [80]:
date_col = [(ts_to_test.iloc[-n_obs:].index[positional:(positional+look_back)]) for positional, date in enumerate(ts_to_test.iloc[-n_obs:].index[:-look_back])]
date_col

[DatetimeIndex(['2021-08-05', '2021-08-07', '2021-08-10', '2021-08-11',
                '2021-08-18'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-07', '2021-08-10', '2021-08-11', '2021-08-18',
                '2021-08-20'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-10', '2021-08-11', '2021-08-18', '2021-08-20',
                '2021-08-24'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-11', '2021-08-18', '2021-08-20', '2021-08-24',
                '2021-08-25'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-18', '2021-08-20', '2021-08-24', '2021-08-25',
                '2021-08-26'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-20', '2021-08-24', '2021-08-25', '2021-08-26',
                '2021-08-28'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-24', '2021-08-25', '2021-08-26', '2021-08-28',
                '2021-08-31'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-25', '2021-08-26', '2021-08-28', '2021-08-31',
                '2021-09-07'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-26', '2021-08-28', '2021-08-31', '2021-09-07',
                '2021-09-10'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-28', '2021-08-31', '2021-09-07', '2021-09-10',
                '2021-09-11'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-08-31', '2021-09-07', '2021-09-10', '2021-09-11',
                '2021-09-17'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-09-07', '2021-09-10', '2021-09-11', '2021-09-17',
                '2021-09-22'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-09-10', '2021-09-11', '2021-09-17', '2021-09-22',
                '2021-09-23'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-09-11', '2021-09-17', '2021-09-22', '2021-09-23',
                '2021-09-25'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-09-17', '2021-09-22', '2021-09-23', '2021-09-25',
                '2021-10-01'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-09-22', '2021-09-23', '2021-09-25', '2021-10-01',
                '2021-10-02'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-09-23', '2021-09-25', '2021-10-01', '2021-10-02',
                '2021-10-06'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-09-25', '2021-10-01', '2021-10-02', '2021-10-06',
                '2021-10-07'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-01', '2021-10-02', '2021-10-06', '2021-10-07',
                '2021-10-13'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-02', '2021-10-06', '2021-10-07', '2021-10-13',
                '2021-10-15'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-06', '2021-10-07', '2021-10-13', '2021-10-15',
                '2021-10-16'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-07', '2021-10-13', '2021-10-15', '2021-10-16',
                '2021-10-20'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-13', '2021-10-15', '2021-10-16', '2021-10-20',
                '2021-10-21'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-15', '2021-10-16', '2021-10-20', '2021-10-21',
                '2021-10-26'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-16', '2021-10-20', '2021-10-21', '2021-10-26',
                '2021-10-28'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-20', '2021-10-21', '2021-10-26', '2021-10-28',
                '2021-11-03'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-21', '2021-10-26', '2021-10-28', '2021-11-03',
                '2021-11-05'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-26', '2021-10-28', '2021-11-03', '2021-11-05',
                '2021-11-06'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-10-28', '2021-11-03', '2021-11-05', '2021-11-06',
                '2021-11-10'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-03', '2021-11-05', '2021-11-06', '2021-11-10',
                '2021-11-11'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-05', '2021-11-06', '2021-11-10', '2021-11-11',
                '2021-11-13'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-06', '2021-11-10', '2021-11-11', '2021-11-13',
                '2021-11-16'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-10', '2021-11-11', '2021-11-13', '2021-11-16',
                '2021-11-18'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-11', '2021-11-13', '2021-11-16', '2021-11-18',
                '2021-11-19'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-13', '2021-11-16', '2021-11-18', '2021-11-19',
                '2021-11-25'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-16', '2021-11-18', '2021-11-19', '2021-11-25',
                '2021-11-30'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-18', '2021-11-19', '2021-11-25', '2021-11-30',
                '2021-12-08'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-19', '2021-11-25', '2021-11-30', '2021-12-08',
                '2021-12-10'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-25', '2021-11-30', '2021-12-08', '2021-12-10',
                '2021-12-11'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-11-30', '2021-12-08', '2021-12-10', '2021-12-11',
                '2021-12-15'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-12-08', '2021-12-10', '2021-12-11', '2021-12-15',
                '2021-12-21'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-12-10', '2021-12-11', '2021-12-15', '2021-12-21',
                '2021-12-22'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-12-11', '2021-12-15', '2021-12-21', '2021-12-22',
                '2021-12-29'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-12-15', '2021-12-21', '2021-12-22', '2021-12-29',
                '2022-01-04'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-12-21', '2021-12-22', '2021-12-29', '2022-01-04',
                '2022-01-06'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-12-22', '2021-12-29', '2022-01-04', '2022-01-06',
                '2022-01-18'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2021-12-29', '2022-01-04', '2022-01-06', '2022-01-18',
                '2022-01-19'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-01-04', '2022-01-06', '2022-01-18', '2022-01-19',
                '2022-01-20'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-01-06', '2022-01-18', '2022-01-19', '2022-01-20',
                '2022-01-27'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-01-18', '2022-01-19', '2022-01-20', '2022-01-27',
                '2022-01-28'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-01-19', '2022-01-20', '2022-01-27', '2022-01-28',
                '2022-01-29'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-01-20', '2022-01-27', '2022-01-28', '2022-01-29',
                '2022-02-01'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-01-27', '2022-01-28', '2022-01-29', '2022-02-01',
                '2022-02-04'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-01-28', '2022-01-29', '2022-02-01', '2022-02-04',
                '2022-02-09'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-01-29', '2022-02-01', '2022-02-04', '2022-02-09',
                '2022-02-11'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-02-01', '2022-02-04', '2022-02-09', '2022-02-11',
                '2022-02-18'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-02-04', '2022-02-09', '2022-02-11', '2022-02-18',
                '2022-02-23'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-02-09', '2022-02-11', '2022-02-18', '2022-02-23',
                '2022-02-24'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-02-11', '2022-02-18', '2022-02-23', '2022-02-24',
                '2022-03-02'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-02-18', '2022-02-23', '2022-02-24', '2022-03-02',
                '2022-03-09'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-02-23', '2022-02-24', '2022-03-02', '2022-03-09',
                '2022-03-10'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-02-24', '2022-03-02', '2022-03-09', '2022-03-10',
                '2022-03-16'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-03-02', '2022-03-09', '2022-03-10', '2022-03-16',
                '2022-03-18'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-03-09', '2022-03-10', '2022-03-16', '2022-03-18',
                '2022-03-23'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-03-10', '2022-03-16', '2022-03-18', '2022-03-23',
                '2022-03-29'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-03-16', '2022-03-18', '2022-03-23', '2022-03-29',
                '2022-04-01'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-03-18', '2022-03-23', '2022-03-29', '2022-04-01',
                '2022-04-02'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-03-23', '2022-03-29', '2022-04-01', '2022-04-02',
                '2022-04-06'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-03-29', '2022-04-01', '2022-04-02', '2022-04-06',
                '2022-04-09'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-04-01', '2022-04-02', '2022-04-06', '2022-04-09',
                '2022-04-15'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-04-02', '2022-04-06', '2022-04-09', '2022-04-15',
                '2022-04-16'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-04-06', '2022-04-09', '2022-04-15', '2022-04-16',
                '2022-04-22'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-04-09', '2022-04-15', '2022-04-16', '2022-04-22',
                '2022-04-26'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-04-15', '2022-04-16', '2022-04-22', '2022-04-26',
                '2022-04-29'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-04-16', '2022-04-22', '2022-04-26', '2022-04-29',
                '2022-05-03'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-04-22', '2022-04-26', '2022-04-29', '2022-05-03',
                '2022-05-07'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-04-26', '2022-04-29', '2022-05-03', '2022-05-07',
                '2022-05-11'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-04-29', '2022-05-03', '2022-05-07', '2022-05-11',
                '2022-05-13'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-05-03', '2022-05-07', '2022-05-11', '2022-05-13',
                '2022-05-19'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-05-07', '2022-05-11', '2022-05-13', '2022-05-19',
                '2022-05-24'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-05-11', '2022-05-13', '2022-05-19', '2022-05-24',
                '2022-05-28'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-05-13', '2022-05-19', '2022-05-24', '2022-05-28',
                '2022-06-01'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-05-19', '2022-05-24', '2022-05-28', '2022-06-01',
                '2022-06-02'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-05-24', '2022-05-28', '2022-06-01', '2022-06-02',
                '2022-06-03'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-05-28', '2022-06-01', '2022-06-02', '2022-06-03',
                '2022-06-10'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-01', '2022-06-02', '2022-06-03', '2022-06-10',
                '2022-06-15'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-02', '2022-06-03', '2022-06-10', '2022-06-15',
                '2022-06-18'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-03', '2022-06-10', '2022-06-15', '2022-06-18',
                '2022-06-22'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-10', '2022-06-15', '2022-06-18', '2022-06-22',
                '2022-06-24'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-15', '2022-06-18', '2022-06-22', '2022-06-24',
                '2022-06-29'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-18', '2022-06-22', '2022-06-24', '2022-06-29',
                '2022-07-02'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-22', '2022-06-24', '2022-06-29', '2022-07-02',
                '2022-07-09'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-24', '2022-06-29', '2022-07-02', '2022-07-09',
                '2022-07-15'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-29', '2022-07-02', '2022-07-09', '2022-07-15',
                '2022-07-20'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-02', '2022-07-09', '2022-07-15', '2022-07-20',
                '2022-07-21'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-09', '2022-07-15', '2022-07-20', '2022-07-21',
                '2022-07-23'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-15', '2022-07-20', '2022-07-21', '2022-07-23',
                '2022-07-28'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-20', '2022-07-21', '2022-07-23', '2022-07-28',
                '2022-08-03'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-21', '2022-07-23', '2022-07-28', '2022-08-03',
                '2022-06-01'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-23', '2022-07-28', '2022-08-03', '2022-06-01',
                '2022-06-02'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-28', '2022-08-03', '2022-06-01', '2022-06-02',
                '2022-06-05'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-08-03', '2022-06-01', '2022-06-02', '2022-06-05',
                '2022-06-07'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-01', '2022-06-02', '2022-06-05', '2022-06-07',
                '2022-06-09'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-02', '2022-06-05', '2022-06-07', '2022-06-09',
                '2022-06-13'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-05', '2022-06-07', '2022-06-09', '2022-06-13',
                '2022-06-14'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-07', '2022-06-09', '2022-06-13', '2022-06-14',
                '2022-06-20'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-09', '2022-06-13', '2022-06-14', '2022-06-20',
                '2022-06-22'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-13', '2022-06-14', '2022-06-20', '2022-06-22',
                '2022-06-23'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-14', '2022-06-20', '2022-06-22', '2022-06-23',
                '2022-06-26'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-20', '2022-06-22', '2022-06-23', '2022-06-26',
                '2022-06-27'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-22', '2022-06-23', '2022-06-26', '2022-06-27',
                '2022-07-03'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-23', '2022-06-26', '2022-06-27', '2022-07-03',
                '2022-07-06'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-26', '2022-06-27', '2022-07-03', '2022-07-06',
                '2022-07-07'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-06-27', '2022-07-03', '2022-07-06', '2022-07-07',
                '2022-07-11'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-03', '2022-07-06', '2022-07-07', '2022-07-11',
                '2022-07-13'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-06', '2022-07-07', '2022-07-11', '2022-07-13',
                '2022-07-14'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-07', '2022-07-11', '2022-07-13', '2022-07-14',
                '2022-07-19'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-11', '2022-07-13', '2022-07-14', '2022-07-19',
                '2022-07-25'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-13', '2022-07-14', '2022-07-19', '2022-07-25',
                '2022-07-26'],
               dtype='datetime64[ns]', name='DATE', freq=None),
 DatetimeIndex(['2022-07-14', '2022-07-19', '2022-07-25', '2022-07-26',
                '2022-07-27'],

In [77]:
# ts_to_test.iloc[-n_obs:].index[0:(0+look_back)]
# ts_to_test.iloc[-n_obs:].loc[['2021-10-01', '2021-10-03', '2021-10-07', '2021-10-08',
#               '2021-10-09']].T
ss.head()

               SAMPLE_0                                              \
             2021-08-05 2021-08-07 2021-08-10 2021-08-11 2021-08-18
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

               SAMPLE_1                                              \
             2021-08-07 2021-08-10 2021-08-11 2021-08-18 2021-08-20
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

               SAMPLE_2                                              \
             2021-08-10 2021-08-11 2021-08-18 2021-08-20 2021-08-24
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

               SAMPLE_3                                              \
             2021-08-11 2021-08-18 2021-08-20 2021-08-24 2021-08-25
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

               SAMPLE_4                                              \
             2021-08-18 2021-08-20 2021-08-24 2021-08-25 2021-08-26
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

               SAMPLE_5                                              \
             2021-08-20 2021-08-24 2021-08-25 2021-08-26 2021-08-28
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

               SAMPLE_6                                              \
             2021-08-24 2021-08-25 2021-08-26 2021-08-28 2021-08-31
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

               SAMPLE_7                                              \
             2021-08-25 2021-08-26 2021-08-28 2021-08-31 2021-09-07
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

               SAMPLE_8                                              \
             2021-08-26 2021-08-28 2021-08-31 2021-09-07 2021-09-10
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

               SAMPLE_9                                              \
             2021-08-28 2021-08-31 2021-09-07 2021-09-10 2021-09-11
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_10                                              \
             2021-08-31 2021-09-07 2021-09-10 2021-09-11 2021-09-17
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_11                                              \
             2021-09-07 2021-09-10 2021-09-11 2021-09-17 2021-09-22
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_12                                              \
             2021-09-10 2021-09-11 2021-09-17 2021-09-22 2021-09-23
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_13                                              \
             2021-09-11 2021-09-17 2021-09-22 2021-09-23 2021-09-25
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_14                                              \
             2021-09-17 2021-09-22 2021-09-23 2021-09-25 2021-10-01
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_15                                              \
             2021-09-22 2021-09-23 2021-09-25 2021-10-01 2021-10-02
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_16                                              \
             2021-09-23 2021-09-25 2021-10-01 2021-10-02 2021-10-06
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_17                                              \
             2021-09-25 2021-10-01 2021-10-02 2021-10-06 2021-10-07
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_18                                              \
             2021-10-01 2021-10-02 2021-10-06 2021-10-07 2021-10-13
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

              SAMPLE_19                                              ...  \
             2021-10-02 2021-10-06 2021-10-07 2021-10-13 2021-10-15  ...
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN  ...
DE0008404005        NaN        NaN        NaN        NaN        NaN  ...
DE000BASF111        NaN        NaN        NaN        NaN        NaN  ...
DE000BAY0017        NaN        NaN        NaN        NaN        NaN  ...

             SAMPLE_227                                              \
             2022-12-26 2022-12-27 2022-12-28 2022-12-29 2023-01-01
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_228                                              \
             2022-12-27 2022-12-28 2022-12-29 2023-01-01 2023-01-02
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_229                                              \
             2022-12-28 2022-12-29 2023-01-01 2023-01-02 2023-01-03
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_230                                              \
             2022-12-29 2023-01-01 2023-01-02 2023-01-03 2023-01-04
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_231                                              \
             2023-01-01 2023-01-02 2023-01-03 2023-01-04 2023-01-05
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_232                                              \
             2023-01-02 2023-01-03 2023-01-04 2023-01-05 2023-01-08
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_233                                              \
             2023-01-03 2023-01-04 2023-01-05 2023-01-08 2023-01-09
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_234                                              \
             2023-01-04 2023-01-05 2023-01-08 2023-01-09 2023-01-10
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_235                                              \
             2023-01-05 2023-01-08 2023-01-09 2023-01-10 2023-01-11
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_236                                              \
             2023-01-08 2023-01-09 2023-01-10 2023-01-11 2023-01-12
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_237                                              \
             2023-01-09 2023-01-10 2023-01-11 2023-01-12 2023-01-15
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_238                                              \
             2023-01-10 2023-01-11 2023-01-12 2023-01-15 2023-01-16
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_239                                              \
             2023-01-11 2023-01-12 2023-01-15 2023-01-16 2023-01-17
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_240                                              \
             2023-01-12 2023-01-15 2023-01-16 2023-01-17 2023-01-18
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_241                                              \
             2023-01-15 2023-01-16 2023-01-17 2023-01-18 2023-01-19
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_242                                              \
             2023-01-16 2023-01-17 2023-01-18 2023-01-19 2023-01-22
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_243                                              \
             2023-01-17 2023-01-18 2023-01-19 2023-01-22 2023-01-23
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_244                                              \
             2023-01-18 2023-01-19 2023-01-22 2023-01-23 2023-01-24
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_245                                              \
             2023-01-19 2023-01-22 2023-01-23 2023-01-24 2023-01-25
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

             SAMPLE_246
             2023-01-22 2023-01-23 2023-01-24 2023-01-25 2023-01-29
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

[4 rows x 1235 columns]

In [72]:
for i, obs_date in enumerate(ts_to_test.iloc[-n_obs:].index[:len(date_col)]):
    print(obs_date, last_date)
    if obs_date >= last_date:
        break
    else:
        print(obs_date)
        date_window = ts_to_test.iloc[-n_obs:].index[i:(i+look_back)]
        cols = ss.columns[ss.columns.get_level_values(level=0)==f"SAMPLE_{i}"]
        print(ts_to_test.iloc[-n_obs:].loc[date_window].T.shape)
        print(ts_to_test.iloc[-n_obs:].loc[date_window].T)
        print(cols)
        ss[cols] = ts_to_test.iloc[-n_obs:].loc[date_window].T.astype(np.float)

2021-08-05 00:00:00 2023-01-25 00:00:00
2021-08-05 00:00:00
(4, 5)
DATE          2021-08-05  2021-08-07  2021-08-10  2021-08-11  2021-08-18
DE000A1EWWW0     171.000      171.34     167.800      166.34     175.080
DE0008404005     179.180      178.28     177.320      173.38     173.820
DE000BASF111      43.935       43.44      43.445       42.52      43.615
DE000BAY0017      58.680       56.73      57.090       57.08      57.230
MultiIndex([('SAMPLE_0', '2021-08-05'),
            ('SAMPLE_0', '2021-08-07'),
            ('SAMPLE_0', '2021-08-10'),
            ('SAMPLE_0', '2021-08-11'),
            ('SAMPLE_0', '2021-08-18')],
           )
2021-08-07 00:00:00 2023-01-25 00:00:00
2021-08-07 00:00:00
(4, 5)
DATE          2021-08-07  2021-08-10  2021-08-11  2021-08-18  2021-08-20
DE000A1EWWW0      171.34     167.800      166.34     175.080      175.92
DE0008404005      178.28     177.320      173.38     173.820      176.02
DE000BASF111       43.44      43.445       42.52      43.615       44.72
DE000BAY0017       56.73      57.090       57.08      57.230       57.93
MultiIndex([('SAMPLE_1', '2021-08-07'),
            ('SAMPLE_1', '2021-08-10'),
            ('SAMPLE_1', '2021-08-11'),
            ('SAMPLE_1', '2021-08-18'),
            ('SAMPLE_1', '2021-08-20')],
           )
2021-08-10 00:00:00 2023-01-25 00:00:00
2021-08-10 00:00:00
(4, 5)
DATE          2021-08-10  2021-08-11  2021-08-18  2021-08-20  2021-08-24
DE000A1EWWW0     167.800      166.34     175.080      175.92     160.960
DE0008404005     177.320      173.38     173.820      176.02     173.000
DE000BASF111      43.445       42.52      43.615       44.72      41.495
DE000BAY0017      57.090       57.08      57.230       57.93      55.640
MultiIndex([('SAMPLE_2', '2021-08-10'),
            ('SAMPLE_2', '2021-08-11'),
            ('SAMPLE_2', '2021-08-18'),
            ('SAMPLE_2', '2021-08-20'),
            ('SAMPLE_2', '2021-08-24')],
           )
2021-08-11 00:00:00 2023-01-25 00:00:00
2021-08-11 00:00:00
(4, 5)
DATE          2021-08-11  2021-08-18  2021-08-20  2021-08-24  2021-08-25
DE000A1EWWW0      166.34     175.080      175.92     160.960     154.440
DE0008404005      173.38     173.820      176.02     173.000     169.880
DE000BASF111       42.52      43.615       44.72      41.495      40.535
DE000BAY0017       57.08      57.230       57.93      55.640      54.495
MultiIndex([('SAMPLE_3', '2021-08-11'),
            ('SAMPLE_3', '2021-08-18'),
            ('SAMPLE_3', '2021-08-20'),
            ('SAMPLE_3', '2021-08-24'),
            ('SAMPLE_3', '2021-08-25')],
           )
2021-08-18 00:00:00 2023-01-25 00:00:00
2021-08-18 00:00:00
(4, 5)
DATE          2021-08-18  2021-08-20  2021-08-24  2021-08-25  2021-08-26
DE000A1EWWW0     175.080      175.92     160.960     154.440     160.940
DE0008404005     173.820      176.02     173.000     169.880     175.980
DE000BASF111      43.615       44.72      41.495      40.535      41.485
DE000BAY0017      57.230       57.93      55.640      54.495      56.150
MultiIndex([('SAMPLE_4', '2021-08-18'),
            ('SAMPLE_4', '2021-08-20'),
            ('SAMPLE_4', '2021-08-24'),
            ('SAMPLE_4', '2021-08-25'),
            ('SAMPLE_4', '2021-08-26')],
           )
2021-08-20 00:00:00 2023-01-25 00:00:00
2021-08-20 00:00:00
(4, 5)
DATE          2021-08-20  2021-08-24  2021-08-25  2021-08-26  2021-08-28
DE000A1EWWW0      175.92     160.960     154.440     160.940     162.880
DE0008404005      176.02     173.000     169.880     175.980     178.280
DE000BASF111       44.72      41.495      40.535      41.485      41.275
DE000BAY0017       57.93      55.640      54.495      56.150      56.180
MultiIndex([('SAMPLE_5', '2021-08-20'),
            ('SAMPLE_5', '2021-08-24'),
            ('SAMPLE_5', '2021-08-25'),
            ('SAMPLE_5', '2021-08-26'),
            ('SAMPLE_5', '2021-08-28')],
           )
2021-08-24 00:00:00 2023-01-25 00:00:00
2021-08-24 00:00:00
(4, 5)
DATE          2021-08-24  2021-08-25  2021-08-26  2021-08-28  2021-08-31
DE000A1EWWW0     160.960     154.440     160.940     162.880     168.460
DE0008404005     173.000     169.880     175.980     178.280     180.280
DE000BASF111      41.495      40.535      41.485      41.275      42.925
DE000BAY0017      55.640      54.495      56.150      56.180      57.740
MultiIndex([('SAMPLE_6', '2021-08-24'),
            ('SAMPLE_6', '2021-08-25'),
            ('SAMPLE_6', '2021-08-26'),
            ('SAMPLE_6', '2021-08-28'),
            ('SAMPLE_6', '2021-08-31')],
           )
2021-08-25 00:00:00 2023-01-25 00:00:00
2021-08-25 00:00:00
(4, 5)
DATE          2021-08-25  2021-08-26  2021-08-28  2021-08-31  2021-09-07
DE000A1EWWW0     154.440     160.940     162.880     168.460    167.6400
DE0008404005     169.880     175.980     178.280     180.280    182.0000
DE000BASF111      40.535      41.485      41.275      42.925     41.3025
DE000BAY0017      54.495      56.150      56.180      57.740     57.0900
MultiIndex([('SAMPLE_7', '2021-08-25'),
            ('SAMPLE_7', '2021-08-26'),
            ('SAMPLE_7', '2021-08-28'),
            ('SAMPLE_7', '2021-08-31'),
            ('SAMPLE_7', '2021-09-07')],
           )
2021-08-26 00:00:00 2023-01-25 00:00:00
2021-08-26 00:00:00
(4, 5)
DATE          2021-08-26  2021-08-28  2021-08-31  2021-09-07  2021-09-10
DE000A1EWWW0     160.940     162.880     168.460    167.6400      170.32
DE0008404005     175.980     178.280     180.280    182.0000      183.10
DE000BASF111      41.485      41.275      42.925     41.3025       43.08
DE000BAY0017      56.150      56.180      57.740     57.0900       60.09
MultiIndex([('SAMPLE_8', '2021-08-26'),
            ('SAMPLE_8', '2021-08-28'),
            ('SAMPLE_8', '2021-08-31'),
            ('SAMPLE_8', '2021-09-07'),
            ('SAMPLE_8', '2021-09-10')],
           )
2021-08-28 00:00:00 2023-01-25 00:00:00
2021-08-28 00:00:00
(4, 5)
DATE          2021-08-28  2021-08-31  2021-09-07  2021-09-10  2021-09-11
DE000A1EWWW0     162.880     168.460    167.6400      170.32      171.88
DE0008404005     178.280     180.280    182.0000      183.10      181.04
DE000BASF111      41.275      42.925     41.3025       43.08       42.84
DE000BAY0017      56.180      57.740     57.0900       60.09       59.36
MultiIndex([('SAMPLE_9', '2021-08-28'),
            ('SAMPLE_9', '2021-08-31'),
            ('SAMPLE_9', '2021-09-07'),
            ('SAMPLE_9', '2021-09-10'),
            ('SAMPLE_9', '2021-09-11')],
           )
2021-08-31 00:00:00 2023-01-25 00:00:00
2021-08-31 00:00:00
(4, 5)
DATE          2021-08-31  2021-09-07  2021-09-10  2021-09-11  2021-09-17
DE000A1EWWW0     168.460    167.6400      170.32      171.88      166.08
DE0008404005     180.280    182.0000      183.10      181.04      185.14
DE000BASF111      42.925     41.3025       43.08       42.84       46.04
DE000BAY0017      57.740     57.0900       60.09       59.36       61.86
MultiIndex([('SAMPLE_10', '2021-08-31'),
            ('SAMPLE_10', '2021-09-07'),
            ('SAMPLE_10', '2021-09-10'),
            ('SAMPLE_10', '2021-09-11'),
            ('SAMPLE_10', '2021-09-17')],
           )
2021-09-07 00:00:00 2023-01-25 00:00:00
2021-09-07 00:00:00
(4, 5)
DATE          2021-09-07  2021-09-10  2021-09-11  2021-09-17  2021-09-22
DE000A1EWWW0    167.6400      170.32      171.88      166.08      162.00
DE0008404005    182.0000      183.10      181.04      185.14      183.50
DE000BASF111     41.3025       43.08       42.84       46.04       45.88
DE000BAY0017     57.0900       60.09       59.36       61.86       61.98
MultiIndex([('SAMPLE_11', '2021-09-07'),
            ('SAMPLE_11', '2021-09-10'),
            ('SAMPLE_11', '2021-09-11'),
            ('SAMPLE_11', '2021-09-17'),
            ('SAMPLE_11', '2021-09-22')],
           )
2021-09-10 00:00:00 2023-01-25 00:00:00
2021-09-10 00:00:00
(4, 5)
DATE          2021-09-10  2021-09-11  2021-09-17  2021-09-22  2021-09-23
DE000A1EWWW0      170.32      171.88      166.08      162.00      166.44
DE0008404005      183.10      181.04      185.14      183.50      186.50
DE000BASF111       43.08       42.84       46.04       45.88       49.07
DE000BAY0017       60.09       59.36       61.86       61.98       63.49
MultiIndex([('SAMPLE_12', '2021-09-10'),
            ('SAMPLE_12', '2021-09-11'),
            ('SAMPLE_12', '2021-09-17'),
            ('SAMPLE_12', '2021-09-22'),
            ('SAMPLE_12', '2021-09-23')],
           )
2021-09-11 00:00:00 2023-01-25 00:00:00
2021-09-11 00:00:00
(4, 5)
DATE          2021-09-11  2021-09-17  2021-09-22  2021-09-23  2021-09-25
DE000A1EWWW0      171.88      166.08      162.00      166.44      169.68
DE0008404005      181.04      185.14      183.50      186.50      182.00
DE000BASF111       42.84       46.04       45.88       49.07       49.13
DE000BAY0017       59.36       61.86       61.98       63.49       63.49
MultiIndex([('SAMPLE_13', '2021-09-11'),
            ('SAMPLE_13', '2021-09-17'),
            ('SAMPLE_13', '2021-09-22'),
            ('SAMPLE_13', '2021-09-23'),
            ('SAMPLE_13', '2021-09-25')],
           )
2021-09-17 00:00:00 2023-01-25 00:00:00
2021-09-17 00:00:00
(4, 5)
DATE          2021-09-17  2021-09-22  2021-09-23  2021-09-25  2021-10-01
DE000A1EWWW0      166.08      162.00      166.44      169.68      186.00
DE0008404005      185.14      183.50      186.50      182.00      196.16
DE000BASF111       46.04       45.88       49.07       49.13       52.25
DE000BAY0017       61.86       61.98       63.49       63.49       65.80
MultiIndex([('SAMPLE_14', '2021-09-17'),
            ('SAMPLE_14', '2021-09-22'),
            ('SAMPLE_14', '2021-09-23'),
            ('SAMPLE_14', '2021-09-25'),
            ('SAMPLE_14', '2021-10-01')],
           )
2021-09-22 00:00:00 2023-01-25 00:00:00
2021-09-22 00:00:00
(4, 5)
DATE          2021-09-22  2021-09-23  2021-09-25  2021-10-01  2021-10-02
DE000A1EWWW0      162.00      166.44      169.68      186.00      188.34
DE0008404005      183.50      186.50      182.00      196.16      198.62
DE000BASF111       45.88       49.07       49.13       52.25       52.43
DE000BAY0017       61.98       63.49       63.49       65.80       66.83
MultiIndex([('SAMPLE_15', '2021-09-22'),
            ('SAMPLE_15', '2021-09-23'),
            ('SAMPLE_15', '2021-09-25'),
            ('SAMPLE_15', '2021-10-01'),
            ('SAMPLE_15', '2021-10-02')],
           )
2021-09-23 00:00:00 2023-01-25 00:00:00
2021-09-23 00:00:00
(4, 5)
DATE          2021-09-23  2021-09-25  2021-10-01  2021-10-02  2021-10-06
DE000A1EWWW0      166.44      169.68      186.00      188.34      187.12
DE0008404005      186.50      182.00      196.16      198.62      194.74
DE000BASF111       49.07       49.13       52.25       52.43       52.59
DE000BAY0017       63.49       63.49       65.80       66.83       65.52
MultiIndex([('SAMPLE_16', '2021-09-23'),
            ('SAMPLE_16', '2021-09-25'),
            ('SAMPLE_16', '2021-10-01'),
            ('SAMPLE_16', '2021-10-02'),
            ('SAMPLE_16', '2021-10-06')],
           )
2021-09-25 00:00:00 2023-01-25 00:00:00
2021-09-25 00:00:00
(4, 5)
DATE          2021-09-25  2021-10-01  2021-10-02  2021-10-06  2021-10-07
DE000A1EWWW0      169.68      186.00      188.34      187.12      182.44
DE0008404005      182.00      196.16      198.62      194.74      193.90
DE000BASF111       49.13       52.25       52.43       52.59       51.74
DE000BAY0017       63.49       65.80       66.83       65.52       66.86
MultiIndex([('SAMPLE_17', '2021-09-25'),
            ('SAMPLE_17', '2021-10-01'),
            ('SAMPLE_17', '2021-10-02'),
            ('SAMPLE_17', '2021-10-06'),
            ('SAMPLE_17', '2021-10-07')],
           )
2021-10-01 00:00:00 2023-01-25 00:00:00
2021-10-01 00:00:00
(4, 5)
DATE          2021-10-01  2021-10-02  2021-10-06  2021-10-07  2021-10-13
DE000A1EWWW0      186.00      188.34      187.12      182.44      176.76
DE0008404005      196.16      198.62      194.74      193.90      199.24
DE000BASF111       52.25       52.43       52.59       51.74       50.89
DE000BAY0017       65.80       66.83       65.52       66.86       65.86
MultiIndex([('SAMPLE_18', '2021-10-01'),
            ('SAMPLE_18', '2021-10-02'),
            ('SAMPLE_18', '2021-10-06'),
            ('SAMPLE_18', '2021-10-07'),
            ('SAMPLE_18', '2021-10-13')],
           )
2021-10-02 00:00:00 2023-01-25 00:00:00
2021-10-02 00:00:00
(4, 5)
DATE          2021-10-02  2021-10-06  2021-10-07  2021-10-13  2021-10-15
DE000A1EWWW0      188.34      187.12      182.44      176.76     171.200
DE0008404005      198.62      194.74      193.90      199.24     197.860
DE000BASF111       52.43       52.59       51.74       50.89      48.670
DE000BAY0017       66.83       65.52       66.86       65.86      63.445
MultiIndex([('SAMPLE_19', '2021-10-02'),
            ('SAMPLE_19', '2021-10-06'),
            ('SAMPLE_19', '2021-10-07'),
            ('SAMPLE_19', '2021-10-13'),
            ('SAMPLE_19', '2021-10-15')],
           )
2021-10-06 00:00:00 2023-01-25 00:00:00
2021-10-06 00:00:00
(4, 5)
DATE          2021-10-06  2021-10-07  2021-10-13  2021-10-15  2021-10-16
DE000A1EWWW0      187.12      182.44      176.76     171.200     174.800
DE0008404005      194.74      193.90      199.24     197.860     199.080
DE000BASF111       52.59       51.74       50.89      48.670      49.625
DE000BAY0017       65.52       66.86       65.86      63.445      64.470
MultiIndex([('SAMPLE_20', '2021-10-06'),
            ('SAMPLE_20', '2021-10-07'),
            ('SAMPLE_20', '2021-10-13'),
            ('SAMPLE_20', '2021-10-15'),
            ('SAMPLE_20', '2021-10-16')],
           )
2021-10-07 00:00:00 2023-01-25 00:00:00
2021-10-07 00:00:00
(4, 5)
DATE          2021-10-07  2021-10-13  2021-10-15  2021-10-16  2021-10-20
DE000A1EWWW0      182.44      176.76     171.200     174.800      171.88
DE0008404005      193.90      199.24     197.860     199.080      194.80
DE000BASF111       51.74       50.89      48.670      49.625       48.64
DE000BAY0017       66.86       65.86      63.445      64.470       63.38
MultiIndex([('SAMPLE_21', '2021-10-07'),
            ('SAMPLE_21', '2021-10-13'),
            ('SAMPLE_21', '2021-10-15'),
            ('SAMPLE_21', '2021-10-16'),
            ('SAMPLE_21', '2021-10-20')],
           )
2021-10-13 00:00:00 2023-01-25 00:00:00
2021-10-13 00:00:00
(4, 5)
DATE          2021-10-13  2021-10-15  2021-10-16  2021-10-20  2021-10-21
DE000A1EWWW0      176.76     171.200     174.800      171.88     175.380
DE0008404005      199.24     197.860     199.080      194.80     200.850
DE000BASF111       50.89      48.670      49.625       48.64      49.875
DE000BAY0017       65.86      63.445      64.470       63.38      63.780
MultiIndex([('SAMPLE_22', '2021-10-13'),
            ('SAMPLE_22', '2021-10-15'),
            ('SAMPLE_22', '2021-10-16'),
            ('SAMPLE_22', '2021-10-20'),
            ('SAMPLE_22', '2021-10-21')],
           )
2021-10-15 00:00:00 2023-01-25 00:00:00
2021-10-15 00:00:00
(4, 5)
DATE          2021-10-15  2021-10-16  2021-10-20  2021-10-21  2021-10-26
DE000A1EWWW0     171.200     174.800      171.88     175.380      180.96
DE0008404005     197.860     199.080      194.80     200.850      200.40
DE000BASF111      48.670      49.625       48.64      49.875       49.34
DE000BAY0017      63.445      64.470       63.38      63.780       61.60
MultiIndex([('SAMPLE_23', '2021-10-15'),
            ('SAMPLE_23', '2021-10-16'),
            ('SAMPLE_23', '2021-10-20'),
            ('SAMPLE_23', '2021-10-21'),
            ('SAMPLE_23', '2021-10-26')],
           )
2021-10-16 00:00:00 2023-01-25 00:00:00
2021-10-16 00:00:00
(4, 5)
DATE          2021-10-16  2021-10-20  2021-10-21  2021-10-26  2021-10-28
DE000A1EWWW0     174.800      171.88     175.380      180.96     181.860
DE0008404005     199.080      194.80     200.850      200.40     205.150
DE000BASF111      49.625       48.64      49.875       49.34      49.675
DE000BAY0017      64.470       63.38      63.780       61.60      57.895
MultiIndex([('SAMPLE_24', '2021-10-16'),
            ('SAMPLE_24', '2021-10-20'),
            ('SAMPLE_24', '2021-10-21'),
            ('SAMPLE_24', '2021-10-26'),
            ('SAMPLE_24', '2021-10-28')],
           )
2021-10-20 00:00:00 2023-01-25 00:00:00
2021-10-20 00:00:00
(4, 5)
DATE          2021-10-20  2021-10-21  2021-10-26  2021-10-28  2021-11-03
DE000A1EWWW0      171.88     175.380      180.96     181.860     187.720
DE0008404005      194.80     200.850      200.40     205.150     199.420
DE000BASF111       48.64      49.875       49.34      49.675      47.615
DE000BAY0017       63.38      63.780       61.60      57.895      60.470
MultiIndex([('SAMPLE_25', '2021-10-20'),
            ('SAMPLE_25', '2021-10-21'),
            ('SAMPLE_25', '2021-10-26'),
            ('SAMPLE_25', '2021-10-28'),
            ('SAMPLE_25', '2021-11-03')],
           )
2021-10-21 00:00:00 2023-01-25 00:00:00
2021-10-21 00:00:00
(4, 5)
DATE          2021-10-21  2021-10-26  2021-10-28  2021-11-03  2021-11-05
DE000A1EWWW0     175.380      180.96     181.860     187.720     192.260
DE0008404005     200.850      200.40     205.150     199.420     217.000
DE000BASF111      49.875       49.34      49.675      47.615      47.430
DE000BAY0017      63.780       61.60      57.895      60.470      60.885
MultiIndex([('SAMPLE_26', '2021-10-21'),
            ('SAMPLE_26', '2021-10-26'),
            ('SAMPLE_26', '2021-10-28'),
            ('SAMPLE_26', '2021-11-03'),
            ('SAMPLE_26', '2021-11-05')],
           )
2021-10-26 00:00:00 2023-01-25 00:00:00
2021-10-26 00:00:00
(4, 5)
DATE          2021-10-26  2021-10-28  2021-11-03  2021-11-05  2021-11-06
DE000A1EWWW0      180.96     181.860     187.720     192.260     194.180
DE0008404005      200.40     205.150     199.420     217.000     214.650
DE000BASF111       49.34      49.675      47.615      47.430      47.415
DE000BAY0017       61.60      57.895      60.470      60.885      59.970
MultiIndex([('SAMPLE_27', '2021-10-26'),
            ('SAMPLE_27', '2021-10-28'),
            ('SAMPLE_27', '2021-11-03'),
            ('SAMPLE_27', '2021-11-05'),
            ('SAMPLE_27', '2021-11-06')],
           )
2021-10-28 00:00:00 2023-01-25 00:00:00
2021-10-28 00:00:00
(4, 5)
DATE          2021-10-28  2021-11-03  2021-11-05  2021-11-06  2021-11-10
DE000A1EWWW0     181.860     187.720     192.260     194.180      188.24
DE0008404005     205.150     199.420     217.000     214.650      214.35
DE000BASF111      49.675      47.615      47.430      47.415       50.84
DE000BAY0017      57.895      60.470      60.885      59.970       61.78
MultiIndex([('SAMPLE_28', '2021-10-28'),
            ('SAMPLE_28', '2021-11-03'),
            ('SAMPLE_28', '2021-11-05'),
            ('SAMPLE_28', '2021-11-06'),
            ('SAMPLE_28', '2021-11-10')],
           )
2021-11-03 00:00:00 2023-01-25 00:00:00
2021-11-03 00:00:00
(4, 5)
DATE          2021-11-03  2021-11-05  2021-11-06  2021-11-10  2021-11-11
DE000A1EWWW0     187.720     192.260     194.180      188.24      183.18
DE0008404005     199.420     217.000     214.650      214.35      210.95
DE000BASF111      47.615      47.430      47.415       50.84       50.31
DE000BAY0017      60.470      60.885      59.970       61.78       62.53
MultiIndex([('SAMPLE_29', '2021-11-03'),
            ('SAMPLE_29', '2021-11-05'),
            ('SAMPLE_29', '2021-11-06'),
            ('SAMPLE_29', '2021-11-10'),
            ('SAMPLE_29', '2021-11-11')],
           )
2021-11-05 00:00:00 2023-01-25 00:00:00
2021-11-05 00:00:00
(4, 5)
DATE          2021-11-05  2021-11-06  2021-11-10  2021-11-11  2021-11-13
DE000A1EWWW0     192.260     194.180      188.24      183.18      192.08
DE0008404005     217.000     214.650      214.35      210.95      212.60
DE000BASF111      47.430      47.415       50.84       50.31       51.76
DE000BAY0017      60.885      59.970       61.78       62.53       64.50
MultiIndex([('SAMPLE_30', '2021-11-05'),
            ('SAMPLE_30', '2021-11-06'),

ValueError: Columns must be same length as key

In [110]:
def build_predicted_df(models_df: pd.DataFrame, ts: pd.DataFrame, look_back: int):
    """
    TODO:
        Fct da wrappare passando come input :
            fare distinct valori look_back
            splittare models_df e ts (entrambi hanno index isin) per livello di look_back relativo a tali prodotti
            invocare build_predicted_df con look_back e relativo ritaglio di models_df e ts
    """
    from degiro.degiroUtils import sample_field_parser, get_prediction

    # Genero ss : columns -> columns di ss; ts.columns -> index di ss
    sample_col = [f"SAMPLE_{sample}" for sample in range(ts.shape[0]-look_back)]
    date_col = [(ts.index[positional:(positional+look_back)]) for positional, date in enumerate(ts.index[:-look_back])]

    columns = []
    for c, sample in enumerate(sample_col):
        for obs_date in date_col[c]:
            columns.append((sample, obs_date))

    ss = pd.DataFrame(index=ts.columns, columns=pd.MultiIndex.from_tuples(columns))
    last_date = ss.columns.get_level_values(level=1)[-2]
    for i, obs_date in enumerate(ts.index[:len(date_col)]):
        if obs_date >= last_date:
            logger.debug(obs_date, last_date)
            break
        try:
            date_window = ts.index[i:(i+look_back)]
            cols = ss.columns[ss.columns.get_level_values(level=0)==f"SAMPLE_{i}"]
            ss[cols] = ts.loc[date_window].T.astype(np.float)
            
        except:
            #logger.debug(i)
            #logger.debug(date_window)
            logger.debug(cols)

    ss_T = ss.T
    ss_T.index.set_names(["SAMPLE", "DATE"], inplace=True)
    ss_T["Y"] = "GROUND_TRUE"
    ss_T.reset_index("SAMPLE", inplace=True)
    ss_T.rename(columns={"SAMPLE" : "SAMPLE_OLD"}, inplace=True)
    ss_T["SAMPLE"] = ss_T.SAMPLE_OLD.apply(sample_field_parser, look_back=look_back)

    ground_truth = ss_T.reset_index().groupby("SAMPLE_OLD").head(1).iloc[look_back:-1].set_index(["Y", "SAMPLE", "DATE"]).T
    pp = ss.T.reset_index("DATE").iloc[:-look_back*(look_back+1)].set_index("DATE", append=True)
    pp["Y"] = "SAMPLES"
    pp = pp.reset_index().set_index(["Y", "SAMPLE", "DATE"])
    ss = pp.T
    ss = pd.merge(ss, ground_truth, how="inner", left_index=True, right_index=True)

    ground_prediction = pd.DataFrame(index=ss[("GROUND_TRUE")].index, columns=ss[("GROUND_TRUE")].columns, data=None)
    tot_stocks=len(ground_prediction.index)
    for c, isin in enumerate(ground_prediction.index):
        for sample, data in zip(ground_prediction.columns.get_level_values(0), ground_prediction.columns.get_level_values(1)):
            ground_prediction.loc[isin, (sample, data)] = get_prediction(isin, sample, models_df, ss)
        logger.debug(round(c/tot_stocks, 4))

    samples = ss[("SAMPLES")]

    return samples, ground_truth, ground_prediction

In [30]:
def build_predicted_df_OLD(models_df: pd.DataFrame, ts: pd.DataFrame, look_back: int):
    """OLD
    TODO:
        Fct da wrappare passando come input :
            fare distinct valori look_back
            splittare models_df e ts (entrambi hanno index isin) per livello di look_back relativo a tali prodotti
            invocare build_predicted_df con look_back e relativo ritaglio di models_df e ts
    """
    from degiro.degiroUtils import sample_field_parser, get_prediction

    # Genero ss : columns -> indici di ss; ts.columns -> columns di ss
    sample_col = [f"SAMPLE_{sample}" for sample in range(ts.shape[0]-look_back)]
    date_col = [(ts.index[positional:(positional+look_back)]) for positional, date in enumerate(ts.index[:-look_back])]

    columns = []
    for c, sample in enumerate(sample_col):
        for date in date_col[c]:
            columns.append((sample, date))

    ss = pd.DataFrame(index=ts.columns, columns=pd.MultiIndex.from_tuples(columns))
    last_obs = ss.columns.get_level_values(level=1)[-2]
    for i, index in enumerate(ts.index[:len(date_col)]):
        if index >= last_obs:
            logger.debug(index, last_obs)
            break
        try:
            date_indexes = ts.index[i:(i+look_back)]
            cols = ss.columns[ss.columns.get_level_values(level=0)==f"SAMPLE_{i}"]
            ss[cols] = ts.loc[date_indexes].T.astype(np.float)
            
        except:
            logger.debug(i)
            logger.debug(date_indexes)
            logger.debug(cols)

    ss_T = ss.T
    ss_T.index.set_names(["SAMPLE", "DATE"], inplace=True)
    ss_T["Y"] = "GROUND_TRUE"
    ss_T.reset_index("SAMPLE", inplace=True)
    ss_T.rename(columns={"SAMPLE" : "SAMPLE_OLD"}, inplace=True)
    ss_T["SAMPLE"] = ss_T.SAMPLE_OLD.apply(sample_field_parser, look_back=look_back)

    ground_truth = ss_T.reset_index().groupby("SAMPLE_OLD").head(1).iloc[look_back:-1].set_index(["Y", "SAMPLE", "DATE"]).T
    pp = ss.T.reset_index("DATE").iloc[:-look_back*(look_back+1)].set_index("DATE", append=True)
    pp["Y"] = "SAMPLES"
    pp = pp.reset_index().set_index(["Y", "SAMPLE", "DATE"])
    ss = pp.T
    ss = pd.merge(ss, ground_truth, how="inner", left_index=True, right_index=True)

    ground_prediction = pd.DataFrame(index=ss[("GROUND_TRUE")].index, columns=ss[("GROUND_TRUE")].columns, data=None)
    tot_stocks=len(ground_prediction.index)
    for c, isin in enumerate(ground_prediction.index):
        for sample, data in zip(ground_prediction.columns.get_level_values(0), ground_prediction.columns.get_level_values(1)):
            ground_prediction.loc[isin, (sample, data)] = get_prediction(isin, sample, models_df, ss)
        logger.debug(round(c/tot_stocks, 4))

    samples = ss[("SAMPLES")]

    return samples, ground_truth, ground_prediction

In [111]:
%%time
#from degiro.degiroUtils import build_predicted_df

samples, ground_truth, ground_prediction = build_predicted_df(df_4_ref, ts_to_test.iloc[-n_obs:], look_back)

DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_0', '2021-10-22'),
            ('SAMPLE_0', '2021-10-25'),
            ('SAMPLE_0', '2021-11-04'),
            ('SAMPLE_0', '2021-11-06'),
            ('SAMPLE_0', '2021-11-14'),
            ('SAMPLE_0', '2021-11-18'),
            ('SAMPLE_0', '2021-11-22'),
            ('SAMPLE_0', '2021-11-26'),
            ('SAMPLE_0', '2021-12-03'),
            ('SAMPLE_0', '2021-12-04')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_1', '2021-10-25'),
            ('SAMPLE_1', '2021-11-04'),
            ('SAMPLE_1', '2021-11-06'),
            ('SAMPLE_1', '2021-11-14'),
            ('SAMPLE_1', '2021-11-18'),
            ('SAMPLE_1', '2021-11-22'),
            ('SAMPLE_1', '2021-11-26'),
            ('SAMPLE_1', '2021-12-03'),
            ('SAMPLE_1', '2021-12-04'),
            ('SAMPLE_1', '2021-12-10')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_2', '2021-11-04'),
            ('SAMPLE_2', '2021-11-06'),
            ('SAMPLE_2', '2021-11-14'),
            ('SAMPLE_2', '2021-11-18'),
            ('SAMPLE_2', '2021-11-22'),
            ('SAMPLE_2', '2021-11-26'),
            ('SAMPLE_2', '2021-12-03'),
            ('SAMPLE_2', '2021-12-04'),
            ('SAMPLE_2', '2021-12-10'),
            ('SAMPLE_2', '2021-12-12')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_3', '2021-11-06'),
            ('SAMPLE_3', '2021-11-14'),
            ('SAMPLE_3', '2021-11-18'),
            ('SAMPLE_3', '2021-11-22'),
            ('SAMPLE_3', '2021-11-26'),
            ('SAMPLE_3', '2021-12-03'),
            ('SAMPLE_3', '2021-12-04'),
            ('SAMPLE_3', '2021-12-10'),
            ('SAMPLE_3', '2021-12-12'),
            ('SAMPLE_3', '2021-12-17')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_4', '2021-11-14'),
            ('SAMPLE_4', '2021-11-18'),
            ('SAMPLE_4', '2021-11-22'),
            ('SAMPLE_4', '2021-11-26'),
            ('SAMPLE_4', '2021-12-03'),
            ('SAMPLE_4', '2021-12-04'),
            ('SAMPLE_4', '2021-12-10'),
            ('SAMPLE_4', '2021-12-12'),
            ('SAMPLE_4', '2021-12-17'),
            ('SAMPLE_4', '2021-12-24')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_5', '2021-11-18'),
            ('SAMPLE_5', '2021-11-22'),
            ('SAMPLE_5', '2021-11-26'),
            ('SAMPLE_5', '2021-12-03'),
            ('SAMPLE_5', '2021-12-04'),
            ('SAMPLE_5', '2021-12-10'),
            ('SAMPLE_5', '2021-12-12'),
            ('SAMPLE_5', '2021-12-17'),
            ('SAMPLE_5', '2021-12-24'),
            ('SAMPLE_5', '2021-12-30')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_6', '2021-11-22'),
            ('SAMPLE_6', '2021-11-26'),
            ('SAMPLE_6', '2021-12-03'),
            ('SAMPLE_6', '2021-12-04'),
            ('SAMPLE_6', '2021-12-10'),
            ('SAMPLE_6', '2021-12-12'),
            ('SAMPLE_6', '2021-12-17'),
            ('SAMPLE_6', '2021-12-24'),
            ('SAMPLE_6', '2021-12-30'),
            ('SAMPLE_6', '2022-01-03')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_7', '2021-11-26'),
            ('SAMPLE_7', '2021-12-03'),
            ('SAMPLE_7', '2021-12-04'),
            ('SAMPLE_7', '2021-12-10'),
            ('SAMPLE_7', '2021-12-12'),
            ('SAMPLE_7', '2021-12-17'),
            ('SAMPLE_7', '2021-12-24'),
            ('SAMPLE_7', '2021-12-30'),
            ('SAMPLE_7', '2022-01-03'),
            ('SAMPLE_7', '2022-01-07')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_8', '2021-12-03'),
            ('SAMPLE_8', '2021-12-04'),
            ('SAMPLE_8', '2021-12-10'),
            ('SAMPLE_8', '2021-12-12'),
            ('SAMPLE_8', '2021-12-17'),
            ('SAMPLE_8', '2021-12-24'),
            ('SAMPLE_8', '2021-12-30'),
            ('SAMPLE_8', '2022-01-03'),
            ('SAMPLE_8', '2022-01-07'),
            ('SAMPLE_8', '2022-01-14')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_9', '2021-12-04'),
            ('SAMPLE_9', '2021-12-10'),
            ('SAMPLE_9', '2021-12-12'),
            ('SAMPLE_9', '2021-12-17'),
            ('SAMPLE_9', '2021-12-24'),
            ('SAMPLE_9', '2021-12-30'),
            ('SAMPLE_9', '2022-01-03'),
            ('SAMPLE_9', '2022-01-07'),
            ('SAMPLE_9', '2022-01-14'),
            ('SAMPLE_9', '2022-01-15')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_10', '2021-12-10'),
            ('SAMPLE_10', '2021-12-12'),
            ('SAMPLE_10', '2021-12-17'),
            ('SAMPLE_10', '2021-12-24'),
            ('SAMPLE_10', '2021-12-30'),
            ('SAMPLE_10', '2022-01-03'),
            ('SAMPLE_10', '2022-01-07'),
            ('SAMPLE_10', '2022-01-14'),
            ('SAMPLE_10', '2022-01-15'),
            ('SAMPLE_10', '2022-01-23')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_11', '2021-12-12'),
            ('SAMPLE_11', '2021-12-17'),
            ('SAMPLE_11', '2021-12-24'),
            ('SAMPLE_11', '2021-12-30'),
            ('SAMPLE_11', '2022-01-03'),
            ('SAMPLE_11', '2022-01-07'),
            ('SAMPLE_11', '2022-01-14'),
            ('SAMPLE_11', '2022-01-15'),
            ('SAMPLE_11', '2022-01-23'),
            ('SAMPLE_11', '2022-01-28')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_12', '2021-12-17'),
            ('SAMPLE_12', '2021-12-24'),
            ('SAMPLE_12', '2021-12-30'),
            ('SAMPLE_12', '2022-01-03'),
            ('SAMPLE_12', '2022-01-07'),
            ('SAMPLE_12', '2022-01-14'),
            ('SAMPLE_12', '2022-01-15'),
            ('SAMPLE_12', '2022-01-23'),
            ('SAMPLE_12', '2022-01-28'),
            ('SAMPLE_12', '2022-02-03')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_13', '2021-12-24'),
            ('SAMPLE_13', '2021-12-30'),
            ('SAMPLE_13', '2022-01-03'),
            ('SAMPLE_13', '2022-01-07'),
            ('SAMPLE_13', '2022-01-14'),
            ('SAMPLE_13', '2022-01-15'),
            ('SAMPLE_13', '2022-01-23'),
            ('SAMPLE_13', '2022-01-28'),
            ('SAMPLE_13', '2022-02-03'),
            ('SAMPLE_13', '2022-02-05')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_14', '2021-12-30'),
            ('SAMPLE_14', '2022-01-03'),
            ('SAMPLE_14', '2022-01-07'),
            ('SAMPLE_14', '2022-01-14'),
            ('SAMPLE_14', '2022-01-15'),
            ('SAMPLE_14', '2022-01-23'),
            ('SAMPLE_14', '2022-01-28'),
            ('SAMPLE_14', '2022-02-03'),
            ('SAMPLE_14', '2022-02-05'),
            ('SAMPLE_14', '2022-02-07')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_15', '2022-01-03'),
            ('SAMPLE_15', '2022-01-07'),
            ('SAMPLE_15', '2022-01-14'),
            ('SAMPLE_15', '2022-01-15'),
            ('SAMPLE_15', '2022-01-23'),
            ('SAMPLE_15', '2022-01-28'),
            ('SAMPLE_15', '2022-02-03'),
            ('SAMPLE_15', '2022-02-05'),
            ('SAMPLE_15', '2022-02-07'),
            ('SAMPLE_15', '2022-02-13')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_16', '2022-01-07'),
            ('SAMPLE_16', '2022-01-14'),
            ('SAMPLE_16', '2022-01-15'),
            ('SAMPLE_16', '2022-01-23'),
            ('SAMPLE_16', '2022-01-28'),
            ('SAMPLE_16', '2022-02-03'),
            ('SAMPLE_16', '2022-02-05'),
            ('SAMPLE_16', '2022-02-07'),
            ('SAMPLE_16', '2022-02-13'),
            ('SAMPLE_16', '2022-02-19')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_17', '2022-01-14'),
            ('SAMPLE_17', '2022-01-15'),
            ('SAMPLE_17', '2022-01-23'),
            ('SAMPLE_17', '2022-01-28'),
            ('SAMPLE_17', '2022-02-03'),
            ('SAMPLE_17', '2022-02-05'),
            ('SAMPLE_17', '2022-02-07'),
            ('SAMPLE_17', '2022-02-13'),
            ('SAMPLE_17', '2022-02-19'),
            ('SAMPLE_17', '2022-02-24')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_18', '2022-01-15'),
            ('SAMPLE_18', '2022-01-23'),
            ('SAMPLE_18', '2022-01-28'),
            ('SAMPLE_18', '2022-02-03'),
            ('SAMPLE_18', '2022-02-05'),
            ('SAMPLE_18', '2022-02-07'),
            ('SAMPLE_18', '2022-02-13'),
            ('SAMPLE_18', '2022-02-19'),
            ('SAMPLE_18', '2022-02-24'),
            ('SAMPLE_18', '2022-02-26')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_19', '2022-01-23'),
            ('SAMPLE_19', '2022-01-28'),
            ('SAMPLE_19', '2022-02-03'),
            ('SAMPLE_19', '2022-02-05'),
            ('SAMPLE_19', '2022-02-07'),
            ('SAMPLE_19', '2022-02-13'),
            ('SAMPLE_19', '2022-02-19'),
            ('SAMPLE_19', '2022-02-24'),
            ('SAMPLE_19', '2022-02-26'),
            ('SAMPLE_19', '2022-03-05')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_20', '2022-01-28'),
            ('SAMPLE_20', '2022-02-03'),
            ('SAMPLE_20', '2022-02-05'),
            ('SAMPLE_20', '2022-02-07'),
            ('SAMPLE_20', '2022-02-13'),
            ('SAMPLE_20', '2022-02-19'),
            ('SAMPLE_20', '2022-02-24'),
            ('SAMPLE_20', '2022-02-26'),
            ('SAMPLE_20', '2022-03-05'),
            ('SAMPLE_20', '2022-03-06')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_21', '2022-02-03'),
            ('SAMPLE_21', '2022-02-05'),
            ('SAMPLE_21', '2022-02-07'),
            ('SAMPLE_21', '2022-02-13'),
            ('SAMPLE_21', '2022-02-19'),
            ('SAMPLE_21', '2022-02-24'),
            ('SAMPLE_21', '2022-02-26'),
            ('SAMPLE_21', '2022-03-05'),
            ('SAMPLE_21', '2022-03-06'),
            ('SAMPLE_21', '2022-03-14')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_22', '2022-02-05'),
            ('SAMPLE_22', '2022-02-07'),
            ('SAMPLE_22', '2022-02-13'),
            ('SAMPLE_22', '2022-02-19'),
            ('SAMPLE_22', '2022-02-24'),
            ('SAMPLE_22', '2022-02-26'),
            ('SAMPLE_22', '2022-03-05'),
            ('SAMPLE_22', '2022-03-06'),
            ('SAMPLE_22', '2022-03-14'),
            ('SAMPLE_22', '2022-03-19')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_23', '2022-02-07'),
            ('SAMPLE_23', '2022-02-13'),
            ('SAMPLE_23', '2022-02-19'),
            ('SAMPLE_23', '2022-02-24'),
            ('SAMPLE_23', '2022-02-26'),
            ('SAMPLE_23', '2022-03-05'),
            ('SAMPLE_23', '2022-03-06'),
            ('SAMPLE_23', '2022-03-14'),
            ('SAMPLE_23', '2022-03-19'),
            ('SAMPLE_23', '2022-03-24')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_24', '2022-02-13'),
            ('SAMPLE_24', '2022-02-19'),
            ('SAMPLE_24', '2022-02-24'),
            ('SAMPLE_24', '2022-02-26'),
            ('SAMPLE_24', '2022-03-05'),
            ('SAMPLE_24', '2022-03-06'),
            ('SAMPLE_24', '2022-03-14'),
            ('SAMPLE_24', '2022-03-19'),
            ('SAMPLE_24', '2022-03-24'),
            ('SAMPLE_24', '2022-03-26')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_25', '2022-02-19'),
            ('SAMPLE_25', '2022-02-24'),
            ('SAMPLE_25', '2022-02-26'),
            ('SAMPLE_25', '2022-03-05'),
            ('SAMPLE_25', '2022-03-06'),
            ('SAMPLE_25', '2022-03-14'),
            ('SAMPLE_25', '2022-03-19'),
            ('SAMPLE_25', '2022-03-24'),
            ('SAMPLE_25', '2022-03-26'),
            ('SAMPLE_25', '2022-03-28')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_26', '2022-02-24'),
            ('SAMPLE_26', '2022-02-26'),
            ('SAMPLE_26', '2022-03-05'),
            ('SAMPLE_26', '2022-03-06'),
            ('SAMPLE_26', '2022-03-14'),
            ('SAMPLE_26', '2022-03-19'),
            ('SAMPLE_26', '2022-03-24'),
            ('SAMPLE_26', '2022-03-26'),
            ('SAMPLE_26', '2022-03-28'),
            ('SAMPLE_26', '2022-04-03')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_27', '2022-02-26'),
            ('SAMPLE_27', '2022-03-05'),
            ('SAMPLE_27', '2022-03-06'),
            ('SAMPLE_27', '2022-03-14'),
            ('SAMPLE_27', '2022-03-19'),
            ('SAMPLE_27', '2022-03-24'),
            ('SAMPLE_27', '2022-03-26'),
            ('SAMPLE_27', '2022-03-28'),
            ('SAMPLE_27', '2022-04-03'),
            ('SAMPLE_27', '2022-04-09')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_28', '2022-03-05'),
            ('SAMPLE_28', '2022-03-06'),
            ('SAMPLE_28', '2022-03-14'),
            ('SAMPLE_28', '2022-03-19'),
            ('SAMPLE_28', '2022-03-24'),
            ('SAMPLE_28', '2022-03-26'),
            ('SAMPLE_28', '2022-03-28'),
            ('SAMPLE_28', '2022-04-03'),
            ('SAMPLE_28', '2022-04-09'),
            ('SAMPLE_28', '2022-04-16')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_29', '2022-03-06'),
            ('SAMPLE_29', '2022-03-14'),
            ('SAMPLE_29', '2022-03-19'),
            ('SAMPLE_29', '2022-03-24'),
            ('SAMPLE_29', '2022-03-26'),
            ('SAMPLE_29', '2022-03-28'),
            ('SAMPLE_29', '2022-04-03'),
            ('SAMPLE_29', '2022-04-09'),
            ('SAMPLE_29', '2022-04-16'),
            ('SAMPLE_29', '2022-04-17')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_30', '2022-03-14'),
            ('SAMPLE_30', '2022-03-19'),
            ('SAMPLE_30', '2022-03-24'),
            ('SAMPLE_30', '2022-03-26'),
            ('SAMPLE_30', '2022-03-28'),
            ('SAMPLE_30', '2022-04-03'),
            ('SAMPLE_30', '2022-04-09'),
            ('SAMPLE_30', '2022-04-16'),
            ('SAMPLE_30', '2022-04-17'),
            ('SAMPLE_30', '2022-04-25')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_31', '2022-03-19'),
            ('SAMPLE_31', '2022-03-24'),
            ('SAMPLE_31', '2022-03-26'),
            ('SAMPLE_31', '2022-03-28'),
            ('SAMPLE_31', '2022-04-03'),
            ('SAMPLE_31', '2022-04-09'),
            ('SAMPLE_31', '2022-04-16'),
            ('SAMPLE_31', '2022-04-17'),
            ('SAMPLE_31', '2022-04-25'),
            ('SAMPLE_31', '2022-04-29')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_32', '2022-03-24'),
            ('SAMPLE_32', '2022-03-26'),
            ('SAMPLE_32', '2022-03-28'),
            ('SAMPLE_32', '2022-04-03'),
            ('SAMPLE_32', '2022-04-09'),
            ('SAMPLE_32', '2022-04-16'),
            ('SAMPLE_32', '2022-04-17'),
            ('SAMPLE_32', '2022-04-25'),
            ('SAMPLE_32', '2022-04-29'),
            ('SAMPLE_32', '2022-05-06')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_33', '2022-03-26'),
            ('SAMPLE_33', '2022-03-28'),
            ('SAMPLE_33', '2022-04-03'),
            ('SAMPLE_33', '2022-04-09'),
            ('SAMPLE_33', '2022-04-16'),
            ('SAMPLE_33', '2022-04-17'),
            ('SAMPLE_33', '2022-04-25'),
            ('SAMPLE_33', '2022-04-29'),
            ('SAMPLE_33', '2022-05-06'),
            ('SAMPLE_33', '2022-05-12')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_34', '2022-03-28'),
            ('SAMPLE_34', '2022-04-03'),
            ('SAMPLE_34', '2022-04-09'),
            ('SAMPLE_34', '2022-04-16'),
            ('SAMPLE_34', '2022-04-17'),
            ('SAMPLE_34', '2022-04-25'),
            ('SAMPLE_34', '2022-04-29'),
            ('SAMPLE_34', '2022-05-06'),
            ('SAMPLE_34', '2022-05-12'),
            ('SAMPLE_34', '2021-05-21')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_35', '2022-04-03'),
            ('SAMPLE_35', '2022-04-09'),
            ('SAMPLE_35', '2022-04-16'),
            ('SAMPLE_35', '2022-04-17'),
            ('SAMPLE_35', '2022-04-25'),
            ('SAMPLE_35', '2022-04-29'),
            ('SAMPLE_35', '2022-05-06'),
            ('SAMPLE_35', '2022-05-12'),
            ('SAMPLE_35', '2021-05-21'),
            ('SAMPLE_35', '2021-05-22')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_36', '2022-04-09'),
            ('SAMPLE_36', '2022-04-16'),
            ('SAMPLE_36', '2022-04-17'),
            ('SAMPLE_36', '2022-04-25'),
            ('SAMPLE_36', '2022-04-29'),
            ('SAMPLE_36', '2022-05-06'),
            ('SAMPLE_36', '2022-05-12'),
            ('SAMPLE_36', '2021-05-21'),
            ('SAMPLE_36', '2021-05-22'),
            ('SAMPLE_36', '2021-05-24')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_37', '2022-04-16'),
            ('SAMPLE_37', '2022-04-17'),
            ('SAMPLE_37', '2022-04-25'),
            ('SAMPLE_37', '2022-04-29'),
            ('SAMPLE_37', '2022-05-06'),
            ('SAMPLE_37', '2022-05-12'),
            ('SAMPLE_37', '2021-05-21'),
            ('SAMPLE_37', '2021-05-22'),
            ('SAMPLE_37', '2021-05-24'),
            ('SAMPLE_37', '2021-06-01')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_38', '2022-04-17'),
            ('SAMPLE_38', '2022-04-25'),
            ('SAMPLE_38', '2022-04-29'),
            ('SAMPLE_38', '2022-05-06'),
            ('SAMPLE_38', '2022-05-12'),
            ('SAMPLE_38', '2021-05-21'),
            ('SAMPLE_38', '2021-05-22'),
            ('SAMPLE_38', '2021-05-24'),
            ('SAMPLE_38', '2021-06-01'),
            ('SAMPLE_38', '2021-06-05')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_39', '2022-04-25'),
            ('SAMPLE_39', '2022-04-29'),
            ('SAMPLE_39', '2022-05-06'),
            ('SAMPLE_39', '2022-05-12'),
            ('SAMPLE_39', '2021-05-21'),
            ('SAMPLE_39', '2021-05-22'),
            ('SAMPLE_39', '2021-05-24'),
            ('SAMPLE_39', '2021-06-01'),
            ('SAMPLE_39', '2021-06-05'),
            ('SAMPLE_39', '2021-06-13')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_40', '2022-04-29'),
            ('SAMPLE_40', '2022-05-06'),
            ('SAMPLE_40', '2022-05-12'),
            ('SAMPLE_40', '2021-05-21'),
            ('SAMPLE_40', '2021-05-22'),
            ('SAMPLE_40', '2021-05-24'),
            ('SAMPLE_40', '2021-06-01'),
            ('SAMPLE_40', '2021-06-05'),
            ('SAMPLE_40', '2021-06-13'),
            ('SAMPLE_40', '2021-06-19')],
           )
DEGIRO - build_predicted_df - DEBUG - MultiIndex([('SAMPLE_41', '2022-05-06'),
            ('SAMPLE_41', '2022-05-12'),
            ('SAMPLE_41', '2021-05-21'),
            ('SAMPLE_41', '2021-05-22'),
            ('SAMPLE_41', '2021-05-24'),
            ('SAMPLE_41', '2021-06-01'),
            ('SAMPLE_41', '2021-06-05'),
            ('SAMPLE_41', '2021-06-13'),
            ('SAMPLE_41', '2021-06-19'),
            ('SAMPLE_41', '2021-06-25')],
           )
--- Logging error ---
Traceback (most recent call last):
  File "c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args

ValueError: in user code:

    c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py:1586 predict_function  *
        return step_function(self, iterator)
    c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py:1576 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py:1569 run_step  **
        outputs = model.predict_step(data)
    c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py:1537 predict_step
        return self(x, training=False)
    c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\base_layer.py:1020 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\input_spec.py:269 assert_input_compatibility
        ', found shape=' + display_shape(x.shape))

    ValueError: Input 0 is incompatible with layer sequential_4: expected shape=(None, None, 5), found shape=(None, 1, 10)

In [38]:
samples.shape, ground_truth.shape, ground_prediction.shape

((4, 1505), (5, 301), (4, 301))

In [44]:
samples.head()

SAMPLE         SAMPLE_0                                              \
DATE         2021-10-01 2021-10-03 2021-10-07 2021-10-08 2021-10-09
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_1                                              \
DATE         2021-10-03 2021-10-07 2021-10-08 2021-10-09 2021-10-11
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_2                                              \
DATE         2021-10-07 2021-10-08 2021-10-09 2021-10-11 2021-10-15
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_3                                              \
DATE         2021-10-08 2021-10-09 2021-10-11 2021-10-15 2021-10-17
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_4                                              \
DATE         2021-10-09 2021-10-11 2021-10-15 2021-10-17 2021-10-21
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_5                                              \
DATE         2021-10-11 2021-10-15 2021-10-17 2021-10-21 2021-10-22
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_6                                              \
DATE         2021-10-15 2021-10-17 2021-10-21 2021-10-22 2021-10-23
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_7                                              \
DATE         2021-10-17 2021-10-21 2021-10-22 2021-10-23 2021-10-25
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_8                                              \
DATE         2021-10-21 2021-10-22 2021-10-23 2021-10-25 2021-10-29
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_9                                              \
DATE         2021-10-22 2021-10-23 2021-10-25 2021-10-29 2021-10-31
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_10                                              \
DATE         2021-10-23 2021-10-25 2021-10-29 2021-10-31 2021-11-04
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_11                                              \
DATE         2021-10-25 2021-10-29 2021-10-31 2021-11-04 2021-11-05
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_12                                              \
DATE         2021-10-29 2021-10-31 2021-11-04 2021-11-05 2021-11-06
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_13                                              \
DATE         2021-10-31 2021-11-04 2021-11-05 2021-11-06 2021-11-08
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_14                                              \
DATE         2021-11-04 2021-11-05 2021-11-06 2021-11-08 2021-11-12
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_15                                              \
DATE         2021-11-05 2021-11-06 2021-11-08 2021-11-12 2021-11-14
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_16                                              \
DATE         2021-11-06 2021-11-08 2021-11-12 2021-11-14 2021-11-18
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_17                                              \
DATE         2021-11-08 2021-11-12 2021-11-14 2021-11-18 2021-11-19
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_18                                              \
DATE         2021-11-12 2021-11-14 2021-11-18 2021-11-19 2021-11-20
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_19                                              ...  \
DATE         2021-11-14 2021-11-18 2021-11-19 2021-11-20 2021-11-22  ...
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN  ...
DE0008404005        NaN        NaN        NaN        NaN        NaN  ...
DE000BASF111        NaN        NaN        NaN        NaN        NaN  ...
DE000BAY0017        NaN        NaN        NaN        NaN        NaN  ...

SAMPLE       SAMPLE_221                                              \
DATE         2022-03-12 2022-03-14 2022-03-15 2022-03-18 2022-03-20
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_222                                              \
DATE         2022-03-14 2022-03-15 2022-03-18 2022-03-20 2022-03-22
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_223                                              \
DATE         2022-03-15 2022-03-18 2022-03-20 2022-03-22 2022-03-26
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_224                                              \
DATE         2022-03-18 2022-03-20 2022-03-22 2022-03-26 2022-03-28
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_225                                              \
DATE         2022-03-20 2022-03-22 2022-03-26 2022-03-28 2022-03-29
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_226                                              \
DATE         2022-03-22 2022-03-26 2022-03-28 2022-03-29 2022-04-01
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_227                                              \
DATE         2022-03-26 2022-03-28 2022-03-29 2022-04-01 2022-04-03
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_228                                              \
DATE         2022-03-28 2022-03-29 2022-04-01 2022-04-03 2022-04-05
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_229                                              \
DATE         2022-03-29 2022-04-01 2022-04-03 2022-04-05 2022-04-09
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_230                                              \
DATE         2022-04-01 2022-04-03 2022-04-05 2022-04-09 2022-04-11
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_231                                              \
DATE         2022-04-03 2022-04-05 2022-04-09 2022-04-11 2022-04-12
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_232                                              \
DATE         2022-04-05 2022-04-09 2022-04-11 2022-04-12 2022-04-15
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_233                                              \
DATE         2022-04-09 2022-04-11 2022-04-12 2022-04-15 2022-04-17
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_234                                              \
DATE         2022-04-11 2022-04-12 2022-04-15 2022-04-17 2022-04-19
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_235                                              \
DATE         2022-04-12 2022-04-15 2022-04-17 2022-04-19 2022-04-23
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_236                                              \
DATE         2022-04-15 2022-04-17 2022-04-19 2022-04-23 2022-04-24
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_237                                              \
DATE         2022-04-17 2022-04-19 2022-04-23 2022-04-24 2022-04-25
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_238                                              \
DATE         2022-04-19 2022-04-23 2022-04-24 2022-04-25 2022-04-26
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_239                                              \
DATE         2022-04-23 2022-04-24 2022-04-25 2022-04-26 2022-04-30
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_240
DATE         2022-04-24 2022-04-25 2022-04-26 2022-04-30 2022-05-02
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

[4 rows x 1205 columns]

In [45]:
ground_truth.head()

Y            GROUND_TRUE                                              \
SAMPLE          SAMPLE_0   SAMPLE_1   SAMPLE_2   SAMPLE_3   SAMPLE_4
DATE          2021-10-11 2021-10-15 2021-10-17 2021-10-21 2021-10-22
SAMPLE_OLD      SAMPLE_5   SAMPLE_6   SAMPLE_7   SAMPLE_8   SAMPLE_9
DE000A1EWWW0         NaN        NaN        NaN        NaN        NaN
DE0008404005         NaN        NaN        NaN        NaN        NaN
DE000BASF111         NaN        NaN        NaN        NaN        NaN
DE000BAY0017         NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE         SAMPLE_5   SAMPLE_6   SAMPLE_7   SAMPLE_8   SAMPLE_9
DATE         2021-10-23 2021-10-25 2021-10-29 2021-10-31 2021-11-04
SAMPLE_OLD    SAMPLE_10  SAMPLE_11  SAMPLE_12  SAMPLE_13  SAMPLE_14
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_10  SAMPLE_11  SAMPLE_12  SAMPLE_13  SAMPLE_14
DATE         2021-11-05 2021-11-06 2021-11-08 2021-11-12 2021-11-14
SAMPLE_OLD    SAMPLE_15  SAMPLE_16  SAMPLE_17  SAMPLE_18  SAMPLE_19
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_15  SAMPLE_16  SAMPLE_17  SAMPLE_18  SAMPLE_19
DATE         2021-11-18 2021-11-19 2021-11-20 2021-11-22 2021-11-26
SAMPLE_OLD    SAMPLE_20  SAMPLE_21  SAMPLE_22  SAMPLE_23  SAMPLE_24
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_20  SAMPLE_21  SAMPLE_22  SAMPLE_23  SAMPLE_24
DATE         2021-11-28 2021-12-02 2021-12-03 2021-12-04 2021-12-06
SAMPLE_OLD    SAMPLE_25  SAMPLE_26  SAMPLE_27  SAMPLE_28  SAMPLE_29
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_25  SAMPLE_26  SAMPLE_27  SAMPLE_28  SAMPLE_29
DATE         2021-12-10 2021-12-12 2021-12-16 2021-12-17 2021-12-18
SAMPLE_OLD    SAMPLE_30  SAMPLE_31  SAMPLE_32  SAMPLE_33  SAMPLE_34
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_30  SAMPLE_31  SAMPLE_32  SAMPLE_33  SAMPLE_34
DATE         2021-12-20 2021-12-24 2021-12-26 2021-12-30 2021-12-31
SAMPLE_OLD    SAMPLE_35  SAMPLE_36  SAMPLE_37  SAMPLE_38  SAMPLE_39
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_35  SAMPLE_36  SAMPLE_37  SAMPLE_38  SAMPLE_39
DATE         2022-01-01 2022-01-03 2022-01-07 2022-01-09 2022-01-13
SAMPLE_OLD    SAMPLE_40  SAMPLE_41  SAMPLE_42  SAMPLE_43  SAMPLE_44
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_40  SAMPLE_41  SAMPLE_42  SAMPLE_43  SAMPLE_44
DATE         2022-01-14 2022-01-15 2022-01-17 2022-01-21 2022-01-23
SAMPLE_OLD    SAMPLE_45  SAMPLE_46  SAMPLE_47  SAMPLE_48  SAMPLE_49
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_45  SAMPLE_46  SAMPLE_47  SAMPLE_48  SAMPLE_49
DATE         2022-01-27 2022-01-28 2022-01-30 2022-02-03 2022-02-05
SAMPLE_OLD    SAMPLE_50  SAMPLE_51  SAMPLE_52  SAMPLE_53  SAMPLE_54
DE000A1EWWW0     303.95      304.9      304.8      301.5      307.2
DE0008404005      199.0     198.94     200.85     198.72     199.62
DE000BASF111       66.5      65.98      66.61      64.78      68.01
DE000BAY0017      47.31      47.33    48.0725      47.41      47.85

Y                                                                    \
SAMPLE        SAMPLE_50  SAMPLE_51  SAMPLE_52  SAMPLE_53  SAMPLE_54
DATE         2022-02-07 2022-02-10 2022-02-11 2022-02-13 2022-02-17
SAMPLE_OLD    SAMPLE_55  SAMPLE_56  SAMPLE_57  SAMPLE_58  SAMPLE_59
DE000A1EWWW0      313.2      319.1        NaN        NaN        NaN
DE0008404005      200.8     201.65        NaN        NaN        NaN
DE000BASF111      68.14     69.155        NaN        NaN        NaN
DE000BAY0017      47.64     47.765        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_55  SAMPLE_56  SAMPLE_57  SAMPLE_58  SAMPLE_59
DATE         2022-02-19 2022-02-20 2022-02-21 2022-02-24 2022-02-26
SAMPLE_OLD    SAMPLE_60  SAMPLE_61  SAMPLE_62  SAMPLE_63  SAMPLE_64
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_60  SAMPLE_61  SAMPLE_62  SAMPLE_63  SAMPLE_64
DATE         2022-02-28 2022-03-04 2022-03-05 2022-03-06 2022-03-10
SAMPLE_OLD    SAMPLE_65  SAMPLE_66  SAMPLE_67  SAMPLE_68  SAMPLE_69
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_65  SAMPLE_66  SAMPLE_67  SAMPLE_68  SAMPLE_69
DATE         2022-03-12 2022-03-14 2022-03-18 2022-03-19 2022-03-20
SAMPLE_OLD    SAMPLE_70  SAMPLE_71  SAMPLE_72  SAMPLE_73  SAMPLE_74
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_70  SAMPLE_71  SAMPLE_72  SAMPLE_73  SAMPLE_74
DATE         2022-03-24 2022-03-26 2022-03-28 2022-04-01 2022-04-02
SAMPLE_OLD    SAMPLE_75  SAMPLE_76  SAMPLE_77  SAMPLE_78  SAMPLE_79
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_75  SAMPLE_76  SAMPLE_77  SAMPLE_78  SAMPLE_79
DATE         2022-04-03 2022-04-07 2022-04-09 2022-04-11 2022-04-15
SAMPLE_OLD    SAMPLE_80  SAMPLE_81  SAMPLE_82  SAMPLE_83  SAMPLE_84
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_80  SAMPLE_81  SAMPLE_82  SAMPLE_83  SAMPLE_84
DATE         2022-04-16 2022-04-17 2022-04-21 2022-04-23 2022-04-25
SAMPLE_OLD    SAMPLE_85  SAMPLE_86  SAMPLE_87  SAMPLE_88  SAMPLE_89
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_85  SAMPLE_86  SAMPLE_87  SAMPLE_88  SAMPLE_89
DATE         2022-04-29 2022-04-30 2022-05-01 2022-05-06 2022-05-08
SAMPLE_OLD    SAMPLE_90  SAMPLE_91  SAMPLE_92  SAMPLE_93  SAMPLE_94
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

Y                                                                    \
SAMPLE        SAMPLE_90  SAMPLE_91  SAMPLE_92  SAMPLE_93  SAMPLE_94
DATE         2022-05-12 2021-05-18 2021-05-21 2021-05-22 2021-05-24
SAMPLE_OLD    SAMPLE_95  SAMPLE_96  SAMPLE_97  SAMPLE_98  SAMPLE_99
DE000A1EWWW0     288.75     179.98     180.96     180.48     173.36
DE0008404005     217.35     198.22      200.4     198.34     193.72
DE000BASF111      69.25      49.11      49.34     49.035      48.45
DE000BAY0017      57.12       62.9       61.6      60.28      61.68

Y                                                                         ...  \
SAMPLE         SAMPLE_95   SAMPLE_96   SAMPLE_97   SAMPLE_98   SAMPLE_99  ...
DATE          2021-05-28  2021-05-30  2021-06-01  2021-06-04  2021-06-05  ...
SAMPLE_OLD    SAMPLE_100  SAMPLE_101  SAMPLE_102  SAMPLE_103  SAMPLE_104  ...
DE000A1EWWW0      181.36      194.05      194.18      193.72      188.24  ...
DE0008404005       195.7       214.5      214.65       216.2      214.35  ...
DE000BASF111      47.615      48.925      47.415        50.3       50.84  ...
DE000BAY0017       60.08       61.07       59.97       62.92       61.78  ...

Y                                                                         \
SAMPLE        SAMPLE_141  SAMPLE_142  SAMPLE_143  SAMPLE_144  SAMPLE_145
DATE          2021-09-13  2021-09-17  2021-09-19  2021-09-21  2021-09-25
SAMPLE_OLD    SAMPLE_146  SAMPLE_147  SAMPLE_148  SAMPLE_149  SAMPLE_150
DE000A1EWWW0       254.2      252.75       254.0      244.65      252.75
DE0008404005       225.9       226.2      226.05       224.1       220.0
DE000BASF111       67.89       67.81      66.785       66.12       65.75
DE000BAY0017       52.06       52.49       51.24      50.065      48.335

Y                                                                         \
SAMPLE        SAMPLE_146  SAMPLE_147  SAMPLE_148  SAMPLE_149  SAMPLE_150
DATE          2021-09-26  2021-09-27  2021-10-02  2021-10-04  2021-10-09
SAMPLE_OLD    SAMPLE_151  SAMPLE_152  SAMPLE_153  SAMPLE_154  SAMPLE_155
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_151  SAMPLE_152  SAMPLE_153  SAMPLE_154  SAMPLE_155
DATE          2021-10-11  2021-10-12  2021-10-15  2021-10-17  2021-10-19
SAMPLE_OLD    SAMPLE_156  SAMPLE_157  SAMPLE_158  SAMPLE_159  SAMPLE_160
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_156  SAMPLE_157  SAMPLE_158  SAMPLE_159  SAMPLE_160
DATE          2021-10-23  2021-10-25  2021-10-26  2021-10-29  2021-10-31
SAMPLE_OLD    SAMPLE_161  SAMPLE_162  SAMPLE_163  SAMPLE_164  SAMPLE_165
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_161  SAMPLE_162  SAMPLE_163  SAMPLE_164  SAMPLE_165
DATE          2021-11-02  2021-11-06  2021-11-08  2021-11-09  2021-11-12
SAMPLE_OLD    SAMPLE_166  SAMPLE_167  SAMPLE_168  SAMPLE_169  SAMPLE_170
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_166  SAMPLE_167  SAMPLE_168  SAMPLE_169  SAMPLE_170
DATE          2021-11-14  2021-11-16  2021-11-20  2021-11-22  2021-11-23
SAMPLE_OLD    SAMPLE_171  SAMPLE_172  SAMPLE_173  SAMPLE_174  SAMPLE_175
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_171  SAMPLE_172  SAMPLE_173  SAMPLE_174  SAMPLE_175
DATE          2021-11-26  2021-11-28  2021-11-30  2021-12-04  2021-12-06
SAMPLE_OLD    SAMPLE_176  SAMPLE_177  SAMPLE_178  SAMPLE_179  SAMPLE_180
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_176  SAMPLE_177  SAMPLE_178  SAMPLE_179  SAMPLE_180
DATE          2021-12-07  2021-12-10  2021-12-12  2021-12-14  2021-12-18
SAMPLE_OLD    SAMPLE_181  SAMPLE_182  SAMPLE_183  SAMPLE_184  SAMPLE_185
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_181  SAMPLE_182  SAMPLE_183  SAMPLE_184  SAMPLE_185
DATE          2021-12-20  2021-12-21  2021-12-24  2021-12-26  2021-12-28
SAMPLE_OLD    SAMPLE_186  SAMPLE_187  SAMPLE_188  SAMPLE_189  SAMPLE_190
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_186  SAMPLE_187  SAMPLE_188  SAMPLE_189  SAMPLE_190
DATE          2022-01-01  2022-01-03  2022-01-04  2022-01-07  2022-01-09
SAMPLE_OLD    SAMPLE_191  SAMPLE_192  SAMPLE_193  SAMPLE_194  SAMPLE_195
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_191  SAMPLE_192  SAMPLE_193  SAMPLE_194  SAMPLE_195
DATE          2022-01-11  2022-01-15  2022-01-17  2022-01-18  2022-01-21
SAMPLE_OLD    SAMPLE_196  SAMPLE_197  SAMPLE_198  SAMPLE_199  SAMPLE_200
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_196  SAMPLE_197  SAMPLE_198  SAMPLE_199  SAMPLE_200
DATE          2022-01-23  2022-01-25  2022-01-29  2022-01-31  2022-02-01
SAMPLE_OLD    SAMPLE_201  SAMPLE_202  SAMPLE_203  SAMPLE_204  SAMPLE_205
DE000A1EWWW0         NaN       300.0      301.45      299.45      301.95
DE0008404005         NaN      198.66      197.72      198.26      198.24
DE000BASF111         NaN       65.31       64.94       65.52       66.87
DE000BAY0017         NaN       47.74       47.69       47.01      47.145

Y                                                                         \
SAMPLE        SAMPLE_201  SAMPLE_202  SAMPLE_203  SAMPLE_204  SAMPLE_205
DATE          2022-02-04  2022-02-06  2022-02-08  2022-02-12  2022-02-14
SAMPLE_OLD    SAMPLE_206  SAMPLE_207  SAMPLE_208  SAMPLE_209  SAMPLE_210
DE000A1EWWW0      303.95       306.7       307.4         NaN         NaN
DE0008404005       199.0     200.775      199.26         NaN         NaN
DE000BASF111        66.5        66.3       65.22         NaN         NaN
DE000BAY0017       47.31       47.76       47.79         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_206  SAMPLE_207  SAMPLE_208  SAMPLE_209  SAMPLE_210
DATE          2022-02-15  2022-02-18  2022-02-20  2022-02-22  2022-02-26
SAMPLE_OLD    SAMPLE_211  SAMPLE_212  SAMPLE_213  SAMPLE_214  SAMPLE_215
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \
SAMPLE        SAMPLE_211  SAMPLE_212  SAMPLE_213  SAMPLE_214  SAMPLE_215
DATE          2022-02-28  2022-03-01  2022-03-04  2022-03-06  2022-03-08
SAMPLE_OLD    SAMPLE_216  SAMPLE_217  SAMPLE_218  SAMPLE_219  SAMPLE_220
DE000A1EWWW0         NaN         NaN         NaN         NaN         NaN
DE0008404005         NaN         NaN         NaN         NaN         NaN
DE000BASF111         NaN         NaN         NaN         NaN         NaN
DE000BAY0017         NaN         NaN         NaN         NaN         NaN

Y                                                                         \

In [46]:
ground_prediction.head()

SAMPLE,SAMPLE_0,SAMPLE_1,SAMPLE_2,SAMPLE_3,SAMPLE_4,SAMPLE_5,SAMPLE_6,SAMPLE_7,SAMPLE_8,SAMPLE_9,SAMPLE_10,SAMPLE_11,SAMPLE_12,SAMPLE_13,SAMPLE_14,SAMPLE_15,SAMPLE_16,SAMPLE_17,SAMPLE_18,SAMPLE_19,SAMPLE_20,SAMPLE_21,SAMPLE_22,SAMPLE_23,SAMPLE_24,SAMPLE_25,SAMPLE_26,SAMPLE_27,SAMPLE_28,SAMPLE_29,SAMPLE_30,SAMPLE_31,SAMPLE_32,SAMPLE_33,SAMPLE_34,SAMPLE_35,SAMPLE_36,SAMPLE_37,SAMPLE_38,SAMPLE_39,SAMPLE_40,SAMPLE_41,SAMPLE_42,SAMPLE_43,SAMPLE_44,SAMPLE_45,SAMPLE_46,SAMPLE_47,SAMPLE_48,SAMPLE_49,SAMPLE_50,SAMPLE_51,SAMPLE_52,SAMPLE_53,SAMPLE_54,SAMPLE_55,SAMPLE_56,SAMPLE_57,SAMPLE_58,SAMPLE_59,SAMPLE_60,SAMPLE_61,SAMPLE_62,SAMPLE_63,SAMPLE_64,SAMPLE_65,SAMPLE_66,SAMPLE_67,SAMPLE_68,SAMPLE_69,SAMPLE_70,SAMPLE_71,SAMPLE_72,SAMPLE_73,SAMPLE_74,SAMPLE_75,SAMPLE_76,SAMPLE_77,SAMPLE_78,SAMPLE_79,SAMPLE_80,SAMPLE_81,SAMPLE_82,SAMPLE_83,SAMPLE_84,SAMPLE_85,SAMPLE_86,SAMPLE_87,SAMPLE_88,SAMPLE_89,SAMPLE_90,SAMPLE_91,SAMPLE_92,SAMPLE_93,SAMPLE_94,SAMPLE_95,SAMPLE_96,SAMPLE_97,SAMPLE_98,SAMPLE_99,...,SAMPLE_141,SAMPLE_142,SAMPLE_143,SAMPLE_144,SAMPLE_145,SAMPLE_146,SAMPLE_147,SAMPLE_148,SAMPLE_149,SAMPLE_150,SAMPLE_151,SAMPLE_152,SAMPLE_153,SAMPLE_154,SAMPLE_155,SAMPLE_156,SAMPLE_157,SAMPLE_158,SAMPLE_159,SAMPLE_160,SAMPLE_161,SAMPLE_162,SAMPLE_163,SAMPLE_164,SAMPLE_165,SAMPLE_166,SAMPLE_167,SAMPLE_168,SAMPLE_169,SAMPLE_170,SAMPLE_171,SAMPLE_172,SAMPLE_173,SAMPLE_174,SAMPLE_175,SAMPLE_176,SAMPLE_177,SAMPLE_178,SAMPLE_179,SAMPLE_180,SAMPLE_181,SAMPLE_182,SAMPLE_183,SAMPLE_184,SAMPLE_185,SAMPLE_186,SAMPLE_187,SAMPLE_188,SAMPLE_189,SAMPLE_190,SAMPLE_191,SAMPLE_192,SAMPLE_193,SAMPLE_194,SAMPLE_195,SAMPLE_196,SAMPLE_197,SAMPLE_198,SAMPLE_199,SAMPLE_200,SAMPLE_201,SAMPLE_202,SAMPLE_203,SAMPLE_204,SAMPLE_205,SAMPLE_206,SAMPLE_207,SAMPLE_208,SAMPLE_209,SAMPLE_210,SAMPLE_211,SAMPLE_212,SAMPLE_213,SAMPLE_214,SAMPLE_215,SAMPLE_216,SAMPLE_217,SAMPLE_218,SAMPLE_219,SAMPLE_220,SAMPLE_221,SAMPLE_222,SAMPLE_223,SAMPLE_224,SAMPLE_225,SAMPLE_226,SAMPLE_227,SAMPLE_228,SAMPLE_229,SAMPLE_230,SAMPLE_231,SAMPLE_232,SAMPLE_233,SAMPLE_234,SAMPLE_235,SAMPLE_236,SAMPLE_237,SAMPLE_238,SAMPLE_239,SAMPLE_240
DATE,2021-10-11,2021-10-15,2021-10-17,2021-10-21,2021-10-22,2021-10-23,2021-10-25,2021-10-29,2021-10-31,2021-11-04,2021-11-05,2021-11-06,2021-11-08,2021-11-12,2021-11-14,2021-11-18,2021-11-19,2021-11-20,2021-11-22,2021-11-26,2021-11-28,2021-12-02,2021-12-03,2021-12-04,2021-12-06,2021-12-10,2021-12-12,2021-12-16,2021-12-17,2021-12-18,2021-12-20,2021-12-24,2021-12-26,2021-12-30,2021-12-31,2022-01-01,2022-01-03,2022-01-07,2022-01-09,2022-01-13,2022-01-14,2022-01-15,2022-01-17,2022-01-21,2022-01-23,2022-01-27,2022-01-28,2022-01-30,2022-02-03,2022-02-05,2022-02-07,2022-02-10,2022-02-11,2022-02-13,2022-02-17,2022-02-19,2022-02-20,2022-02-21,2022-02-24,2022-02-26,2022-02-28,2022-03-04,2022-03-05,2022-03-06,2022-03-10,2022-03-12,2022-03-14,2022-03-18,2022-03-19,2022-03-20,2022-03-24,2022-03-26,2022-03-28,2022-04-01,2022-04-02,2022-04-03,2022-04-07,2022-04-09,2022-04-11,2022-04-15,2022-04-16,2022-04-17,2022-04-21,2022-04-23,2022-04-25,2022-04-29,2022-04-30,2022-05-01,2022-05-06,2022-05-08,2022-05-12,2021-05-18,2021-05-21,2021-05-22,2021-05-24,2021-05-28,2021-05-30,2021-06-01,2021-06-04,2021-06-05,...,2021-09-13,2021-09-17,2021-09-19,2021-09-21,2021-09-25,2021-09-26,2021-09-27,2021-10-02,2021-10-04,2021-10-09,2021-10-11,2021-10-12,2021-10-15,2021-10-17,2021-10-19,2021-10-23,2021-10-25,2021-10-26,2021-10-29,2021-10-31,2021-11-02,2021-11-06,2021-11-08,2021-11-09,2021-11-12,2021-11-14,2021-11-16,2021-11-20,2021-11-22,2021-11-23,2021-11-26,2021-11-28,2021-11-30,2021-12-04,2021-12-06,2021-12-07,2021-12-10,2021-12-12,2021-12-14,2021-12-18,2021-12-20,2021-12-21,2021-12-24,2021-12-26,2021-12-28,2022-01-01,2022-01-03,2022-01-04,2022-01-07,2022-01-09,2022-01-11,2022-01-15,2022-01-17,2022-01-18,2022-01-21,2022-01-23,2022-01-25,2022-01-29,2022-01-31,2022-02-01,2022-02-04,2022-02-06,2022-02-08,2022-02-12,2022-02-14,2022-02-15,2022-02-18,2022-02-20,2022-02-22,2022-02-26,2022-02-28,2022-03-01,2022-03-04,2022-03-06,2022-03-08,2022-03-12,2022-03-14,2022-03-15,2022-03-18,2022-03-20,2022-03-22,2022-03-26,2022-03-28,2022-03-29,2022-04-01,2022-04-03,2022-04-05,2022-04-09,2022-04-11,2022-04-12,2022-04-15,2022-04-17,2022-04-19,2022-04-23,2022-04-24,2022-04-25,2022-04-26,2022-04-30,2022-05-02,2022-05-06
DE000A1EWWW0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.041565,308.618042,314.453125,309.147888,304.468201,305.185516,328.96283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179.77449,186.429291,192.618683,195.213806,197.128235,...,252.584747,254.482544,252.789886,253.251068,244.862289,251.794342,258.424561,257.842896,254.476288,255.041306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300.142548,302.864227,303.672974,299.522095,307.27478,308.49707,314.37854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DE0008404005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.253036,200.635605,202.132721,202.298111,201.553909,198.610046,193.726593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198.473541,196.3358,214.905777,216.069702,219.047989,...,222.101486,226.17392,225.36554,225.464767,223.32486,219.457428,216.007889,214.74884,207.975067,208.594711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199.725937,201.045807,199.99649,198.928665,198.896103,201.012711,202.08812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DE000BASF111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.447762,66.91922,68.229279,67.720993,67.078049,66.700729,66.131851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.338467,49.062607,49.411983,48.772243,50.412292,...,66.566071,67.466675,67.280762,66.476166,66.038818,65.587509,65.83358,65.328995,62.418732,62.358242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.268013,66.365555,65.323685,65.444641,66.947891,67.179649,68.173218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DE000BAY0017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.965508,47.661385,47.842144,47.994747,47.384537,47.153225,49.593399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.63176,60.03862,61.20179,60.034981,62.815533,...,52.015625,52.375946,52.520966,51.239594,50.09201,48.222675,48.60947,48.256618,47.131561,47.200119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.346695,47.820152,47.870777,47.678501,47.909943,47.682606,47.838547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
ground_prediction.reset_index().to_csv(raw_file_path / "ground_prediction.csv")
ground_prediction_test = pd.read_csv(raw_file_path / "ground_prediction.csv", header=[0, 1], index_col=[0, 1])

In [34]:
ground_prediction_test.head()

,SAMPLE,SAMPLE_0,SAMPLE_1,SAMPLE_2,SAMPLE_3,SAMPLE_4,SAMPLE_5,SAMPLE_6,SAMPLE_7,SAMPLE_8,SAMPLE_9,SAMPLE_10,SAMPLE_11,SAMPLE_12,SAMPLE_13,SAMPLE_14,SAMPLE_15,SAMPLE_16,SAMPLE_17,SAMPLE_18,SAMPLE_19,SAMPLE_20,SAMPLE_21,SAMPLE_22,SAMPLE_23,SAMPLE_24,SAMPLE_25,SAMPLE_26,SAMPLE_27,SAMPLE_28,SAMPLE_29,SAMPLE_30,SAMPLE_31,SAMPLE_32,SAMPLE_33,SAMPLE_34,SAMPLE_35,SAMPLE_36,SAMPLE_37,SAMPLE_38,SAMPLE_39,SAMPLE_40,SAMPLE_41,SAMPLE_42,SAMPLE_43,SAMPLE_44,SAMPLE_45,SAMPLE_46,SAMPLE_47,SAMPLE_48,SAMPLE_49,SAMPLE_50,SAMPLE_51,SAMPLE_52,SAMPLE_53,SAMPLE_54,SAMPLE_55,SAMPLE_56,SAMPLE_57,SAMPLE_58,SAMPLE_59,SAMPLE_60,SAMPLE_61,SAMPLE_62,SAMPLE_63,SAMPLE_64,SAMPLE_65,SAMPLE_66,SAMPLE_67,SAMPLE_68,SAMPLE_69,SAMPLE_70,SAMPLE_71,SAMPLE_72,SAMPLE_73,SAMPLE_74,SAMPLE_75,SAMPLE_76,SAMPLE_77,SAMPLE_78,SAMPLE_79,SAMPLE_80,SAMPLE_81,SAMPLE_82,SAMPLE_83,SAMPLE_84,SAMPLE_85,SAMPLE_86,SAMPLE_87,SAMPLE_88,SAMPLE_89,SAMPLE_90,SAMPLE_91,SAMPLE_92,SAMPLE_93,SAMPLE_94,SAMPLE_95,SAMPLE_96,SAMPLE_97,SAMPLE_98,SAMPLE_99,...,SAMPLE_201,SAMPLE_202,SAMPLE_203,SAMPLE_204,SAMPLE_205,SAMPLE_206,SAMPLE_207,SAMPLE_208,SAMPLE_209,SAMPLE_210,SAMPLE_211,SAMPLE_212,SAMPLE_213,SAMPLE_214,SAMPLE_215,SAMPLE_216,SAMPLE_217,SAMPLE_218,SAMPLE_219,SAMPLE_220,SAMPLE_221,SAMPLE_222,SAMPLE_223,SAMPLE_224,SAMPLE_225,SAMPLE_226,SAMPLE_227,SAMPLE_228,SAMPLE_229,SAMPLE_230,SAMPLE_231,SAMPLE_232,SAMPLE_233,SAMPLE_234,SAMPLE_235,SAMPLE_236,SAMPLE_237,SAMPLE_238,SAMPLE_239,SAMPLE_240,SAMPLE_241,SAMPLE_242,SAMPLE_243,SAMPLE_244,SAMPLE_245,SAMPLE_246,SAMPLE_247,SAMPLE_248,SAMPLE_249,SAMPLE_250,SAMPLE_251,SAMPLE_252,SAMPLE_253,SAMPLE_254,SAMPLE_255,SAMPLE_256,SAMPLE_257,SAMPLE_258,SAMPLE_259,SAMPLE_260,SAMPLE_261,SAMPLE_262,SAMPLE_263,SAMPLE_264,SAMPLE_265,SAMPLE_266,SAMPLE_267,SAMPLE_268,SAMPLE_269,SAMPLE_270,SAMPLE_271,SAMPLE_272,SAMPLE_273,SAMPLE_274,SAMPLE_275,SAMPLE_276,SAMPLE_277,SAMPLE_278,SAMPLE_279,SAMPLE_280,SAMPLE_281,SAMPLE_282,SAMPLE_283,SAMPLE_284,SAMPLE_285,SAMPLE_286,SAMPLE_287,SAMPLE_288,SAMPLE_289,SAMPLE_290,SAMPLE_291,SAMPLE_292,SAMPLE_293,SAMPLE_294,SAMPLE_295,SAMPLE_296,SAMPLE_297,SAMPLE_298,SAMPLE_299,SAMPLE_300
,DATE,2021-05-21 00:00:00,2021-05-21 00:00:00,2021-05-24 00:00:00,2021-05-28 00:00:00,2021-05-30 00:00:00,2021-06-03 00:00:00,2021-06-04 00:00:00,2021-06-05 00:00:00,2021-06-11 00:00:00,2021-06-13 00:00:00,2021-06-17 00:00:00,2021-06-19 00:00:00,2021-06-20 00:00:00,2021-06-21 00:00:00,2021-06-25 00:00:00,2021-06-27 00:00:00,2021-07-01 00:00:00,2021-07-02 00:00:00,2021-07-03 00:00:00,2021-07-05 00:00:00,2021-07-09 00:00:00,2021-07-11 00:00:00,2021-07-15 00:00:00,2021-07-16 00:00:00,2021-07-17 00:00:00,2021-07-19 00:00:00,2021-07-23 00:00:00,2021-07-25 00:00:00,2021-07-26 00:00:00,2021-07-29 00:00:00,2021-07-31 00:00:00,2021-08-02 00:00:00,2021-08-06 00:00:00,2021-08-08 00:00:00,2021-08-09 00:00:00,2021-08-12 00:00:00,2021-08-14 00:00:00,2021-08-16 00:00:00,2021-08-20 00:00:00,2021-08-22 00:00:00,2021-08-23 00:00:00,2021-08-26 00:00:00,2021-08-28 00:00:00,2021-08-30 00:00:00,2021-09-03 00:00:00,2021-09-05 00:00:00,2021-09-06 00:00:00,2021-09-09 00:00:00,2021-09-11 00:00:00,2021-09-13 00:00:00,2021-09-17 00:00:00,2021-09-19 00:00:00,2021-09-20 00:00:00,2021-09-24 00:00:00,2021-09-26 00:00:00,2021-10-01 00:00:00,2021-10-03 00:00:00,2021-10-07 00:00:00,2021-10-08 00:00:00,2021-10-09 00:00:00,2021-10-11 00:00:00,2021-10-15 00:00:00,2021-10-17 00:00:00,2021-10-21 00:00:00,2021-10-22 00:00:00,2021-10-23 00:00:00,2021-10-25 00:00:00,2021-10-29 00:00:00,2021-10-31 00:00:00,2021-11-04 00:00:00,2021-11-05 00:00:00,2021-11-06 00:00:00,2021-11-08 00:00:00,2021-11-12 00:00:00,2021-11-14 00:00:00,2021-11-18 00:00:00,2021-11-19 00:00:00,2021-11-20 00:00:00,2021-11-22 00:00:00,2021-11-26 00:00:00,2021-11-28 00:00:00,2021-12-02 00:00:00,2021-12-03 00:00:00,2021-12-04 00:00:00,2021-12-06 00:00:00,2021-12-10 00:00:00,2021-12-12 00:00:00,2021-12-16 00:00:00,2021-12-17 00:00:00,2021-12-18 00:00:00,2021-12-20 00:00:00,2021-12-24 00:00:00,2021-12-26 00:00:00,2021-12-30 00:00:00,2021-12-31 00:00:00,2022-01-01 00:00:00,2022-01-03 00:00:00,2022-01-07 00:00:00,2022-01-09 00:00:00,2022-01-13 00:00:00,...,2021-09-13 00:00:00,2021-09-17 00:00:00,2021-09-19 00:00:00,2021-09-21 00:00:00,2021-09-25 00:00:00,2021-09-26 00:00:00,2021-09-27 00:00:00,2021-10-02 00:00:00,2021-10-04 00:00:00,2021-10-09 00:00:00,2021-10-11 00:00:00,2021-10-12 00:00:00,2021-10-15 00:00:00,2021-10-17 00:00:00,2021-10-19 00:00:00,2021-10-23 00:00:00,2021-10-25 00:00:00,2021-10-26 00:00:00,2021-10-29 00:00:00,2021-10-31 00:00:00,2021-11-02 00:00:00,2021-11-06 00:00:00,2021-11-08 00:00:00,2021-11-09 00:00:00,2021-11-12 00:00:00,2021-11-14 00:00:00,2021-11-16 00:00:00,2021-11-20 00:00:00,2021-11-22 00:00:00,2021-11-23 00:00:00,2021-11-26 00:00:00,2021-11-28 00:00:00,2021-11-30 00:00:00,2021-12-04 00:00:00,2021-12-06 00:00:00,2021-12-07 00:00:00,2021-12-10 00:00:00,2021-12-12 00:00:00,2021-12-14 00:00:00,2021-12-18 00:00:00,2021-12-20 00:00:00,2021-12-21 00:00:00,2021-12-24 00:00:00,2021-12-26 00:00:00,2021-12-28 00:00:00,2022-01-01 00:00:00,2022-01-03 00:00:00,2022-01-04 00:00:00,2022-01-07 00:00:00,2022-01-09 00:00:00,2022-01-11 00:00:00,2022-01-15 00:00:00,2022-01-17 00:00:00,2022-01-18 00:00:00,2022-01-21 00:00:00,2022-01-23 00:00:00,2022-01-25 00:00:00,2022-01-29 00:00:00,2022-01-31 00:00:00,2022-02-01 00:00:00,2022-02-04 00:00:00,2022-02-06 00:00:00,2022-02-08 00:00:00,2022-02-12 00:00:00,2022-02-14 00:00:00,2022-02-15 00:00:00,2022-02-18 00:00:00,2022-02-20 00:00:00,2022-02-22 00:00:00,2022-02-26 00:00:00,2022-02-28 00:00:00,2022-03-01 00:00:00,2022-03-04 00:00:00,2022-03-06 00:00:00,2022-03-08 00:00:00,2022-03-12 00:00:00,2022-03-14 00:00:00,2022-03-15 00:00:00,2022-03-18 00:00:00,2022-03-20 00:00:00,2022-03-22 00:00:00,2022-03-26 00:00:00,2022-03-28 00:00:00,2022-03-29 00:00:00,2022-04-01 00:00:00,2022-04-03 00:00:00,2022-04-05 00:00:00,2022-04-09 00:00:00,2022-04-11 00:00:00,2022-04-12 00:00:00,2022-04-15 00:00:00,2022-04-17 00:00:00,2022-04-19 00:00:00,2022-04-23 00:00:00,2022-04-24 00:00:00,2022-04-25 00:00:00,2022-04-26 00:00:00,2022-04-30 00:00:00,2022-05-02 00:00:00,2022-05-06 00:00:00
0,DE000A1EWWW0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,DE0008404005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DE000BASF111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DE000BAY0017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
samples.head()

SAMPLE         SAMPLE_0                                              \
DATE         2021-05-14 2021-05-15 2021-05-16 2021-05-17 2021-05-18
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_1                                              \
DATE         2021-05-15 2021-05-16 2021-05-17 2021-05-18 2021-05-21
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_2                                              \
DATE         2021-05-16 2021-05-17 2021-05-18 2021-05-21 2021-05-21
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_3                                              \
DATE         2021-05-17 2021-05-18 2021-05-21 2021-05-21 2021-05-24
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_4                                              \
DATE         2021-05-18 2021-05-21 2021-05-21 2021-05-24 2021-05-28
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_5                                              \
DATE         2021-05-21 2021-05-21 2021-05-24 2021-05-28 2021-05-30
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_6                                              \
DATE         2021-05-21 2021-05-24 2021-05-28 2021-05-30 2021-06-03
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_7                                              \
DATE         2021-05-24 2021-05-28 2021-05-30 2021-06-03 2021-06-04
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_8                                              \
DATE         2021-05-28 2021-05-30 2021-06-03 2021-06-04 2021-06-05
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE         SAMPLE_9                                              \
DATE         2021-05-30 2021-06-03 2021-06-04 2021-06-05 2021-06-11
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_10                                              \
DATE         2021-06-03 2021-06-04 2021-06-05 2021-06-11 2021-06-13
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_11                                              \
DATE         2021-06-04 2021-06-05 2021-06-11 2021-06-13 2021-06-17
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_12                                              \
DATE         2021-06-05 2021-06-11 2021-06-13 2021-06-17 2021-06-19
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_13                                              \
DATE         2021-06-11 2021-06-13 2021-06-17 2021-06-19 2021-06-20
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_14                                              \
DATE         2021-06-13 2021-06-17 2021-06-19 2021-06-20 2021-06-21
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_15                                              \
DATE         2021-06-17 2021-06-19 2021-06-20 2021-06-21 2021-06-25
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_16                                              \
DATE         2021-06-19 2021-06-20 2021-06-21 2021-06-25 2021-06-27
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_17                                              \
DATE         2021-06-20 2021-06-21 2021-06-25 2021-06-27 2021-07-01
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_18                                              \
DATE         2021-06-21 2021-06-25 2021-06-27 2021-07-01 2021-07-02
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE        SAMPLE_19                                              ...  \
DATE         2021-06-25 2021-06-27 2021-07-01 2021-07-02 2021-07-03  ...
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN  ...
DE0008404005        NaN        NaN        NaN        NaN        NaN  ...
DE000BASF111        NaN        NaN        NaN        NaN        NaN  ...
DE000BAY0017        NaN        NaN        NaN        NaN        NaN  ...

SAMPLE       SAMPLE_281                                              \
DATE         2022-03-12 2022-03-14 2022-03-15 2022-03-18 2022-03-20
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_282                                              \
DATE         2022-03-14 2022-03-15 2022-03-18 2022-03-20 2022-03-22
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_283                                              \
DATE         2022-03-15 2022-03-18 2022-03-20 2022-03-22 2022-03-26
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_284                                              \
DATE         2022-03-18 2022-03-20 2022-03-22 2022-03-26 2022-03-28
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_285                                              \
DATE         2022-03-20 2022-03-22 2022-03-26 2022-03-28 2022-03-29
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_286                                              \
DATE         2022-03-22 2022-03-26 2022-03-28 2022-03-29 2022-04-01
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_287                                              \
DATE         2022-03-26 2022-03-28 2022-03-29 2022-04-01 2022-04-03
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_288                                              \
DATE         2022-03-28 2022-03-29 2022-04-01 2022-04-03 2022-04-05
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_289                                              \
DATE         2022-03-29 2022-04-01 2022-04-03 2022-04-05 2022-04-09
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_290                                              \
DATE         2022-04-01 2022-04-03 2022-04-05 2022-04-09 2022-04-11
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_291                                              \
DATE         2022-04-03 2022-04-05 2022-04-09 2022-04-11 2022-04-12
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_292                                              \
DATE         2022-04-05 2022-04-09 2022-04-11 2022-04-12 2022-04-15
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_293                                              \
DATE         2022-04-09 2022-04-11 2022-04-12 2022-04-15 2022-04-17
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_294                                              \
DATE         2022-04-11 2022-04-12 2022-04-15 2022-04-17 2022-04-19
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_295                                              \
DATE         2022-04-12 2022-04-15 2022-04-17 2022-04-19 2022-04-23
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_296                                              \
DATE         2022-04-15 2022-04-17 2022-04-19 2022-04-23 2022-04-24
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_297                                              \
DATE         2022-04-17 2022-04-19 2022-04-23 2022-04-24 2022-04-25
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_298                                              \
DATE         2022-04-19 2022-04-23 2022-04-24 2022-04-25 2022-04-26
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_299                                              \
DATE         2022-04-23 2022-04-24 2022-04-25 2022-04-26 2022-04-30
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

SAMPLE       SAMPLE_300
DATE         2022-04-24 2022-04-25 2022-04-26 2022-04-30 2022-05-02
DE000A1EWWW0        NaN        NaN        NaN        NaN        NaN
DE0008404005        NaN        NaN        NaN        NaN        NaN
DE000BASF111        NaN        NaN        NaN        NaN        NaN
DE000BAY0017        NaN        NaN        NaN        NaN        NaN

[4 rows x 1505 columns]

In [25]:
sample_col = [f"SAMPLE_{sample}" for sample in range(ts_dax.shape[0]-look_back)]
date_col = [(ts_dax.index[positional:(positional+look_back)]) for positional, date in enumerate(ts_dax.index[:-look_back])]

columns = []
for c, sample in enumerate(sample_col):
    for date in date_col[c]:
        columns.append((sample, date))

ss = pd.DataFrame(index=ts_dax.columns, columns=pd.MultiIndex.from_tuples(columns))
last_obs = ss.columns.get_level_values(level=1)[-2]
for i, index in enumerate(ts_dax.index[:len(date_col)]):
    if index >= last_obs:
        logger.debug(index, last_obs)
        break
    try:
        date_indexes = ts_dax.index[i:(i+look_back)]
        cols = ss.columns[ss.columns.get_level_values(level=0)==f"SAMPLE_{i}"]
        ss[cols] = ts_dax.loc[date_indexes].T.astype(np.float)
        
    except:
        logger.debug(i)
        logger.debug(date_indexes)
        logger.debug(cols)

ss_T = ss.T
ss_T.index.set_names(["SAMPLE", "DATE"], inplace=True)
ss_T["Y"] = "GROUND_TRUE"
ss_T.reset_index("SAMPLE", inplace=True)
ss_T.rename(columns={"SAMPLE" : "SAMPLE_OLD"}, inplace=True)
ss_T["SAMPLE"] = ss_T.SAMPLE_OLD.apply(sample_field_parser, look_back=look_back)

ground_truth = ss_T.reset_index().groupby("SAMPLE_OLD").head(1).iloc[look_back:-1].set_index(["Y", "SAMPLE", "DATE"]).T
pp = ss.T.reset_index("DATE").iloc[:-look_back*(look_back+1)].set_index("DATE", append=True)
pp["Y"] = "SAMPLES"
pp = pp.reset_index().set_index(["Y", "SAMPLE", "DATE"])
ss = pp.T
ss = pd.merge(ss, ground_truth, how="inner", left_index=True, right_index=True)

ground_prediction = pd.DataFrame(index=ss[("GROUND_TRUE")].index, columns=ss[("GROUND_TRUE")].columns, data=None)
tot_stocks=len(ground_prediction.index)
for c, isin in enumerate(ground_prediction.index):
    for sample, data in zip(ground_prediction.columns.get_level_values(0), ground_prediction.columns.get_level_values(1)):
        ground_prediction.loc[isin, (sample, data)] = get_prediction(isin, sample, rnn_models, ss)
    logger.debug(round(c/tot_stocks, 4))

samples = ss[("SAMPLES")]

samples, ground_truth, ground_prediction

In [ ]:
ss.reset_index().to_csv("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\laboratorio\\file\\raw\\dax_ground_true.csv", sep=";")

In [35]:
from degiro.degiroUtils import sample_field_parser, get_prediction

In [29]:
ss_T = ss.T
ss_T.index.set_names(["SAMPLE", "DATE"], inplace=True)
ss_T["Y"] = "GROUND_TRUE"
ss_T.reset_index("SAMPLE", inplace=True)
ss_T.rename(columns={"SAMPLE" : "SAMPLE_OLD"}, inplace=True)
ss_T["SAMPLE"] = ss_T.SAMPLE_OLD.apply(sample_field_parser, look_back=look_back)

ground_truth = ss_T.reset_index().groupby("SAMPLE_OLD").head(1).iloc[look_back:-1].set_index(["Y", "SAMPLE", "DATE"]).T
pp = ss.T.reset_index("DATE").iloc[:-look_back*(look_back+1)].set_index("DATE", append=True)
pp["Y"] = "SAMPLES"
pp = pp.reset_index().set_index(["Y", "SAMPLE", "DATE"])
ss = pp.T
ss = pd.merge(ss, ground_truth, how="inner", left_index=True, right_index=True)

Y               SAMPLES                                              \
SAMPLE         SAMPLE_0   SAMPLE_1   SAMPLE_2   SAMPLE_3   SAMPLE_4
DATE         2019-03-07 2019-03-08 2019-03-09 2019-03-10 2019-03-13
DE000A1EWWW0      279.2      289.5      290.2      294.2      288.9
DE0008404005      210.0      208.4      206.8      203.0      199.8
DE000BASF111      71.08      71.14      70.27      69.09      67.73
DE000BAY0017      51.84      51.62      52.06      52.34      50.12
DE0005190003      76.29       76.1      72.56       72.1       71.5

Y                                                                    ...  \
SAMPLE         SAMPLE_5   SAMPLE_6   SAMPLE_7   SAMPLE_8   SAMPLE_9  ...
DATE         2019-03-14 2019-03-15 2019-03-16 2019-03-17 2019-03-20  ...
DE000A1EWWW0      293.1      288.7      290.6      291.1      295.6  ...
DE0008404005      202.0     200.45     198.26     194.92     195.38  ...
DE000BASF111      68.16       69.4      68.32      68.99       68.0  ...
DE000BAY0017      51.59      55.11      53.34      53.77      53.91  ...
DE0005190003       71.5      70.39      69.32      71.27      71.58  ...

Y            GROUND_TRUE                                              \
SAMPLE        SAMPLE_240 SAMPLE_241 SAMPLE_242 SAMPLE_243 SAMPLE_244
DATE          2020-02-19 2020-02-20 2020-02-21 2020-02-22 2020-02-23
DE000A1EWWW0       191.5     177.08     166.92      173.0      175.7
DE0008404005      134.74      122.1      119.0     129.92     132.42
DE000BASF111      40.795     40.205      39.29      41.06     39.035
DE000BAY0017        50.1     49.815       48.1      50.57     48.125
DE0005190003       41.37      37.66     39.135     40.355      40.09

Y
SAMPLE       SAMPLE_245 SAMPLE_246 SAMPLE_247 SAMPLE_248 SAMPLE_249
DATE         2020-02-26 2020-02-27 2020-02-28 2020-02-29 2020-03-01
DE000A1EWWW0     171.94     173.88      200.8      221.0        NaN
DE0008404005     146.92      146.5     173.02      173.3        NaN
DE000BASF111      41.25      40.91      46.38      46.21        NaN
DE000BAY0017      48.05     48.205      56.07      56.44        NaN
DE0005190003      45.42      44.08      50.65      50.33        NaN

[5 rows x 500 columns]

In [30]:
ss.drop(columns=[ss.columns[-1]], inplace=True)

In [36]:
ground_prediction = pd.DataFrame(index=ss[("GROUND_TRUE")].index, columns=ss[("GROUND_TRUE")].columns, data=None)
tot_stocks=len(ground_prediction.index)
for c, isin in enumerate(ground_prediction.index):
    for sample, data in zip(ground_prediction.columns.get_level_values(0), ground_prediction.columns.get_level_values(1)):
        ground_prediction.loc[isin, (sample, data)] = get_prediction(isin, sample, rnn_models, ss)
    logger.debug(round(c/tot_stocks, 4))

0.0
0.0333
0.0667
0.1
0.1333
0.1667
0.2
0.2333
0.2667
0.3
0.3333
0.3667
0.4
0.4333
0.4667
0.5
0.5333
0.5667
0.6
0.6333
0.6667
0.7
0.7333
0.7667
0.8
0.8333
0.8667
0.9
0.9333
0.9667

## TEST CHECKPOINTS : SAVING AND LOADING FILES
    dax_anagrafica.parquet -> DIFF
    ts_dax.parquet -> EQUALS                    -> OK
    dax_models.parquet -> TYPE DIFF             -> OK

In [90]:
from degiro.degiroUtils import check_equality_btwn_df

In [91]:
"""
dax.P_HISTORICAL.iloc[0]
'expires': '2021-03-04T18:41:29.1355696+01:00'
ultimo -> [364, 279.2]] Ã¨ di oggi 04/03/2020
"""

"\ndax.P_HISTORICAL.iloc[0]\n'expires': '2021-03-04T18:41:29.1355696+01:00'\nultimo -> [364, 279.2]] Ã¨ di oggi 04/03/2020\n"

In [92]:
dax.head()

,P_REAL_TIME,P_HISTORICAL,ANAGRAFICA,NAME,ISIN,SYMBOL,CONTRACT_SIZE,TRADEBLE,P_CLOSE,P_VECTOR,LOG_RET_VECTOR,20_D_AVG,20_D_STD,10_D_AVG,10_D_STD,R_CUMSUM,DAILY_THRESHOLD,DAILY_THRESHOLD_COUNTER,DAILY_THRESHOLD_INT,TIME_SERIES
3457,{'expires': '2021-03-04T18:41:29.1345705+01:00...,"{'times': '2020-03-05/P1D', 'expires': '2021-0...","{'id': '3457', 'name': 'Adidas AG', 'isin': 'D...",Adidas AG,DE000A1EWWW0,ADS,1.0,True,289.50,"[249.1, 241.05, 227.3, 221.0, 200.8, 173.88, 1...","[-0.03285004141650339, -0.05873364999313381, -...",0.001487,0.022197,0.001882,0.023856,1.013092,"[SELL, SELL, SELL, SELL, SELL, HOLD AND PRAY, ...","{'SELL': 31, 'HOLD AND PRAY': 185, 'BUY': 36}","[-1, -1, -1, -1, -1, 0, 0, 0, -1, 1, 1, -1, 1,...",DE000A1EWWW0 DATE ...
4799,{'expires': '2021-03-04T18:41:29.8636333+01:00...,"{'times': '2020-03-05/P1D', 'expires': '2021-0...","{'id': '4799', 'name': 'Allianz SE', 'isin': '...",Allianz SE,DE0008404005,ALV,1.0,True,208.40,"[195.0, 188.9, 171.7, 173.3, 173.02, 146.5, 14...","[-0.03178178405628296, -0.09546900660403405, 0...",0.001409,0.019984,0.002241,0.022868,1.070587,"[SELL, SELL, HOLD AND PRAY, HOLD AND PRAY, SEL...","{'SELL': 22, 'HOLD AND PRAY': 202, 'BUY': 28}","[-1, -1, 0, 0, -1, 0, -1, 0, -1, 1, 1, 0, 1, 1...",DE0008404005 DATE ...
3572,{'expires': '2021-03-04T18:41:30.5036935+01:00...,"{'times': '2020-03-05/P1D', 'expires': '2021-0...","{'id': '3572', 'name': 'BASF SE', 'isin': 'DE0...",BASF SE,DE000BASF111,BAS,1.0,True,71.14,"[53.32, 52.67, 47.105, 46.21, 46.38, 40.91, 41...","[-0.01226546181520991, -0.11166688099466696, -...",0.002311,0.023429,0.002355,0.024455,1.065141,"[HOLD AND PRAY, SELL, HOLD AND PRAY, HOLD AND ...","{'HOLD AND PRAY': 194, 'SELL': 26, 'BUY': 32}","[0, -1, 0, 0, -1, 0, -1, 1, -1, 0, 0, -1, 1, 0...",DE000BASF111 DATE ...
3934,{'expires': '2021-03-04T18:41:31.1607454+01:00...,"{'times': '2020-03-05/P1D', 'expires': '2021-0...","{'id': '3934', 'name': 'Bayer AG', 'isin': 'DE...",Bayer AG,DE000BAY0017,BAYN,1.0,True,51.62,"[66.33, 63.78, 58.42, 56.44, 56.07, 48.205, 48...","[-0.03920262195555299, -0.08778136462231666, -...",-0.000083,0.024336,0.000165,0.024850,0.950371,"[SELL, SELL, SELL, HOLD AND PRAY, SELL, HOLD A...","{'SELL': 31, 'HOLD AND PRAY': 188, 'BUY': 33}","[-1, -1, -1, 0, -1, 0, 0, 1, -1, 1, 0, -1, 1, ...",DE000BAY0017 DATE ...
3597,{'expires': '2021-03-04T18:41:31.8388167+01:00...,"{'times': '2020-03-05/P1D', 'expires': '2021-0...","{'id': '3597', 'name': 'Bayerische Motoren Wer...",Bayerische Motoren Werke AG,DE0005190003,BMW,1.0,True,76.10,"[58.07, 57.22, 51.02, 50.33, 50.65, 44.08, 45....","[-0.014745691761994301, -0.11468577490829877, ...",0.002288,0.022271,0.002917,0.024871,1.075877,"[HOLD AND PRAY, SELL, HOLD AND PRAY, HOLD AND ...","{'HOLD AND PRAY': 183, 'SELL': 31, 'BUY': 38}","[0, -1, 0, 0, -1, 1, -1, 0, -1, -1, 1, -1, 1, ...",DE0005190003 DATE ...

### export / load dax_anagrafica.parquet

In [130]:
dax_anagrafica = anagrafica_builder(dax, "ANAGRAFICA")
dax_anagrafica.set_index("isin", inplace=True)
dax_anagrafica.head()
dax_anagrafica.to_parquet(raw_file_path / "dax_anagrafica.parquet")

In [148]:
dax_anagrafica_test = pd.read_parquet(raw_file_path / "dax_anagrafica.parquet")
check_equality_btwn_df(dax_anagrafica, dax_anagrafica_test)

DFS DIFFERSS
EQUALS id
EQUALS name
EQUALS symbol
-------------> contractSize
-------------> 	(dtype('O'), dtype('float64'))
EQUALS productType
-------------> productTypeId
-------------> 	(dtype('O'), dtype('int64'))
-------------> tradable
-------------> 	(dtype('O'), dtype('bool'))
EQUALS category
EQUALS currency
-------------> strikePrice
-------------> 	(dtype('O'), dtype('float64'))
EQUALS exchangeId
-------------> onlyEodPrices
-------------> 	(dtype('O'), dtype('bool'))
-------------> orderTimeTypes
-------------> 	(dtype('O'), dtype('O'))
-------------> buyOrderTypes
-------------> 	(dtype('O'), dtype('O'))
-------------> sellOrderTypes
-------------> 	(dtype('O'), dtype('O'))
-------------> productBitTypes
-------------> 	(dtype('O'), dtype('O'))
-------------> closePrice
-------------> 	(dtype('O'), dtype('float64'))
EQUALS closePriceDate
EQUALS feedQuality
-------------> orderBookDepth
-------------> 	(dtype('O'), dtype('int64'))
EQUALS vwdIdentifierType
EQUALS vwdId
-------------> qualitySwitchable
-------------> 	(dtype('O'), dtype('bool'))
-------------> qualitySwitchFree
-------------> 	(dtype('O'), dtype('bool'))
-------------> vwdModuleId
-------------> 	(dtype('O'), dtype('int64'))

### export / load ts_dax.parquet

In [143]:
ts_dax.to_parquet(raw_file_path / "ts_dax.parquet", engine="fastparquet")

In [149]:
check_equality_btwn_df(ts_dax, pd.read_parquet(raw_file_path / "ts_dax_test.parquet"))

DFS ARE EQUALS

### export / load dax_models.parquet

In [118]:
from degiro.degiroUtils import rnn_load
rnn_models_test = pd.read_parquet(path=raw_file_path / "dax_models.parquet", engine="fastparquet").set_index("index")
rnn_models_test.index.name = None
rnn_models_test["MODEL"] = rnn_models_test.apply(lambda x: rnn_load(path=_MODEL_PATH_ / x.name), axis=1)

In [150]:
check_equality_btwn_df(rnn_models.drop(columns=["PREDICTED_Y", "TEST_Y"]), rnn_models_test)

DFS DIFFERSS
	SAME TYPE MODEL -> <class 'tensorflow.python.keras.engine.sequential.Sequential'> <class 'tensorflow.python.keras.engine.sequential.Sequential'>
	SAME TYPE SCALER_MIN -> <class 'numpy.float64'> <class 'numpy.float64'>
	SAME TYPE SCALER_MAX -> <class 'numpy.float64'> <class 'numpy.float64'>
EQUALS TRAIN_LOSS
EQUALS TEST_LOSS
EQUALS VOL_IS
EQUALS VOL_OOS
EQUALS TIMESTAMP
EQUALS AVERAGE_PRICE
EQUALS LOOK_BACK
EQUALS LAST_PRICE
EQUALS TRAIN_LOSS_PERC
EQUALS TEST_LOSS_PERC
EQUALS VOL_IS_PERC
EQUALS VOL_OOS_PERC

### export / ground_prediction.csv, ground_true, samples

In [187]:
ground_prediction.reset_index().to_csv(raw_file_path / "ground_prediction.csv")
ground_prediction_test = pd.read_csv(raw_file_path / "ground_prediction.csv", header=[0, 1], index_col=[0, 1])

In [188]:
ground_prediction.shape

(30, 249)

In [189]:
ground_prediction_test.reset_index(level=0, drop=True).shape

(30, 249)

In [42]:
ground_true = ss[("GROUND_TRUE")]
ground_true.head()

SAMPLE,SAMPLE_0,SAMPLE_1,SAMPLE_2,SAMPLE_3,SAMPLE_4,SAMPLE_5,SAMPLE_6,SAMPLE_7,SAMPLE_8,SAMPLE_9,...,SAMPLE_239,SAMPLE_240,SAMPLE_241,SAMPLE_242,SAMPLE_243,SAMPLE_244,SAMPLE_245,SAMPLE_246,SAMPLE_247,SAMPLE_248
DATE,2019-03-08,2019-03-09,2019-03-10,2019-03-13,2019-03-14,2019-03-15,2019-03-16,2019-03-17,2019-03-20,2019-03-21,...,2020-02-16,2020-02-19,2020-02-20,2020-02-21,2020-02-22,2020-02-23,2020-02-26,2020-02-27,2020-02-28,2020-02-29
DE000A1EWWW0,289.5,290.2,294.2,288.9,293.1,288.7,290.6,291.1,295.6,288.8,...,180.62,191.5,177.08,166.92,173.0,175.7,171.94,173.88,200.8,221.0
DE0008404005,208.4,206.8,203.0,199.8,202.0,200.45,198.26,194.92,195.38,194.86,...,131.74,134.74,122.1,119.0,129.92,132.42,146.92,146.5,173.02,173.3
DE000BASF111,71.14,70.27,69.09,67.73,68.16,69.4,68.32,68.99,68.0,67.03,...,39.635,40.795,40.205,39.29,41.06,39.035,41.25,40.91,46.38,46.21
DE000BAY0017,51.62,52.06,52.34,50.12,51.59,55.11,53.34,53.77,53.91,53.11,...,47.5,50.1,49.815,48.1,50.57,48.125,48.05,48.205,56.07,56.44
DE0005190003,76.1,72.56,72.1,71.5,71.5,70.39,69.32,71.27,71.58,71.03,...,39.8,41.37,37.66,39.135,40.355,40.09,45.42,44.08,50.65,50.33

In [43]:
samples = ss[("SAMPLES")]
samples.head()

SAMPLE,SAMPLE_0,SAMPLE_1,SAMPLE_2,SAMPLE_3,SAMPLE_4,SAMPLE_5,SAMPLE_6,SAMPLE_7,SAMPLE_8,SAMPLE_9,...,SAMPLE_240,SAMPLE_241,SAMPLE_242,SAMPLE_243,SAMPLE_244,SAMPLE_245,SAMPLE_246,SAMPLE_247,SAMPLE_248,SAMPLE_249
DATE,2019-03-07,2019-03-08,2019-03-09,2019-03-10,2019-03-13,2019-03-14,2019-03-15,2019-03-16,2019-03-17,2019-03-20,...,2020-02-16,2020-02-19,2020-02-20,2020-02-21,2020-02-22,2020-02-23,2020-02-26,2020-02-27,2020-02-28,2020-02-29
DE000A1EWWW0,279.2,289.5,290.2,294.2,288.9,293.1,288.7,290.6,291.1,295.6,...,180.62,191.5,177.08,166.92,173.0,175.7,171.94,173.88,200.8,221.0
DE0008404005,210.0,208.4,206.8,203.0,199.8,202.0,200.45,198.26,194.92,195.38,...,131.74,134.74,122.1,119.0,129.92,132.42,146.92,146.5,173.02,173.3
DE000BASF111,71.08,71.14,70.27,69.09,67.73,68.16,69.4,68.32,68.99,68.0,...,39.635,40.795,40.205,39.29,41.06,39.035,41.25,40.91,46.38,46.21
DE000BAY0017,51.84,51.62,52.06,52.34,50.12,51.59,55.11,53.34,53.77,53.91,...,47.5,50.1,49.815,48.1,50.57,48.125,48.05,48.205,56.07,56.44
DE0005190003,76.29,76.1,72.56,72.1,71.5,71.5,70.39,69.32,71.27,71.58,...,39.8,41.37,37.66,39.135,40.355,40.09,45.42,44.08,50.65,50.33

In [34]:
samples.head()

SAMPLE,SAMPLE_0,SAMPLE_1,SAMPLE_2,SAMPLE_3,SAMPLE_4,SAMPLE_5,SAMPLE_6,SAMPLE_7,SAMPLE_8,SAMPLE_9,SAMPLE_10,SAMPLE_11,SAMPLE_12,SAMPLE_13,SAMPLE_14,SAMPLE_15,SAMPLE_16,SAMPLE_17,SAMPLE_18,SAMPLE_19,SAMPLE_20,SAMPLE_21,SAMPLE_22,SAMPLE_23,SAMPLE_24,SAMPLE_25,SAMPLE_26,SAMPLE_27,SAMPLE_28,SAMPLE_29,SAMPLE_30,SAMPLE_31,SAMPLE_32,SAMPLE_33,SAMPLE_34,SAMPLE_35,SAMPLE_36,SAMPLE_37,SAMPLE_38,SAMPLE_39,SAMPLE_40,SAMPLE_41,SAMPLE_42,SAMPLE_43,SAMPLE_44,SAMPLE_45,SAMPLE_46,SAMPLE_47,SAMPLE_48,SAMPLE_49,SAMPLE_50,SAMPLE_51,SAMPLE_52,SAMPLE_53,SAMPLE_54,SAMPLE_55,SAMPLE_56,SAMPLE_57,SAMPLE_58,SAMPLE_59,SAMPLE_60,SAMPLE_61,SAMPLE_62,SAMPLE_63,SAMPLE_64,SAMPLE_65,SAMPLE_66,SAMPLE_67,SAMPLE_68,SAMPLE_69,SAMPLE_70,SAMPLE_71,SAMPLE_72,SAMPLE_73,SAMPLE_74,SAMPLE_75,SAMPLE_76,SAMPLE_77,SAMPLE_78,SAMPLE_79,SAMPLE_80,SAMPLE_81,SAMPLE_82,SAMPLE_83,SAMPLE_84,SAMPLE_85,SAMPLE_86,SAMPLE_87,SAMPLE_88,SAMPLE_89,SAMPLE_90,SAMPLE_91,SAMPLE_92,SAMPLE_93,SAMPLE_94,SAMPLE_95,SAMPLE_96,SAMPLE_97,SAMPLE_98,SAMPLE_99,...,SAMPLE_132,SAMPLE_133,SAMPLE_134,SAMPLE_135,SAMPLE_136,SAMPLE_137,SAMPLE_138,SAMPLE_139,SAMPLE_140,SAMPLE_141,SAMPLE_142,SAMPLE_143,SAMPLE_144,SAMPLE_145,SAMPLE_146,SAMPLE_147,SAMPLE_148,SAMPLE_149,SAMPLE_150,SAMPLE_151,SAMPLE_152,SAMPLE_153,SAMPLE_154,SAMPLE_155,SAMPLE_156,SAMPLE_157,SAMPLE_158,SAMPLE_159,SAMPLE_160,SAMPLE_161,SAMPLE_162,SAMPLE_163,SAMPLE_164,SAMPLE_165,SAMPLE_166,SAMPLE_167,SAMPLE_168,SAMPLE_169,SAMPLE_170,SAMPLE_171,SAMPLE_172,SAMPLE_173,SAMPLE_174,SAMPLE_175,SAMPLE_176,SAMPLE_177,SAMPLE_178,SAMPLE_179,SAMPLE_180,SAMPLE_181,SAMPLE_182,SAMPLE_183,SAMPLE_184,SAMPLE_185,SAMPLE_186,SAMPLE_187,SAMPLE_188,SAMPLE_189,SAMPLE_190,SAMPLE_191,SAMPLE_192,SAMPLE_193,SAMPLE_194,SAMPLE_195,SAMPLE_196,SAMPLE_197,SAMPLE_198,SAMPLE_199,SAMPLE_200,SAMPLE_201,SAMPLE_202,SAMPLE_203,SAMPLE_204,SAMPLE_205,SAMPLE_206,SAMPLE_207,SAMPLE_208,SAMPLE_209,SAMPLE_210,SAMPLE_211,SAMPLE_212,SAMPLE_213,SAMPLE_214,SAMPLE_215,SAMPLE_216,SAMPLE_217,SAMPLE_218,SAMPLE_219,SAMPLE_220,SAMPLE_221,SAMPLE_222,SAMPLE_223,SAMPLE_224,SAMPLE_225,SAMPLE_226,SAMPLE_227,SAMPLE_228,SAMPLE_229,SAMPLE_230,SAMPLE_231
DATE,2019-12-04,2019-12-05,2019-12-06,2019-12-09,2019-12-10,2019-12-11,2019-12-12,2019-12-13,2019-12-16,2019-12-17,2019-12-18,2019-12-19,2019-12-20,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-30,2019-12-31,2020-01-01,2020-01-02,2020-01-03,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-13,2020-01-14,2020-01-15,2020-01-16,2020-01-17,2020-01-20,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31,2020-02-03,2020-02-04,2020-02-05,2020-02-06,2020-02-07,2020-02-10,2020-02-11,2020-02-12,2020-02-13,2020-02-14,2020-02-17,2020-02-18,2020-02-19,2020-02-20,2020-02-21,2020-02-24,2020-02-25,2020-02-26,2020-02-27,2020-02-28,2020-03-02,2020-03-03,2020-03-04,2020-03-05,2020-03-06,2020-03-09,2020-03-10,2020-03-11,2020-03-12,2020-03-13,2020-03-16,2020-03-17,2020-03-18,2020-03-19,2020-03-20,2020-03-23,2020-03-24,2020-03-25,2020-03-26,2020-03-27,2020-03-30,2020-03-31,2020-04-01,2020-04-02,2020-04-03,2020-04-06,2020-04-07,2020-04-08,2020-04-09,2020-04-10,2020-04-13,2020-04-14,2020-04-15,2020-04-16,2020-04-17,2020-04-20,2020-04-21,...,2020-06-05,2020-06-08,2020-06-09,2020-06-10,2020-06-11,2020-06-15,2020-06-16,2020-06-17,2020-06-18,2020-06-19,2020-06-22,2020-06-23,2020-06-24,2020-06-25,2020-06-26,2020-06-29,2020-06-30,2020-07-01,2020-07-02,2020-07-03,2020-07-06,2020-07-07,2020-07-08,2020-07-09,2020-07-10,2020-07-13,2020-07-14,2020-07-15,2020-07-16,2020-07-17,2020-07-20,2020-07-21,2020-07-22,2020-07-23,2020-07-24,2020-07-27,2020-07-28,2020-07-29,2020-07-30,2020-08-04,2020-08-05,2020-08-06,2020-08-07,2020-08-10,2020-08-11,2020-08-12,2020-08-13,2020-08-14,2020-08-17,2020-08-18,2020-08-19,2020-08-20,2020-08-21,2020-08-24,2020-08-25,2020-08-26,2020-08-27,2020-08-28,2020-08-31,2020-09-01,2020-09-02,2020-09-03,2020-09-04,2020-09-07,2020-09-08,2020-09-09,2020-09-10,2020-09-11,2020-09-14,2020-09-15,2020-09-16,2020-09-17,2020-09-18,2020-09-21,2020-09-22,2020-09-23,2020-09-24,2020-09-25,2020-09-28,2020-09-29,2020-09-30,2020-10-01,2020-10-02,2020-10-05,2020-10-06,2020-10-07,2020-10-08,2020-10-09,2020-10-12,2020-10-13,2020-10-14,2020-10-15,2020-10-16,2020-10-19,2020-10-20,2020-10-21,2020-10-22,2020-10-23,2020-10-26,2020-10-27
DE000A1EWWW0,262.4,256.2,254.5,252.475,268.4,268.4,272.85,279.6,282.35,282.5,284.125,286.5,281.9,280.6,281.1,285.3,295.5,294.0,298.55,294.1,291.85,285.7,285.375,283.3,284.05,279.15,280.2,278.0,278.0,275.55,269.0,268.35,270.65,274.4,267.0,263.0,259.9,261.15,263.0,267.0,261.55,263.7,264.05,270.25,272.8,270.75,266.75,278.8,282.0,289.1,284.35,282.6,280.3,281.675,285.25,284.9,293.55,297.3,299.0,297.95,296.9,300.9,300.0,298.5,301.45,301.2,299.45,301.95,303.95,304.9,306.7,304.8,307.4,301.5,303.25,307.2,311.6,313.2,319.1,313.15,307.8,308.85,313.05,310.55,316.0,336.25,322.75,317.95,306.8,308.8,309.5,309.0,312.0,317.7,312.3,308.5,305.25,305.45,311.9,315.85,...,297.65,299.1,297.05,297.05,299.15,301.95,298.4,294.55,294.05,296.8,288.75,284.9,286.55,284.15,287.7,280.6,258.8,259.6,252.05,259.85,256.85,260.6,258.85,262.3,265.95,266.1,270.3,271.5,269.1,277.2,277.9,277.55,277.6,280.45,282.35,280.0,276.75,271.3,276.55,270.75,266.2,265.0,263.7,261.7,261.8,279.8,282.0,278.0,281.0,287.0,285.0,287.5,294.5,298.9,300.0,290.1,282.8,280.2,271.5,279.2,289.5,290.2,293.0,288.2,292.4,288.7,290.6,291.4,295.2,288.8,290.9,295.3,297.7,292.05,292.3,279.8,283.9,278.5,278.6,274.6,275.0,278.5,270.9,262.0,265.6,270.7,276.7,270.25,278.0,285.1,285.3,286.2,295.2,281.9,289.8,286.8,288.2,292.3,295.1,288.5
DE0008404005,198.96,192.7,192.32,191.44,202.45,203.8,203.575,203.25,202.75,204.75,205.25,205.8,205.75,205.075,205.15,205.55,203.3,203.15,203.45,201.55,203.1,202.8,202.7,201.15,200.95,201.2,201.3,198.54,199.0,198.64,199.24,199.08,198.54,198.6,196.4,195.08,197.68,198.94,198.58,198.7,195.3,197.4,194.84,195.3,194.84,195.88,193.64,196.16,192.34,191.56,191.02,187.62,183.92,190.2,192.5,192.26,192.84,194.74,193.3,194.18,196.58,197.7,198.66,196.98,197.72,199.3,198.26,198.24,199.0,198.94,200.775,200.85,199.26,198.72,198.02,199.62,198.7,200.8,201.65,202.05,201.4,201.3,199.6,197.72,192.88,190.5,192.14,193.7,210.0,211.5,210.3,210.2,211.0,210.5,208.85,207.6,203.6,201.1,208.95,210.7,...,215.45,217.75,215.65,214.1,215.35,216.5,214.95,213.55,217.4,217.65,217.35,214.65,213.65,210.9,215.175,214.15,212.7,221.5,216.75,219.9,216.4,216.6,218.05,216.35,217.45,216.275,216.05,216.2,215.6,219.1,219.05,215.45,217.25,218.6,219.3,218.75,218.8,220.0,218.35,217.2,217.05,219.55,214.6,213.25,212.35,212.55,211.85,212.0,214.75,216.15,210.1,211.45,213.5,213.9,213.8,213.45,213.65,215.3,207.65,210.0,208.4,206.8,203.0,199.75,202.0,200.75,198.26,194.92,195.38,194.86,197.86,198.98,199.35,195.73,196.68,196.3,195.08,195.58,195.7,195.96,193.14,192.32,188.26,186.52,190.92,190.3,193.23,190.48,195.28,198.24,200.25,201.0,200.75,202.15,203.2,201.1,203.0,203.375,205.75,205.75
DE000BASF111,59.27,57.93,57.93,57.86,61.62,61.98,63.01,61.93,61.61,62.66,62.735,62.9,62.21,62.66,62.35,62.0,61.73,62.125,62.0,61.53,62.5,62.07,62.97,62.265,62.56,63.53,63.73,63.32,62.89,62.86,63.48,63.885,64.07,64.95,65.22,65.01,64.47,64.12,63.71,63.35,61.86,64.56,64.67,64.61,65.87,65.87,64.97,64.72,63.7,63.92,63.48,62.27,61.66,63.1,65.21,64.785,65.57,65.55,64.48,64.63,64.96,65.2,65.31,64.81,64.94,64.62,65.52,66.87,66.5,65.98,66.3,66.61,65.22,64.78,65.37,68.01,67.77,68.14,69.155,68.75,68.08,67.48,67.36,67.08,66.97,66.57,66.68,66.31,66.305,66.85,66.41,67.07,67.54,67.02,66.56,66.49,65.57,64.33,67.01,67.4,...,66.66,67.15,66.71,66.75,67.11,67.95,67.5,67.26,69.09,69.17,69.25,68.9,69.23,68.98,70.8,70.28,70.28,69.22,66.72,67.06,67.16,70.18,70.89,71.13,71.49,70.42,70.18,71.09,70.83,71.76,72.56,71.03,70.96,71.27,71.08,71.49,71.45,72.35,72.24,71.05,70.84,71.88,70.03,69.82,70.46,69.98,69.15,69.58,69.97,72.48,70.76,70.09,70.57,72.6,72.19,72.47,71.79,72.61,70.82,71.16,71.14,70.27,69.09,67.55,68.16,69.4,68.23,68.99,68.22,67.03,67.16,67.67,67.5,66.835,67.04,67.12,67.115,67.36,66.81,66.66,66.16,65.35,64.82,63.83,64.53,63.88,65.47,64.53,66.28,67.33,67.2,66.65,67.47,67.165,68.1,68.1,67.785,67.64,68.58,68.41
DE000BAY0017,45.34,44.65,45.325,45.535,47.465,47.5025,48.93,48.29,48.18,49.31,49.9025,50.24,50.415,50.93,50.95,51.33,50.77,50.15,49.65,49.97,50.24,50.03,49.4925,48.725,48.71,48.51,48.825,48.56,48.31,48.105,48.155,47.29,46.63,48.0375,47.78,47.08,47.695,48.6775,47.8825,47.4075,46.22,46.155,46.64,46.4425,47.1,47.38,46.925,47.465,46.49,46.495,46.555,45.705,45.2,45.075,45.65,45.4725,45.83,45.91,45.745,45.56,46.615,47.38,47.74,47.49,47.69,47.26,47.01,47.145,47.31,47.33,47.76,48.0725,47.79,47.41,47.56,47.85,47.85,47.64,47.765,47.965,47.2825,47.29,47.215,47.02,46.04,49.75,50.16,50.56,50.36,51.16,50.52,50.59,51.37,51.2,51.15,51.06,50.25,49.365,50.67,50.53,...,51.48,52.28,52.255,54.97,55.29,55.92,55.72,55.77,56.33,56.77,57.12,56.96,57.3,53.28,54.37,53.99,53.78,53.49,52.31,53.47,53.82,53.15,53.45,54.25,54.91,54.51,55.69,56.0,54.14,54.96,54.13,52.88,52.9,52.98,53.05,53.34,53.36,53.51,53.78,53.23,53.92,53.78,53.37,53.21,53.21,53.65,54.14,53.39,53.4,53.8,52.81,52.91,53.04,52.95,52.43,54.46,53.05,53.17,51.48,51.84,51.62,52.06,52.34,50.02,51.59,55.0,53.34,53.94,53.9,53.11,53.98,54.55,54.94,53.9,53.965,54.09,55.19,55.32,55.8,54.03,51.465,51.26,50.48,49.915,50.93,50.09,51.93,51.43,52.36,53.0,53.66,53.01,52.56,52.09,52.69,52.59,50.34,50.98,51.5,52.32

In [41]:
ground_truth.head()

Y            GROUND_TRUE                                              \
SAMPLE          SAMPLE_0   SAMPLE_1   SAMPLE_2   SAMPLE_3   SAMPLE_4
DATE          2019-12-05 2019-12-06 2019-12-09 2019-12-10 2019-12-11
SAMPLE_OLD      SAMPLE_1   SAMPLE_2   SAMPLE_3   SAMPLE_4   SAMPLE_5
DE000A1EWWW0       256.2      254.5    252.475      268.4      268.4
DE0008404005       192.7     192.32     191.44     202.45      203.8
DE000BASF111       57.93      57.93      57.86      61.62      61.98
DE000BAY0017       44.65     45.325     45.535     47.465    47.5025

Y                                                                    \
SAMPLE         SAMPLE_5   SAMPLE_6   SAMPLE_7   SAMPLE_8   SAMPLE_9
DATE         2019-12-12 2019-12-13 2019-12-16 2019-12-17 2019-12-18
SAMPLE_OLD     SAMPLE_6   SAMPLE_7   SAMPLE_8   SAMPLE_9  SAMPLE_10
DE000A1EWWW0     272.85      279.6     282.35      282.5    284.125
DE0008404005    203.575     203.25     202.75     204.75     205.25
DE000BASF111      63.01      61.93      61.61      62.66     62.735
DE000BAY0017      48.93      48.29      48.18      49.31    49.9025

Y                                                                    \
SAMPLE        SAMPLE_10  SAMPLE_11  SAMPLE_12  SAMPLE_13  SAMPLE_14
DATE         2019-12-19 2019-12-20 2019-12-23 2019-12-24 2019-12-25
SAMPLE_OLD    SAMPLE_11  SAMPLE_12  SAMPLE_13  SAMPLE_14  SAMPLE_15
DE000A1EWWW0      286.5      281.9      280.6      281.1      285.3
DE0008404005      205.8     205.75    205.075     205.15     205.55
DE000BASF111       62.9      62.21      62.66      62.35       62.0
DE000BAY0017      50.24     50.415      50.93      50.95      51.33

Y                                                                    \
SAMPLE        SAMPLE_15  SAMPLE_16  SAMPLE_17  SAMPLE_18  SAMPLE_19
DATE         2019-12-26 2019-12-27 2019-12-30 2019-12-31 2020-01-01
SAMPLE_OLD    SAMPLE_16  SAMPLE_17  SAMPLE_18  SAMPLE_19  SAMPLE_20
DE000A1EWWW0      295.5      294.0     298.55      294.1     291.85
DE0008404005      203.3     203.15     203.45     201.55      203.1
DE000BASF111      61.73     62.125       62.0      61.53       62.5
DE000BAY0017      50.77      50.15      49.65      49.97      50.24

Y                                                                    \
SAMPLE        SAMPLE_20  SAMPLE_21  SAMPLE_22  SAMPLE_23  SAMPLE_24
DATE         2020-01-02 2020-01-03 2020-01-06 2020-01-07 2020-01-08
SAMPLE_OLD    SAMPLE_21  SAMPLE_22  SAMPLE_23  SAMPLE_24  SAMPLE_25
DE000A1EWWW0      285.7    285.375      283.3     284.05     279.15
DE0008404005      202.8      202.7     201.15     200.95      201.2
DE000BASF111      62.07      62.97     62.265      62.56      63.53
DE000BAY0017      50.03    49.4925     48.725      48.71      48.51

Y                                                                    \
SAMPLE        SAMPLE_25  SAMPLE_26  SAMPLE_27  SAMPLE_28  SAMPLE_29
DATE         2020-01-09 2020-01-10 2020-01-13 2020-01-14 2020-01-15
SAMPLE_OLD    SAMPLE_26  SAMPLE_27  SAMPLE_28  SAMPLE_29  SAMPLE_30
DE000A1EWWW0      280.2      278.0      278.0     275.55      269.0
DE0008404005      201.3     198.54      199.0     198.64     199.24
DE000BASF111      63.73      63.32      62.89      62.86      63.48
DE000BAY0017     48.825      48.56      48.31     48.105     48.155

Y                                                                    \
SAMPLE        SAMPLE_30  SAMPLE_31  SAMPLE_32  SAMPLE_33  SAMPLE_34
DATE         2020-01-16 2020-01-17 2020-01-20 2020-01-21 2020-01-22
SAMPLE_OLD    SAMPLE_31  SAMPLE_32  SAMPLE_33  SAMPLE_34  SAMPLE_35
DE000A1EWWW0     268.35     270.65      274.4      267.0      263.0
DE0008404005     199.08     198.54      198.6      196.4     195.08
DE000BASF111     63.885      64.07      64.95      65.22      65.01
DE000BAY0017      47.29      46.63    48.0375      47.78      47.08

Y                                                                    \
SAMPLE        SAMPLE_35  SAMPLE_36  SAMPLE_37  SAMPLE_38  SAMPLE_39
DATE         2020-01-23 2020-01-24 2020-01-27 2020-01-28 2020-01-29
SAMPLE_OLD    SAMPLE_36  SAMPLE_37  SAMPLE_38  SAMPLE_39  SAMPLE_40
DE000A1EWWW0      259.9     261.15      263.0      267.0     261.55
DE0008404005     197.68     198.94     198.58      198.7      195.3
DE000BASF111      64.47      64.12      63.71      63.35      61.86
DE000BAY0017     47.695    48.6775    47.8825    47.4075      46.22

Y                                                                    \
SAMPLE        SAMPLE_40  SAMPLE_41  SAMPLE_42  SAMPLE_43  SAMPLE_44
DATE         2020-01-30 2020-01-31 2020-02-03 2020-02-04 2020-02-05
SAMPLE_OLD    SAMPLE_41  SAMPLE_42  SAMPLE_43  SAMPLE_44  SAMPLE_45
DE000A1EWWW0      263.7     264.05     270.25      272.8     270.75
DE0008404005      197.4     194.84      195.3     194.84     195.88
DE000BASF111      64.56      64.67      64.61      65.87      65.87
DE000BAY0017     46.155      46.64    46.4425       47.1      47.38

Y                                                                    \
SAMPLE        SAMPLE_45  SAMPLE_46  SAMPLE_47  SAMPLE_48  SAMPLE_49
DATE         2020-02-06 2020-02-07 2020-02-10 2020-02-11 2020-02-12
SAMPLE_OLD    SAMPLE_46  SAMPLE_47  SAMPLE_48  SAMPLE_49  SAMPLE_50
DE000A1EWWW0     266.75      278.8      282.0      289.1     284.35
DE0008404005     193.64     196.16     192.34     191.56     191.02
DE000BASF111      64.97      64.72       63.7      63.92      63.48
DE000BAY0017     46.925     47.465      46.49     46.495     46.555

Y                                                                    \
SAMPLE        SAMPLE_50  SAMPLE_51  SAMPLE_52  SAMPLE_53  SAMPLE_54
DATE         2020-02-13 2020-02-14 2020-02-17 2020-02-18 2020-02-19
SAMPLE_OLD    SAMPLE_51  SAMPLE_52  SAMPLE_53  SAMPLE_54  SAMPLE_55
DE000A1EWWW0      282.6      280.3    281.675     285.25      284.9
DE0008404005     187.62     183.92      190.2      192.5     192.26
DE000BASF111      62.27      61.66       63.1      65.21     64.785
DE000BAY0017     45.705       45.2     45.075      45.65    45.4725

Y                                                                    \
SAMPLE        SAMPLE_55  SAMPLE_56  SAMPLE_57  SAMPLE_58  SAMPLE_59
DATE         2020-02-20 2020-02-21 2020-02-24 2020-02-25 2020-02-26
SAMPLE_OLD    SAMPLE_56  SAMPLE_57  SAMPLE_58  SAMPLE_59  SAMPLE_60
DE000A1EWWW0     293.55      297.3      299.0     297.95      296.9
DE0008404005     192.84     194.74      193.3     194.18     196.58
DE000BASF111      65.57      65.55      64.48      64.63      64.96
DE000BAY0017      45.83      45.91     45.745      45.56     46.615

Y                                                                    \
SAMPLE        SAMPLE_60  SAMPLE_61  SAMPLE_62  SAMPLE_63  SAMPLE_64
DATE         2020-02-27 2020-02-28 2020-03-02 2020-03-03 2020-03-04
SAMPLE_OLD    SAMPLE_61  SAMPLE_62  SAMPLE_63  SAMPLE_64  SAMPLE_65
DE000A1EWWW0      300.9      300.0      298.5     301.45      301.2
DE0008404005      197.7     198.66     196.98     197.72      199.3
DE000BASF111       65.2      65.31      64.81      64.94      64.62
DE000BAY0017      47.38      47.74      47.49      47.69      47.26

Y                                                                    \
SAMPLE        SAMPLE_65  SAMPLE_66  SAMPLE_67  SAMPLE_68  SAMPLE_69
DATE         2020-03-05 2020-03-06 2020-03-09 2020-03-10 2020-03-11
SAMPLE_OLD    SAMPLE_66  SAMPLE_67  SAMPLE_68  SAMPLE_69  SAMPLE_70
DE000A1EWWW0     299.45     301.95     303.95      304.9      306.7
DE0008404005     198.26     198.24      199.0     198.94    200.775
DE000BASF111      65.52      66.87       66.5      65.98       66.3
DE000BAY0017      47.01     47.145      47.31      47.33      47.76

Y                                                                    \
SAMPLE        SAMPLE_70  SAMPLE_71  SAMPLE_72  SAMPLE_73  SAMPLE_74
DATE         2020-03-12 2020-03-13 2020-03-16 2020-03-17 2020-03-18
SAMPLE_OLD    SAMPLE_71  SAMPLE_72  SAMPLE_73  SAMPLE_74  SAMPLE_75
DE000A1EWWW0      304.8      307.4      301.5     303.25      307.2
DE0008404005     200.85     199.26     198.72     198.02     199.62
DE000BASF111      66.61      65.22      64.78      65.37      68.01
DE000BAY0017    48.0725      47.79      47.41      47.56      47.85

Y                                                                    \
SAMPLE        SAMPLE_75  SAMPLE_76  SAMPLE_77  SAMPLE_78  SAMPLE_79
DATE         2020-03-19 2020-03-20 2020-03-23 2020-03-24 2020-03-25
SAMPLE_OLD    SAMPLE_76  SAMPLE_77  SAMPLE_78  SAMPLE_79  SAMPLE_80
DE000A1EWWW0      311.6      313.2      319.1     313.15      307.8
DE0008404005      198.7      200.8     201.65     202.05      201.4
DE000BASF111      67.77      68.14     69.155      68.75      68.08
DE000BAY0017      47.85      47.64     47.765     47.965    47.2825

Y                                                                    \
SAMPLE        SAMPLE_80  SAMPLE_81  SAMPLE_82  SAMPLE_83  SAMPLE_84
DATE         2020-03-26 2020-03-27 2020-03-30 2020-03-31 2020-04-01
SAMPLE_OLD    SAMPLE_81  SAMPLE_82  SAMPLE_83  SAMPLE_84  SAMPLE_85
DE000A1EWWW0     308.85     313.05     310.55      316.0     336.25
DE0008404005      201.3      199.6     197.72     192.88      190.5
DE000BASF111      67.48      67.36      67.08      66.97      66.57
DE000BAY0017      47.29     47.215      47.02      46.04      49.75

Y                                                                    \
SAMPLE        SAMPLE_85  SAMPLE_86  SAMPLE_87  SAMPLE_88  SAMPLE_89
DATE         2020-04-02 2020-04-03 2020-04-06 2020-04-07 2020-04-08
SAMPLE_OLD    SAMPLE_86  SAMPLE_87  SAMPLE_88  SAMPLE_89  SAMPLE_90
DE000A1EWWW0     322.75     317.95      306.8      308.8      309.5
DE0008404005     192.14      193.7      210.0      211.5      210.3
DE000BASF111      66.68      66.31     66.305      66.85      66.41
DE000BAY0017      50.16      50.56      50.36      51.16      50.52

Y                                                                    \
SAMPLE        SAMPLE_90  SAMPLE_91  SAMPLE_92  SAMPLE_93  SAMPLE_94
DATE         2020-04-09 2020-04-10 2020-04-13 2020-04-14 2020-04-15
SAMPLE_OLD    SAMPLE_91  SAMPLE_92  SAMPLE_93  SAMPLE_94  SAMPLE_95
DE000A1EWWW0      309.0      312.0      317.7      312.3      308.5
DE0008404005      210.2      211.0      210.5     208.85      207.6
DE000BASF111      67.07      67.54      67.02      66.56      66.49
DE000BAY0017      50.59      51.37       51.2      51.15      51.06

Y                                                                     ...  \
SAMPLE        SAMPLE_95  SAMPLE_96  SAMPLE_97  SAMPLE_98   SAMPLE_99  ...
DATE         2020-04-16 2020-04-17 2020-04-20 2020-04-21  2020-04-22  ...
SAMPLE_OLD    SAMPLE_96  SAMPLE_97  SAMPLE_98  SAMPLE_99  SAMPLE_100  ...
DE000A1EWWW0     305.25     305.45      311.9     315.85       322.7  ...
DE0008404005      203.6      201.1     208.95      210.7       211.2  ...
DE000BASF111      65.57      64.33      67.01       67.4       67.92  ...
DE000BAY0017      50.25     49.365      50.67      50.53        51.0  ...

Y                                                                         \
SAMPLE        SAMPLE_132  SAMPLE_133  SAMPLE_134  SAMPLE_135  SAMPLE_136
DATE          2020-06-08  2020-06-09  2020-06-10  2020-06-11  2020-06-15
SAMPLE_OLD    SAMPLE_133  SAMPLE_134  SAMPLE_135  SAMPLE_136  SAMPLE_137
DE000A1EWWW0       299.1      297.05      297.05      299.15      301.95
DE0008404005      217.75      215.65       214.1      215.35       216.5
DE000BASF111       67.15       66.71       66.75       67.11       67.95
DE000BAY0017       52.28      52.255       54.97       55.29       55.92

Y                                                                         \
SAMPLE        SAMPLE_137  SAMPLE_138  SAMPLE_139  SAMPLE_140  SAMPLE_141
DATE          2020-06-16  2020-06-17  2020-06-18  2020-06-19  2020-06-22
SAMPLE_OLD    SAMPLE_138  SAMPLE_139  SAMPLE_140  SAMPLE_141  SAMPLE_142
DE000A1EWWW0       298.4      294.55      294.05       296.8      288.75
DE0008404005      214.95      213.55       217.4      217.65      217.35
DE000BASF111        67.5       67.26       69.09       69.17       69.25
DE000BAY0017       55.72       55.77       56.33       56.77       57.12

Y                                                                         \
SAMPLE        SAMPLE_142  SAMPLE_143  SAMPLE_144  SAMPLE_145  SAMPLE_146
DATE          2020-06-23  2020-06-24  2020-06-25  2020-06-26  2020-06-29
SAMPLE_OLD    SAMPLE_143  SAMPLE_144  SAMPLE_145  SAMPLE_146  SAMPLE_147
DE000A1EWWW0       284.9      286.55      284.15       287.7       280.6
DE0008404005      214.65      213.65       210.9     215.175      214.15
DE000BASF111        68.9       69.23       68.98        70.8       70.28
DE000BAY0017       56.96        57.3       53.28       54.37       53.99

Y                                                                         \
SAMPLE        SAMPLE_147  SAMPLE_148  SAMPLE_149  SAMPLE_150  SAMPLE_151
DATE          2020-06-30  2020-07-01  2020-07-02  2020-07-03  2020-07-06
SAMPLE_OLD    SAMPLE_148  SAMPLE_149  SAMPLE_150  SAMPLE_151  SAMPLE_152
DE000A1EWWW0       258.8       259.6      252.05      259.85      256.85
DE0008404005       212.7       221.5      216.75       219.9       216.4
DE000BASF111       70.28       69.22       66.72       67.06       67.16
DE000BAY0017       53.78       53.49       52.31       53.47       53.82

Y                                                                         \
SAMPLE        SAMPLE_152  SAMPLE_153  SAMPLE_154  SAMPLE_155  SAMPLE_156
DATE          2020-07-07  2020-07-08  2020-07-09  2020-07-10  2020-07-13
SAMPLE_OLD    SAMPLE_153  SAMPLE_154  SAMPLE_155  SAMPLE_156  SAMPLE_157
DE000A1EWWW0       260.6      258.85       262.3      265.95       266.1
DE0008404005       216.6      218.05      216.35      217.45     216.275
DE000BASF111       70.18       70.89       71.13       71.49       70.42
DE000BAY0017       53.15       53.45       54.25       54.91       54.51

Y                                                                         \
SAMPLE        SAMPLE_157  SAMPLE_158  SAMPLE_159  SAMPLE_160  SAMPLE_161
DATE          2020-07-14  2020-07-15  2020-07-16  2020-07-17  2020-07-20
SAMPLE_OLD    SAMPLE_158  SAMPLE_159  SAMPLE_160  SAMPLE_161  SAMPLE_162
DE000A1EWWW0       270.3       271.5       269.1       277.2       277.9
DE0008404005      216.05       216.2       215.6       219.1      219.05
DE000BASF111       70.18       71.09       70.83       71.76       72.56
DE000BAY0017       55.69        56.0       54.14       54.96       54.13

Y                                                                         \
SAMPLE        SAMPLE_162  SAMPLE_163  SAMPLE_164  SAMPLE_165  SAMPLE_166
DATE          2020-07-21  2020-07-22  2020-07-23  2020-07-24  2020-07-27
SAMPLE_OLD    SAMPLE_163  SAMPLE_164  SAMPLE_165  SAMPLE_166  SAMPLE_167
DE000A1EWWW0      277.55       277.6      280.45      282.35       280.0
DE0008404005      215.45      217.25       218.6       219.3      218.75
DE000BASF111       71.03       70.96       71.27       71.08       71.49
DE000BAY0017       52.88        52.9       52.98       53.05       53.34

Y                                                                         \
SAMPLE        SAMPLE_167  SAMPLE_168  SAMPLE_169  SAMPLE_170  SAMPLE_171
DATE          2020-07-28  2020-07-29  2020-07-30  2020-08-04  2020-08-05
SAMPLE_OLD    SAMPLE_168  SAMPLE_169  SAMPLE_170  SAMPLE_171  SAMPLE_172
DE000A1EWWW0      276.75       271.3      276.55      270.75       266.2
DE0008404005       218.8       220.0      218.35       217.2      217.05
DE000BASF111       71.45       72.35       72.24       71.05       70.84
DE000BAY0017       53.36       53.51       53.78       53.23       53.92

Y                                                                         \
SAMPLE        SAMPLE_172  SAMPLE_173  SAMPLE_174  SAMPLE_175  SAMPLE_176
DATE          2020-08-06  2020-08-07  2020-08-10  2020-08-11  2020-08-12
SAMPLE_OLD    SAMPLE_173  SAMPLE_174  SAMPLE_175  SAMPLE_176  SAMPLE_177
DE000A1EWWW0       265.0       263.7       261.7       261.8       279.8
DE0008404005      219.55       214.6      213.25      212.35      212.55
DE000BASF111       71.88       70.03       69.82       70.46       69.98
DE000BAY0017       53.78       53.37       53.21       53.21       53.65

Y                                                                         \
SAMPLE        SAMPLE_177  SAMPLE_178  SAMPLE_179  SAMPLE_180  SAMPLE_181
DATE          2020-08-13  2020-08-14  2020-08-17  2020-08-18  2020-08-19
SAMPLE_OLD    SAMPLE_178  SAMPLE_179  SAMPLE_180  SAMPLE_181  SAMPLE_182
DE000A1EWWW0       282.0       278.0       281.0       287.0       285.0
DE0008404005      211.85       212.0      214.75      216.15       210.1
DE000BASF111       69.15       69.58       69.97       72.48       70.76
DE000BAY0017       54.14       53.39        53.4        53.8       52.81

Y                                                                         \
SAMPLE        SAMPLE_182  SAMPLE_183  SAMPLE_184  SAMPLE_185  SAMPLE_186
DATE          2020-08-20  2020-08-21  2020-08-24  2020-08-25  2020-08-26
SAMPLE_OLD    SAMPLE_183  SAMPLE_184  SAMPLE_185  SAMPLE_186  SAMPLE_187
DE000A1EWWW0       287.5       294.5       298.9       300.0       290.1
DE0008404005      211.45       213.5       213.9       213.8      213.45
DE000BASF111       70.09       70.57        72.6       72.19       72.47
DE000BAY0017       52.91       53.04       52.95       52.43       54.46

Y                                                                         \
SAMPLE        SAMPLE_187  SAMPLE_188  SAMPLE_189  SAMPLE_190  SAMPLE_191
DATE          2020-08-27  2020-08-28  2020-08-31  2020-09-01  2020-09-02
SAMPLE_OLD    SAMPLE_188  SAMPLE_189  SAMPLE_190  SAMPLE_191  SAMPLE_192
DE000A1EWWW0       282.8       280.2       271.5       279.2       289.5
DE0008404005      213.65       215.3      207.65       210.0       208.4
DE000BASF111       71.79       72.61       70.82       71.16       71.14
DE000BAY0017       53.05       53.17       51.48       51.84       51.62

Y                                                                         \
SAMPLE        SAMPLE_192  SAMPLE_193  SAMPLE_194  SAMPLE_195  SAMPLE_196
DATE          2020-09-03  2020-09-04  2020-09-07  2020-09-08  2020-09-09
SAMPLE_OLD    SAMPLE_193  SAMPLE_194  SAMPLE_195  SAMPLE_196  SAMPLE_197
DE000A1EWWW0       290.2       293.0       288.2       292.4       288.7
DE0008404005       206.8       203.0      199.75       202.0      200.75
DE000BASF111       70.27       69.09       67.55       68.16        69.4
DE000BAY0017       52.06       52.34       50.02       51.59        55.0

Y                                                                         \
SAMPLE        SAMPLE_197  SAMPLE_198  SAMPLE_199  SAMPLE_200  SAMPLE_201
DATE          2020-09-10  2020-09-11  2020-09-14  2020-09-15  2020-09-16
SAMPLE_OLD    SAMPLE_198  SAMPLE_199  SAMPLE_200  SAMPLE_201  SAMPLE_202
DE000A1EWWW0       290.6       291.4       295.2       288.8       290.9
DE0008404005      198.26      194.92      195.38      194.86      197.86
DE000BASF111       68.23       68.99       68.22       67.03       67.16
DE000BAY0017       53.34       53.94        53.9       53.11       53.98

Y                                                                         \
SAMPLE        SAMPLE_202  SAMPLE_203  SAMPLE_204  SAMPLE_205  SAMPLE_206
DATE          2020-09-17  2020-09-18  2020-09-21  2020-09-22  2020-09-23
SAMPLE_OLD    SAMPLE_203  SAMPLE_204  SAMPLE_205  SAMPLE_206  SAMPLE_207
DE000A1EWWW0       295.3       297.7      292.05       292.3       279.8
DE0008404005      198.98      199.35      195.73      196.68       196.3
DE000BASF111       67.67        67.5      66.835       67.04       67.12
DE000BAY0017       54.55       54.94        53.9      53.965       54.09

Y                                                                         \
SAMPLE        SAMPLE_207  SAMPLE_208  SAMPLE_209  SAMPLE_210  SAMPLE_211

In [42]:
ground_prediction.head()

SAMPLE,SAMPLE_0,SAMPLE_1,SAMPLE_2,SAMPLE_3,SAMPLE_4,SAMPLE_5,SAMPLE_6,SAMPLE_7,SAMPLE_8,SAMPLE_9,SAMPLE_10,SAMPLE_11,SAMPLE_12,SAMPLE_13,SAMPLE_14,SAMPLE_15,SAMPLE_16,SAMPLE_17,SAMPLE_18,SAMPLE_19,SAMPLE_20,SAMPLE_21,SAMPLE_22,SAMPLE_23,SAMPLE_24,SAMPLE_25,SAMPLE_26,SAMPLE_27,SAMPLE_28,SAMPLE_29,SAMPLE_30,SAMPLE_31,SAMPLE_32,SAMPLE_33,SAMPLE_34,SAMPLE_35,SAMPLE_36,SAMPLE_37,SAMPLE_38,SAMPLE_39,SAMPLE_40,SAMPLE_41,SAMPLE_42,SAMPLE_43,SAMPLE_44,SAMPLE_45,SAMPLE_46,SAMPLE_47,SAMPLE_48,SAMPLE_49,SAMPLE_50,SAMPLE_51,SAMPLE_52,SAMPLE_53,SAMPLE_54,SAMPLE_55,SAMPLE_56,SAMPLE_57,SAMPLE_58,SAMPLE_59,SAMPLE_60,SAMPLE_61,SAMPLE_62,SAMPLE_63,SAMPLE_64,SAMPLE_65,SAMPLE_66,SAMPLE_67,SAMPLE_68,SAMPLE_69,SAMPLE_70,SAMPLE_71,SAMPLE_72,SAMPLE_73,SAMPLE_74,SAMPLE_75,SAMPLE_76,SAMPLE_77,SAMPLE_78,SAMPLE_79,SAMPLE_80,SAMPLE_81,SAMPLE_82,SAMPLE_83,SAMPLE_84,SAMPLE_85,SAMPLE_86,SAMPLE_87,SAMPLE_88,SAMPLE_89,SAMPLE_90,SAMPLE_91,SAMPLE_92,SAMPLE_93,SAMPLE_94,SAMPLE_95,SAMPLE_96,SAMPLE_97,SAMPLE_98,SAMPLE_99,...,SAMPLE_132,SAMPLE_133,SAMPLE_134,SAMPLE_135,SAMPLE_136,SAMPLE_137,SAMPLE_138,SAMPLE_139,SAMPLE_140,SAMPLE_141,SAMPLE_142,SAMPLE_143,SAMPLE_144,SAMPLE_145,SAMPLE_146,SAMPLE_147,SAMPLE_148,SAMPLE_149,SAMPLE_150,SAMPLE_151,SAMPLE_152,SAMPLE_153,SAMPLE_154,SAMPLE_155,SAMPLE_156,SAMPLE_157,SAMPLE_158,SAMPLE_159,SAMPLE_160,SAMPLE_161,SAMPLE_162,SAMPLE_163,SAMPLE_164,SAMPLE_165,SAMPLE_166,SAMPLE_167,SAMPLE_168,SAMPLE_169,SAMPLE_170,SAMPLE_171,SAMPLE_172,SAMPLE_173,SAMPLE_174,SAMPLE_175,SAMPLE_176,SAMPLE_177,SAMPLE_178,SAMPLE_179,SAMPLE_180,SAMPLE_181,SAMPLE_182,SAMPLE_183,SAMPLE_184,SAMPLE_185,SAMPLE_186,SAMPLE_187,SAMPLE_188,SAMPLE_189,SAMPLE_190,SAMPLE_191,SAMPLE_192,SAMPLE_193,SAMPLE_194,SAMPLE_195,SAMPLE_196,SAMPLE_197,SAMPLE_198,SAMPLE_199,SAMPLE_200,SAMPLE_201,SAMPLE_202,SAMPLE_203,SAMPLE_204,SAMPLE_205,SAMPLE_206,SAMPLE_207,SAMPLE_208,SAMPLE_209,SAMPLE_210,SAMPLE_211,SAMPLE_212,SAMPLE_213,SAMPLE_214,SAMPLE_215,SAMPLE_216,SAMPLE_217,SAMPLE_218,SAMPLE_219,SAMPLE_220,SAMPLE_221,SAMPLE_222,SAMPLE_223,SAMPLE_224,SAMPLE_225,SAMPLE_226,SAMPLE_227,SAMPLE_228,SAMPLE_229,SAMPLE_230,SAMPLE_231
DATE,2019-12-05,2019-12-06,2019-12-09,2019-12-10,2019-12-11,2019-12-12,2019-12-13,2019-12-16,2019-12-17,2019-12-18,2019-12-19,2019-12-20,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-30,2019-12-31,2020-01-01,2020-01-02,2020-01-03,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-13,2020-01-14,2020-01-15,2020-01-16,2020-01-17,2020-01-20,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31,2020-02-03,2020-02-04,2020-02-05,2020-02-06,2020-02-07,2020-02-10,2020-02-11,2020-02-12,2020-02-13,2020-02-14,2020-02-17,2020-02-18,2020-02-19,2020-02-20,2020-02-21,2020-02-24,2020-02-25,2020-02-26,2020-02-27,2020-02-28,2020-03-02,2020-03-03,2020-03-04,2020-03-05,2020-03-06,2020-03-09,2020-03-10,2020-03-11,2020-03-12,2020-03-13,2020-03-16,2020-03-17,2020-03-18,2020-03-19,2020-03-20,2020-03-23,2020-03-24,2020-03-25,2020-03-26,2020-03-27,2020-03-30,2020-03-31,2020-04-01,2020-04-02,2020-04-03,2020-04-06,2020-04-07,2020-04-08,2020-04-09,2020-04-10,2020-04-13,2020-04-14,2020-04-15,2020-04-16,2020-04-17,2020-04-20,2020-04-21,2020-04-22,...,2020-06-08,2020-06-09,2020-06-10,2020-06-11,2020-06-15,2020-06-16,2020-06-17,2020-06-18,2020-06-19,2020-06-22,2020-06-23,2020-06-24,2020-06-25,2020-06-26,2020-06-29,2020-06-30,2020-07-01,2020-07-02,2020-07-03,2020-07-06,2020-07-07,2020-07-08,2020-07-09,2020-07-10,2020-07-13,2020-07-14,2020-07-15,2020-07-16,2020-07-17,2020-07-20,2020-07-21,2020-07-22,2020-07-23,2020-07-24,2020-07-27,2020-07-28,2020-07-29,2020-07-30,2020-08-04,2020-08-05,2020-08-06,2020-08-07,2020-08-10,2020-08-11,2020-08-12,2020-08-13,2020-08-14,2020-08-17,2020-08-18,2020-08-19,2020-08-20,2020-08-21,2020-08-24,2020-08-25,2020-08-26,2020-08-27,2020-08-28,2020-08-31,2020-09-01,2020-09-02,2020-09-03,2020-09-04,2020-09-07,2020-09-08,2020-09-09,2020-09-10,2020-09-11,2020-09-14,2020-09-15,2020-09-16,2020-09-17,2020-09-18,2020-09-21,2020-09-22,2020-09-23,2020-09-24,2020-09-25,2020-09-28,2020-09-29,2020-09-30,2020-10-01,2020-10-02,2020-10-05,2020-10-06,2020-10-07,2020-10-08,2020-10-09,2020-10-12,2020-10-13,2020-10-14,2020-10-15,2020-10-16,2020-10-19,2020-10-20,2020-10-21,2020-10-22,2020-10-23,2020-10-26,2020-10-27,2020-10-28
DE000A1EWWW0,263.486359,258.249939,256.889252,255.313843,268.910645,268.910645,273.114166,279.696655,282.424011,282.573242,284.191986,286.562164,281.976562,280.68631,281.182129,285.364258,295.501526,294.023315,298.482971,294.12207,291.89386,285.763519,285.439087,283.36972,284.117218,279.252228,280.290131,278.119415,278.119415,275.722778,269.469421,268.864197,271.01944,274.607086,267.617554,264.014221,261.325562,262.39801,264.014221,267.617554,262.744598,264.634399,264.946198,270.641937,273.066223,271.113983,267.388306,278.906982,282.075989,289.156921,284.416382,282.67276,280.38913,281.752991,285.314362,284.965057,293.578583,297.265381,298.919708,297.899353,296.874451,300.753479,299.886963,298.434387,301.281036,301.041443,299.35553,301.759308,303.658936,304.553345,306.233063,304.459442,306.880768,301.328918,302.996582,306.696014,310.697876,312.119019,317.190155,312.07489,307.249481,308.21225,311.986603,309.755096,314.559631,330.299988,320.187378,316.223267,306.325775,308.166565,308.804535,308.349182,311.054901,316.011688,311.32193,307.892151,304.8815,305.068695,310.965759,314.43042,...,297.606964,299.016632,297.021118,297.021118,299.065094,301.759308,298.337219,294.566132,294.072693,296.776611,288.807861,284.965057,286.612091,284.216919,287.760132,280.68631,260.395416,261.070587,254.989639,261.28299,258.779144,261.924133,260.437408,263.398712,266.658142,266.794647,270.689087,271.825165,269.562805,277.334137,278.021118,277.677399,277.726471,280.537689,282.424011,280.092194,276.893524,271.635162,276.697968,271.113983,266.885742,265.798187,264.634399,262.874969,262.962006,279.894348,282.075989,278.119415,281.082916,287.061371,285.06485,287.560516,294.516815,298.822723,299.886963,290.153473,282.871796,280.290131,271.825165,279.301575,289.555664,290.253052,293.034271,288.259155,292.439667,288.757996,290.651245,291.446838,295.206421,288.857727,290.949738,295.30484,297.655701,292.092407,292.340454,279.894348,283.967651,278.611389,278.7099,274.800629,275.188385,278.611389,271.255951,263.136414,266.340424,271.066711,276.844635,270.641937,278.119415,285.164642,285.364258,286.262665,295.206421,281.976562,289.854614,286.861694,288.259155,292.340454,295.108002,288.558472
DE0008404005,198.792038,193.169998,192.855789,192.142075,202.190857,203.532715,203.308426,202.984848,202.488144,204.481781,204.982208,205.53302,205.482941,204.807007,204.88208,205.282623,203.034592,202.885391,203.183914,201.302902,202.835693,202.53775,202.438553,200.910431,200.714752,200.959412,201.057434,198.392761,198.8302,198.487595,199.059601,198.906586,198.392761,198.449646,196.401642,195.215012,197.583435,198.772964,198.430679,198.544571,195.410355,197.322495,195.003082,195.410355,195.003082,195.930069,193.962219,196.18335,192.872238,192.238235,191.808472,189.285004,186.918991,191.170624,193.004181,192.806519,193.286652,194.915131,193.673248,194.426636,196.566055,197.602127,198.506577,196.933563,197.620819,199.117081,198.128006,198.109131,198.8302,198.772964,200.543869,200.617065,199.078751,198.563568,197.902023,199.424393,198.544571,200.568268,201.401245,201.795441,201.155563,201.057434,199.405151,197.620819,193.320068,191.401886,192.708206,194.013489,209.719101,211.190414,210.014786,209.91629,210.702026,210.211533,208.580154,207.334442,203.333328,200.861481,208.679504,210.407974,...,214.95607,217.056274,215.141663,213.689636,214.863068,215.924255,214.489761,213.167175,216.741638,216.966583,216.696548,214.208405,213.262436,210.604095,214.700012,213.736938,212.35289,220.30687,216.152496,218.947586,215.832718,216.015656,217.324509,215.78688,216.786713,215.718079,215.5112,215.6492,215.095306,218.25235,218.208557,214.95607,216.606232,217.812653,218.427109,217.944977,217.988998,219.033783,217.591339,216.561035,216.425171,218.644684,214.161392,212.880707,212.01532,212.208389,211.53093,211.676498,214.302322,215.603226,209.817734,211.141678,213.119492,213.500061,213.405106,213.071793,213.262436,214.816528,207.384384,209.719101,208.132462,206.534424,202.736313,199.549606,201.746094,200.519485,198.128006,195.073593,195.481644,195.020691,197.751862,198.811111,199.165009,195.795013,196.657669,196.310547,195.215012,195.6604,195.768051,196.002274,193.538208,192.855789,189.735138,188.5392,191.729721,191.247437,193.61409,191.386398,195.392563,198.109131,200.033127,200.763641,200.519485,201.89418,202.93512,200.861481,202.736313,203.109238,205.482941,205.482941
DE000BASF111,59.934155,58.913898,58.913898,58.863228,61.923618,62.24651,63.190086,62.201427,61.914707,62.866508,62.935612,63.088097,62.454823,62.866508,62.58234,62.264565,62.021851,62.377663,62.264565,61.843533,62.71954,62.327843,63.152969,62.504856,62.774578,63.675468,63.863415,63.478844,63.078838,63.051075,63.628582,64.009491,64.184265,65.020432,65.278015,65.077644,64.563507,64.231575,63.844593,63.506886,62.138435,64.649055,64.7537,64.696609,65.898682,65.898682,65.039505,64.801292,63.835186,64.042519,63.628582,62.509407,61.959293,63.273724,65.268471,64.86319,65.612206,65.593102,64.573013,64.715637,65.029968,65.258926,65.36393,64.887009,65.010895,64.706123,65.564453,66.851128,66.499428,66.003685,66.308922,66.604103,65.278015,64.858429,65.421211,67.9254,67.700699,68.046722,68.983192,68.611984,67.990768,67.428055,67.314903,67.050209,66.945984,66.566048,66.670662,66.318451,66.313683,66.832153,66.413727,67.040733,67.484558,66.99337,66.556534,66.489914,65.612206,64.430588,66.983894,67.352638,...,66.651649,67.116463,66.699181,66.737183,67.078606,67.869316,67.446892,67.220474,68.923859,68.996872,69.069756,68.749878,69.051544,68.823227,70.450653,69.994362,69.994362,69.042442,66.708679,67.031265,67.125923,69.905769,70.528854,70.736259,71.044182,70.117935,69.905769,70.701805,70.476746,71.272545,71.935806,70.65004,70.589516,70.856461,70.693184,71.044182,71.010155,71.763672,71.672951,70.667305,70.485435,71.373322,69.772392,69.584686,70.153152,69.727806,68.978638,69.36882,69.71888,71.870399,70.415817,69.825813,70.249756,71.968437,71.631577,71.862213,71.297783,71.976578,70.468048,70.762062,70.744858,69.985519,68.923859,67.493973,68.065369,69.206009,68.130554,68.832382,68.121246,67.002846,67.125923,67.606819,67.446892,66.817909,67.012321,67.088074,67.083344,67.314903,66.794174,66.651649,66.17543,65.402115,64.89653,63.957619,64.620529,64.004776,65.516708,64.620529,66.289856,67.286583,67.163757,66.642136,67.418633,67.130653,68.00943,68.00943,67.714775,67.578629,68.455162,68.297775
DE000BAY0017,45.610924,45.070446,45.598759,45.770695,47.496304,47.532059,48.937229,48.297787,48.18927,49.322132,49.927345,50.27367,50.453423,50.982105,51.002609,51.391396,50.817982,50.181259,49.66885,49.996552,50.27367,50.058098,49.508011,48.731049,48.716011,48.516132,48.831482,48.565983,48.317566,48.115547,48.164669,47.33041,46.720184,48.049385,47.798763,47.133507,47.716682,48.683445,47.898182,47.44162,46.354778,46.297894,46.729237,46.551693,47.152153,47.415527,46.989769,47.496304,46.594162,46.59864,46.652515,45.912395,45.498085,45.398682,45.866306,45.719162,46.017986,46.086174,45.946056,45.791393,46.706623,47.415527,47.760098,47.520134,47.711864,47.302132,47.06842,47.194191,47.349289,47.368187,47.779423,48.083668,47.808445,47.443993,47.587017,47.866608,47.866608,47.66375,47.784256,47.978535,47.323334,47.33041,47.259808,47.077702,46.197979,49.771141,50.191525,50.602364,50.396927,51.217663,50.561279,50.633179,51.432217,51.258575,51.207436,51.115311,50.283943,49.37809,50.715328,50.571552,...,51.544357,52.353001,52.327953,54.920494,55.205284,55.751198,55.580048,55.623024,56.095688,56.45573,56.734936,56.608093,56.876038,53.339672,54.373474,54.018642,53.819916,53.542549,52.383038,53.5233,53.85791,53.213268,53.504036,54.2621,54.866547,54.502594,55.554203,55.819092,54.159454,54.911514,54.150097,52.948849,52.968521,53.047073,53.115627,53.397804,53.417152,53.561787,53.819916,53.29113,53.952606,53.819916,53.426823,53.271683,53.271683,53.695992,54.159454,53.446148,53.455807,53.838921,52.879898,52.978348,53.105843,53.017639,52.502945,54.456581,53.115627,53.232754,51.544357,51.909916,51.686802,52.13203,52.413052,50.04784,51.656303,54.947403,53.397804,53.971493,53.933701,53.174252,54.00922,54.539318,54.893539,53.933701,53.995083,54.112625,55.116821,55.231728,55.64875,54.056286,51.529076,51.319904,50.520191,49.940159,50.982105,50.119667,52.000912,51.493408,52.433044,53.066677,53.705547,53.076473,52.632385,52.162231,52.761333,52.662189,50.376381,51.033356,51.564728,52.393044

In [40]:
ts_dax[["DE000A1EWWW0", "DE0008404005", "DE000BASF111", "DE000BAY0017"]].T.head()

DATE,2019-12-04,2019-12-05,2019-12-06,2019-12-09,2019-12-10,2019-12-11,2019-12-12,2019-12-13,2019-12-16,2019-12-17,2019-12-18,2019-12-19,2019-12-20,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-30,2019-12-31,2020-01-01,2020-01-02,2020-01-03,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-13,2020-01-14,2020-01-15,2020-01-16,2020-01-17,2020-01-20,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31,2020-02-03,2020-02-04,2020-02-05,2020-02-06,2020-02-07,2020-02-10,2020-02-11,2020-02-12,2020-02-13,2020-02-14,2020-02-17,2020-02-18,2020-02-19,2020-02-20,2020-02-21,2020-02-24,2020-02-25,2020-02-26,2020-02-27,2020-02-28,2020-03-02,2020-03-03,2020-03-04,2020-03-05,2020-03-06,2020-03-09,2020-03-10,2020-03-11,2020-03-12,2020-03-13,2020-03-16,2020-03-17,2020-03-18,2020-03-19,2020-03-20,2020-03-23,2020-03-24,2020-03-25,2020-03-26,2020-03-27,2020-03-30,2020-03-31,2020-04-01,2020-04-02,2020-04-03,2020-04-06,2020-04-07,2020-04-08,2020-04-09,2020-04-10,2020-04-13,2020-04-14,2020-04-15,2020-04-16,2020-04-17,2020-04-20,2020-04-21,...,2020-06-10,2020-06-11,2020-06-15,2020-06-16,2020-06-17,2020-06-18,2020-06-19,2020-06-22,2020-06-23,2020-06-24,2020-06-25,2020-06-26,2020-06-29,2020-06-30,2020-07-01,2020-07-02,2020-07-03,2020-07-06,2020-07-07,2020-07-08,2020-07-09,2020-07-10,2020-07-13,2020-07-14,2020-07-15,2020-07-16,2020-07-17,2020-07-20,2020-07-21,2020-07-22,2020-07-23,2020-07-24,2020-07-27,2020-07-28,2020-07-29,2020-07-30,2020-08-04,2020-08-05,2020-08-06,2020-08-07,2020-08-10,2020-08-11,2020-08-12,2020-08-13,2020-08-14,2020-08-17,2020-08-18,2020-08-19,2020-08-20,2020-08-21,2020-08-24,2020-08-25,2020-08-26,2020-08-27,2020-08-28,2020-08-31,2020-09-01,2020-09-02,2020-09-03,2020-09-04,2020-09-07,2020-09-08,2020-09-09,2020-09-10,2020-09-11,2020-09-14,2020-09-15,2020-09-16,2020-09-17,2020-09-18,2020-09-21,2020-09-22,2020-09-23,2020-09-24,2020-09-25,2020-09-28,2020-09-29,2020-09-30,2020-10-01,2020-10-02,2020-10-05,2020-10-06,2020-10-07,2020-10-08,2020-10-09,2020-10-12,2020-10-13,2020-10-14,2020-10-15,2020-10-16,2020-10-19,2020-10-20,2020-10-21,2020-10-22,2020-10-23,2020-10-26,2020-10-27,2020-10-28,2020-10-29,2020-10-30
DE000A1EWWW0,262.40,256.20,254.500,252.475,268.400,268.4000,272.850,279.60,282.35,282.50,284.1250,286.50,281.900,280.600,281.10,285.30,295.50,294.000,298.55,294.10,291.85,285.70,285.3750,283.300,284.05,279.15,280.200,278.00,278.00,275.550,269.000,268.350,270.65,274.4000,267.00,263.00,259.900,261.1500,263.0000,267.0000,261.55,263.700,264.05,270.2500,272.80,270.75,266.750,278.800,282.00,289.100,284.350,282.600,280.30,281.675,285.25,284.9000,293.55,297.30,299.000,297.95,296.900,300.90,300.00,298.50,301.45,301.20,299.45,301.950,303.95,304.90,306.700,304.8000,307.40,301.50,303.25,307.20,311.60,313.20,319.100,313.150,307.8000,308.85,313.050,310.55,316.00,336.25,322.75,317.95,306.800,308.80,309.50,309.00,312.00,317.70,312.30,308.50,305.25,305.450,311.90,315.85,...,297.05,299.15,301.95,298.40,294.55,294.05,296.80,288.75,284.90,286.55,284.15,287.700,280.60,258.80,259.60,252.05,259.85,256.85,260.60,258.85,262.30,265.95,266.100,270.30,271.50,269.10,277.20,277.90,277.55,277.60,280.45,282.35,280.00,276.75,271.30,276.55,270.75,266.20,265.00,263.70,261.70,261.80,279.80,282.00,278.00,281.00,287.00,285.00,287.50,294.50,298.90,300.00,290.10,282.80,280.20,271.50,279.20,289.50,290.20,293.00,288.20,292.40,288.70,290.60,291.40,295.20,288.80,290.90,295.30,297.70,292.050,292.300,279.80,283.900,278.50,278.60,274.60,275.000,278.50,270.90,262.000,265.60,270.70,276.70,270.25,278.00,285.10,285.30,286.20,295.20,281.900,289.80,286.80,288.200,292.300,295.10,288.50,291.70,289.600,295.40
DE0008404005,198.96,192.70,192.320,191.440,202.450,203.8000,203.575,203.25,202.75,204.75,205.2500,205.80,205.750,205.075,205.15,205.55,203.30,203.150,203.45,201.55,203.10,202.80,202.7000,201.150,200.95,201.20,201.300,198.54,199.00,198.640,199.240,199.080,198.54,198.6000,196.40,195.08,197.680,198.9400,198.5800,198.7000,195.30,197.400,194.84,195.3000,194.84,195.88,193.640,196.160,192.34,191.560,191.020,187.620,183.92,190.200,192.50,192.2600,192.84,194.74,193.300,194.18,196.580,197.70,198.66,196.98,197.72,199.30,198.26,198.240,199.00,198.94,200.775,200.8500,199.26,198.72,198.02,199.62,198.70,200.80,201.650,202.050,201.4000,201.30,199.600,197.72,192.88,190.50,192.14,193.70,210.000,211.50,210.30,210.20,211.00,210.50,208.85,207.60,203.60,201.100,208.95,210.70,...,214.10,215.35,216.50,214.95,213.55,217.40,217.65,217.35,214.65,213.65,210.90,215.175,214.15,212.70,221.50,216.75,219.90,216.40,216.60,218.05,216.35,217.45,216.275,216.05,216.20,215.60,219.10,219.05,215.45,217.25,218.60,219.30,218.75,218.80,220.00,218.35,217.20,217.05,219.55,214.60,213.25,212.35,212.55,211.85,212.00,214.75,216.15,210.10,211.45,213.50,213.90,213.80,213.45,213.65,215.30,207.65,210.00,208.40,206.80,203.00,199.75,202.00,200.75,198.26,194.92,195.38,194.86,197.86,198.98,199.35,195.730,196.680,196.30,195.080,195.58,195.70,195.96,193.140,192.32,188.26,186.520,190.92,190.30,193.23,190.48,195.28,198.24,200.25,201.00,200.75,202.150,203.20,201.10,203.000,203.375,205.75,205.75,206.80,196.580,198.62
DE000BASF111,59.27,57.93,57.930,57.860,61.620,61.9800,63.010,61.93,61.61,62.66,62.7350,62.90,62.210,62.660,62.35,62.00,61.73,62.125,62.00,61.53,62.50,62.07,62.9700,62.265,62.56,63.53,63.730,63.32,62.89,62.860,63.480,63.885,64.07,64.9500,65.22,65.01,64.470,64.1200,63.7100,63.3500,61.86,64.560,64.67,64.6100,65.87,65.87,64.970,64.720,63.70,63.920,63.480,62.270,61.66,63.100,65.21,64.7850,65.57,65.55,64.480,64.63,64.960,65.20,65.31,64.81,64.94,64.62,65.52,66.870,66.50,65.98,66.300,66.6100,65.22,64.78,65.37,68.01,67.77,68.14,69.155,68.750,68.0800,67.48,67.360,67.08,66.97,66.57,66.68,66.31,66.305,66.85,66.41,67.07,67.54,67.02,66.56,66.49,65.57,64.330,67.01,67.40,...,66.75,67.11,67.95,67.50,67.26,69.09,69.17,69.25,68.90,69.23,68.98,70.800,70.28,70.28,69.22,66.72,67.06,67.16,70.18,70.89,71.13,71.49,70.420,70.18,71.09,70.83,71.76,72.56,71.03,70.96,71.27,71.08,71.49,71.45,72.35,72.24,71.05,70.84,71.88,70.03,69.82,70.46,69.98,69.15,69.58,69.97,72.48,70.76,70.09,70.57,72.60,72.19,72.47,71.79,72.61,70.82,71.16,71.14,70.27,69.09,67.55,68.16,69.40,68.23,68.99,68.22,67.03,67.16,67.67,67.50,66.835,67.040,67.12,67.115,67.36,66.81,66.66,66.160,65.35,64.82,63.830,64.53,63.88,65.47,64.53,66.28,67.33,67.20,66.65,67.47,67.165,68.10,68.10,67.785,67.640,68.58,68.41,67.37,64.400,64.89
DE000BAY0017,45.34,44.65,45.325,45.535,47.465,47.5025,48.930,48.29,48.18,49.31,49.9025,50.24,50.415,50.930,50.95,51.33,50.77,50.150,49.65,49.97,50.24,50.03,49.4925,48.725,48.71,48.51,48.825,48.56,48.31,48.105,48.155,47.290,46.63,48.0375,47.78,47.08,47.695,48.6775,47.8825,47.4075,46.22,46.155,46.64,46.4425,47.10,47.38,46.925,47.465,46.49,46.495,46.555,45.705,45.20,45.075,45.65,45.4725,45.83,45.91,45.745,45.56,46.615,47.38,47.74,47.49,47.69,47.26,47.01,47.145,47.31,47.33,47.760,48.0725,47.79,47.41,47.56,47.85,47.85,47.64,47.765,47.965,47.2825,47.29,47.215,47.02,46.04,49.75,50.16,50.56,50.360,51.16,50.52,50.59,51.37,51.20,51.15,51.06,50.25,49.365,50.67,50.53,...,54.97,55.29,55.92,55.72,55.77,56.33,56.77,57.12,56.96,57.30,53.28,54.370,53.99,53.78,53.49,52.31,53.47,53.82,53.15,53.45,54.25,54.91,54.510,55.69,56.00,54.14,54.96,54.13,52.88,52.90,52.98,53.05,53.34,53.36,53.51,53.78,53.23,53.92,53.78,53.37,53.21,53.21,53.65,54.14,53.39,53.40,53.80,52.81,52.91,53.04,52.95,52.43,54.46,53.05,53.17,51.48,51.84,51.62,52.06,52.34,50.02,51.59,55.00,53.34,53.94,53.90,53.11,53.98,54.55,54.94,53.900,53.965,54.09,55.190,55.32,55.80,54.03,51.465,51.26,50.48,49.915,50.93,50.09,51.93,51.43,52.36,53.00,53.66,53.01,52.56,52.090,52.69,52.59,50.340,50.980,51.50,52.32,51.43,49.475,49.29